### ISSUE TITLE
Use exact constants for cubic feet and cubic meters

### ISSUE THREAD

**Issue by bimwood** [angularsen/UnitsNet#1006]
**Is your feature request related to a problem? Please describe.**
UnitsNet is great, but the constants it uses for conversion to/from square feet and cubic feet are not exact - and exact values exist! :). This causes me problems because my code uses another API that uses the exact values.

**Describe the solution you'd like**
Please change the sqft constant from 0.092903 to 0.09290304 in Area.json lines 199/200
Please change the cuft constant from 0.0283168 to 0.028316846592 in Volume.json lines 180/181

**Describe alternatives you've considered**
Currently I have to avoid using UnitsNet area and volume conversions. So I convert into UnitsNet base units in my code, like this:
Area.FromSquareMeters(areaInSquareFeet * SQUARE_FEET_TO_SQUARE_METERS)
where SQUARE_FEET_TO_SQUARE_METERS is a constant set to 0.09290304.
It works, but it's not very elegant. 

**Additional context**
I realise the current constants meet the 1E-5 goal, so this is a feature request rather than a bug. :)

**Comment by angularsen** [comment]
Thanks for the detailed description. We'll definitely take the more precise constants.
If you want to attempt a PR, let me know. If not, I may find time to get around to this sometime after new year's eve.

**Comment by bimwood** [comment]
Thanks!
I'd have liked to attempt a PR but my VS Git is erroring when cloning my UnitsNet fork (poss something to do with Git LFS? I need to do more digging)
If you do get around to this constants fix, that would be great. Thank you.

**Comment by angularsen** [comment]
Right, you may need to install Git LFS: https://git-lfs.github.com/

I'll comment here if and when I take it on.

**Comment by tmilnthorp** [comment]
@bimwood I added a PR to update these for you

**Comment by angularsen** [comment]
@bimwood Nuget is on the way out.

[Release UnitsNet/4.117.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.117.0)
