### ISSUE TITLE
Add Deca prefix for length unit

### ISSUE THREAD

**Issue by JasLieb** [angularsen/UnitsNet#1034]
**Is your feature request related to a problem? Please describe.**
I want to use Decameter unit but isn't available yet.
For example, I have to convert decameter to meter or another else length unit

**Describe the solution you'd like**
Add Decameter enum value in available LengthUnit

Sorry in advance for my bad English or my misunterstanding of the code of conduct or bad issue writing.

**Comment by angularsen** [comment]
Nuget on the way.

[Release UnitsNet/4.119.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.119.0)
