### ISSUE TITLE
Custom unit name mapping to existing unit

### ISSUE THREAD

**Issue by bobbyalex** [angularsen/UnitsNet#1046]
What is the easiest way to map a custom string to an existing unit name so that it can be passed to the `ConvertByName` method?

For eg: I want to map the string `Centi` to the existing `Centimeter` unit so that I can pass it to the convert method:
`UnitConverter.ConvertByName(1, "Length", "Centi", "Millimeter");`

It will be functionally equivalent to 
`UnitConverter.ConvertByName(1, "Length", "Centimeter", "Millimeter");`

This is useful in systems which have their own unit strings that cant be changed. Is there an easy way to do this?

**Comment by angularsen** [comment]
@bobbyalex Hi, this is currently not supported, but if you are interested in trying to add support for it we are happy to assist you.

This wiki explains what is currently possible:
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units
