### ISSUE TITLE
Adding unit for Flexural Modulus 

### ISSUE THREAD

**Issue by vidzilla** [angularsen/UnitsNet#1061]
Hello ! 
I'd like to add in a new unit for flexural modulus (also called [section modulus](https://en.wikipedia.org/wiki/Section_modulus)). Just wanted to check with everyone if this is okay or if someone's already working on this ? 

I want to add it since the unit for this quantity is the same as 'Volume', but using 'Volume' in code with engineering calculations using section moduli gets very confusing/misleading very quickly. 

Happy to add more details if needed. 

Edit - Re use cases, it is used extensively in structural (and also likely mechanical) engineering calculations

**Comment by angularsen** [comment]
Hi @vidzilla , are there other related quantities that would make sense to also add if we do add section modulus? For example `Speed * Duration = Length`.

The wiki describes these seemingly related quantities:
> Other geometric properties used in design include [area](https://en.wikipedia.org/wiki/Area) for tension and shear, [radius of gyration](https://en.wikipedia.org/wiki/Radius_of_gyration) for compression, and [moment of inertia](https://en.wikipedia.org/wiki/Moment_of_inertia) and [polar moment of inertia](https://en.wikipedia.org/wiki/Polar_moment_of_inertia) for stiffness.

If there is sufficient added value to bring in one over using `Volume`, then I think I'm positive to add it.
