### ISSUE TITLE
UnitsNet NuGet and App Center

### ISSUE THREAD

**Issue by madcockpatterson** [angularsen/UnitsNet#1076]
When using UnitsNet as a NuGet package in my UWP/NetStandard UI, When I cut a release and Distribute it to Microsoft App Center; their Malware checker removes my App. When I remove UNitsNet it does not get removed. They are thinking that the use of log4j is causing the issue.

**Comment by angularsen** [comment]
That's weird, is this the UnitsNet nuget or the
UnitsNet.WindowsRuntimeComponent nuget?

UnitsNet has no nuget dependencies and it is definitely not bundling log4j
to my knowledge. The WRC variant may bring in some extra stuff, I haven't
checked, but unless you are targeting JavaScript or c++ UWP apps you should
be using the main UnitsNet nuget.

Do you see these files as part of UnitsNet nupkg file?
You can unzip the unitsnet nupkg file and see all the contents there.

I would suspect maybe some other component is adding it.

**Comment by angularsen** [comment]
On the phone here so limited access, but we are depending on these nugets.

Maybe some of them bring in something unexpected?


<ItemGroup>
<PackageReference Include="JetBrains.Annotations" Version="2019.1.3"
PrivateAssets="All" />
<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0"
PrivateAssets="All" />
</ItemGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net40'">
<PackageReference Include="System.ValueTuple" Version="4.5.0" />
</ItemGroup>

**Comment by madcockpatterson** [comment]
We are using the Main UnitsNet NuGet for C# UWP. I have not found a Log4j but when talking with APP Center they told us to remove Log4J. UnitsNet is the only non-Microsoft NuGet package we use, so I removed it to test and App center did not remove it. Im going to cut another release and verify. So idk if log4j has anything to do with it but they pointed it out, but their malware is picking something up. They are still looking and has been about a week.

**Comment by angularsen** [comment]
Did you resolve it?

I am closing this issue since there is currently no clear path forward. Please reopen if a fix is necessary.

**Comment by madcockpatterson** [comment]
I did not, but its not an issue with UnitsNet. Sorry for the confusion.
