### ISSUE TITLE
Add support for darcy?

### ISSUE THREAD

**Issue by sveipa** [angularsen/UnitsNet#1077]
**Story**
As a developer working in fluid mechanics in the oil & gas industry
I would like to use a very common unit for handling permeability called `darcy`
so that it can be converted back/from SI units for normalization.

**References**
- [https://en.wikipedia.org/wiki/Darcy_(unit](https://en.wikipedia.org/wiki/Darcy_%28unit))
- [https://en.wikipedia.org/wiki/Permeability_(Earth_sciences)#Units](https://en.wikipedia.org/wiki/Permeability_%28Earth_sciences%29#Units)
- [https://www.slb.com/-/media/files/oilfield-review/defining-permeability.ashx](https://www.slb.com/-/media/files/oilfield-review/defining-permeability.ashx)

**Additional context**
Permeability in fluid mechanics is a measure of the ability of a porous material to allow fluids to pass through it.
Most frequently encountered variants of permeability is
- Darcy (D)
- millidarcy (md)
- microdarcy (µD)
- m^2
- cm^2

Note: There are several different permeabilities that are unrelated, for instance for *magnetism* - see https://en.wikipedia.org/wiki/Permeability_(electromagnetism) so prefixing/suffixing the unit type is important.

**Comment by angularsen** [comment]
It seems we already took the name Permeability for elecromagnetism, currently with a single unit `HenryPerMeter`.

It seems these units are commonly used in this domain at least, so I'm fine with adding them. Are you interested in attempt a pull request?

Also, should it be named `MediumPermeability`? `FluidMechanicsPermeability`? You know best.

**Comment by sveipa** [comment]
@angularsen Yes, we can plan for a pull request. Permeability is a property of the porous medium, so maybe `PorousMediumPermeability' is an alternative. Will think about it some more.

**Comment by KZajdel** [comment]
I created PR with permeability units for fluid mechanics:
https://github.com/angularsen/UnitsNet/pull/1079

**Comment by angularsen** [comment]
Closed by #1079
