### ISSUE TITLE
Custom dynamic units

### ISSUE THREAD

**Issue by percramer** [angularsen/UnitsNet#1080]
Hi,

i am testing UnitsNet and thing are looking pretty good. A am using it in a database driven program, and most of my data/information is all dynamically generated (or received from the database as values). 

I can do quite a lot by using the UnitConverter.ConvertByName() function. But I also have some custom conversions setup in my database. And there I am having problems since UnitsNet is mostly based on existing enums / structures for creating custom units. I can generate a enum dynamically but not the other needed info I guess. Are there other ways to create custom units?

**Comment by angularsen** [comment]
Hi, some info on custom units here:
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units

In the upcoming v5, we are doing some breaking changes trying to move away from enums and use strings more. Things may be easier for you there, so I recommend you give that branch or nuget a try and report back if there are still things you are missing we could improve.
