### ISSUE TITLE
Add FromPoundsForcePerSquareMil (lbs/mil²) to Pressure

### ISSUE THREAD

**Issue by rutemja** [angularsen/UnitsNet#1091]
**Is your feature request related to a problem? Please describe.**
Our machines need to show the E-Module in lbs/mil² to our American users. UnitsNet already supports lbs/in², but lbs/mil² is missing.

**Describe the solution you'd like**
Please add lbs/mil² to Pressure class.

These should be the correct functions to calculate it from Pascal:
```
"FromUnitToBaseFunc": "{x} * 6.894757293168361e9",
"FromBaseToUnitFunc": "{x} / 6.894757293168361e9",
```

Thank you :)

**Comment by angularsen** [comment]
Fixed in #1092
