### ISSUE TITLE
nanoFramework fails to build on VS2022

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#1094]
@josesimoes Hi, we're having trouble building `release/v5` branch with AppVeyor VS2022 image.

Is this a known issue with VS2022?

`master` branch with VS2019 image builds just fine.

I tried both `v5` branch's older vsix gallery method of installing, and the newer github releases method of installing the vsix that you provided to `master` branch earlier. Both seems to copy the files into VS installation as expected, but they both fail with 

https://ci.appveyor.com/project/angularsen/unitsnet/builds/43753694
```
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\nanoFramework\v1.0\NFProjectSystem.MDP.targets(760,5): 
error MSB4062: The "GenerateBinaryOutputTask" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll. 
Could not load file or assembly 'file:///C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll' or one of its dependencies. 
An attempt was made to load a program with an incorrect format. 
Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 
```

**Comment by josesimoes** [comment]
Yes I know what's happening. That's caused by VS 2022 becoming 64bits. When building from the command line you have to give it a hint about that.

Haven't look at the pipeline for v5 but I'm assuming it's still running on appveyor. I'll search and let you know what's the correct option to add (if it was on ADO I would know it 😉).
