### ISSUE TITLE
The same abbreviation for InverseKilopascal and InverseMegapascal (Compressibility)

### ISSUE THREAD

**Issue by KZajdel** [angularsen/UnitsNet#1096]
**Describe the bug**
InverseKilopascal and InverseMegapascal units in Compressibility have the same abbreviation, so an exception is thrown when trying to parse it

**To Reproduce**
Try to execute: `UnitParser.Default.Parse("kPa⁻¹", typeof(UnitsNet.Units.CompressibilityUnit))`
Exception is thrown: "Cannot parse "kPa⁻¹" since it could be either of these: InverseKilopascal, InverseMegapascal"

**Expected behavior**
Value is parsed without any exception

**Comment by angularsen** [comment]
@KZajdel Hi, thanks for reporting. I just merged a fix, if you could give it a try.
Nuget should be out shortly.

[Release UnitsNet/4.134.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.134.0)
