### ISSUE TITLE
StackOverflowException using Lenght unit and quantity.ToUnit() .Introduced in version 4.142.0

### ISSUE THREAD

**Issue by BartoszPierzchlewiczMacrix** [angularsen/UnitsNet#1116]
Probably due to the introduction of LengthUnit.Angstrom.
Unfortunately no further bug details.
Downgrading to 4.141.0 solves the problem.
Exception also occurs in most up to date version 4.143.0

**Comment by angularsen** [comment]
Thanks, do you have a short code snippet that reproduces?

**Comment by angularsen** [comment]
Fixed by #1119

**Comment by angularsen** [comment]
[Release UnitsNet/4.144.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.144.0)
