### ISSUE TITLE
Parse quantity without knowing the unit type

### ISSUE THREAD

**Issue by jeisenbach-schulzst** [angularsen/UnitsNet#1120]
Hi and thanks for this great lib.

**Is your feature request related to a problem? Please describe.**
I receive measurements like `"230V"`, `"27°C"`, `"1000kWh"` etc.
Is it possible to do something like
`var quantity = Quantity.Parse("27°C");`
without knowing the unit (temperature) in advance?

Thanks and best regards
Jens

**Comment by angularsen** [comment]
Hi, yes it is possible, but with a few limitations:
- Unit abbreviations may be ambiguous across different quantities, for example `m` may mean minutes or meters. Sometimes also within the same quantity, but that is more rare.
- You need a space between number and unit abbreviation.
- It will prefer case-sensitive match in case of ambiguity per quantity, but falls back to case-insensitive. See example below.

```cs
IQuantity? parsedQuantity = Quantity.Infos
.Select(q => Quantity.TryParse(q.ValueType, "27 °C", out IQuantity? parsed) ? parsed : null)
.SingleOrDefault(obj => obj != null); // Parsed as Temperature.
```

Example of ambiguity:
![image](https://user-images.githubusercontent.com/787816/185455116-d13746f1-8bb0-4c78-b810-198574124e1b.png)

**Comment by jeisenbach-schulzst** [comment]
Thanks for your quick response!

br
