### ISSUE TITLE
Power constructor uses decimal

### ISSUE THREAD

**Issue by Henje** [angularsen/UnitsNet#1121]
**Describe the bug**
In a generic function I am constructing UnitsNet types from a double and a corresponding unit. But the power type cannot be constructed using a double as it takes a decimal. From my limited search it seems all the other units take a double. This inconsistency makes it hard to use the types in generic code.

**To Reproduce**
Steps to reproduce the behavior (just an example):
1. `var a = new Power(1.5, PowerUnit.Watt);` does not compile

**Expected behavior**
It should work like `var a = new Length(1.5, LengthUnit.Meter);`. Alternatively, all constructors could take a decimal.

**Additional Context**
For a quick workaround, I can cast the double to a decimal, because decimal is implicitly convertible to double. Nevertheless, this inconsistency only surfaced after trying to use the code with power, which could have been avoided, if all constructors were consistent.

**Comment by Brunni** [comment]
Hi.
As far as I can see, this was a decision made by choice to have better precision:
https://github.com/angularsen/UnitsNet/wiki/Precision

If you would use the "Power.From" factory method, it accepts both double and decimal as it accepts "QuantityValue"

**Comment by Henje** [comment]
This is a rather unfortunate design. We currently use Activator.CreateInstance to construct UnitsNet objects from a type. This requires us to use the correct types. The alternative route via From can only be done by resolving the function ourselves via reflection.

Not impossible to work around, but unfortunate. Or is there an alternative way to construct the correct quantity using a double and a unit (like a value of PowerUnit)?

**Comment by Brunni** [comment]
I think what you are looking for is Quantity.From method:

```
double quantityValue = 12.12;
Quantity.From(quantityValue, PowerUnit.Microwatt);
```

**Comment by Henje** [comment]
Yes, Quantity.From works. Thanks for your help.
