### ISSUE TITLE
Fully embrace INumber and generic math of .NET 7

### ISSUE THREAD

**Issue by bitbonk** [angularsen/UnitsNet#1129]
.NET 7 will introduce the [INumber&lt;TSelf&gt;](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.inumber-1?view=net-7.0) interface (along with accompanying with C# 11 features) that make a feature called [generic math](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/) possible.

I think this would be a perfect fit for the quantities of UnitsNet and could potentially make the usage way more intuitive, flexible and overall enjoyable.

Please consider to fully embrace `INumber<TSelf>`  and generic math in a future version of UnitsNet.

Here is a short introduction to this feature set by @MadsTorgersen (first 25 minutes): [Where's C# headed? - Mads Torgersen - NDC Copenhagen 2022](https://youtu.be/v8bqAm4aUFM)
Official documentation: https://docs.microsoft.com/en-us/dotnet/standard/generics/math

**Comment by tmilnthorp** [comment]
The biggest question is the supported deployments. Do we abandon netstandard/netframework support just for generic math? Neither are EOL yet.

**Comment by tmilnthorp** [comment]
We already do, but without too many #ifs. I fear that the API support for generic math vs precompiled lambdas would be difficult to maintain with equivalent functionality. But definitely worth a try.

**Comment by bitbonk** [comment]
My guess would be that [IQuantity&lt;TUnitType&gt;>](https://github.com/angularsen/UnitsNet/blob/77b1ef2e86fa8961650c281ec3aad6521dcd3963/UnitsNet/IQuantity.cs#L112) would need to derive from [INumber&lt;TSelf&gt;](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.inumber-1?view=net-7.0) somehow, right?

**Comment by angularsen** [comment]
@bitbonk An early prototype here to explore how it can be used.
#984

I haven't yet looked into what the changes were compared to the experimental interfaces at the time, but I assume it is in the ballpark similar.

**Comment by angularsen** [comment]
Some support for generic math was added in #1164 , it can be extended further.

**Comment by bitbonk** [comment]
> Some support for generic math was added in #1164 , it can be extended further.

Awesome! What version of UnitsNet has generic math included?

**Comment by angularsen** [comment]
https://github.com/angularsen/UnitsNet/pull/1164/files#diff-88adba83458faa7e4ec81b932cb85045c84f3b9e1b077bbc647167910cd07efa
