### ISSUE TITLE
Readonly structs

### ISSUE THREAD

**Issue by sonnemaf** [angularsen/UnitsNet#1130]
Should/could the structs in this project be made `readonly`. I think they should. All primitive struct types from Microsoft are readonly. 

Readonly structs have a lot of advantages where there are no defensive copies for `readonly fields`, `in parameters`, 'readonly locals + returns`.

**Comment by Brunni** [comment]
As far as I see, everything compiles with `public readonly partial struct` as well.

**Comment by angularsen** [comment]
Sounds like a good improvement as long as it compiles for nestandard2.0. 
These structs were intended to be immutable already.

Would you be interested in attempting a pull request @sonnemaf ?

**Comment by sonnemaf** [comment]
Hi @angularsen 

Good news but unfortunately I don't have time to implement it the next few weeks. Is it in a hurry? I will probably have time for it in october.

**Comment by angularsen** [comment]
No rush on my end :-)

**Comment by sonnemaf** [comment]
Hi,

I'm unable to clone the repository. I keep getting this error. Tried it on two computers.

![image](https://user-images.githubusercontent.com/9335559/196702403-8c6f8746-92e0-4ddf-8fb8-4ad1617ceadd.png)

I'm giving up. The change is really small. You only have to add the readonly text to the UnitsNet\CodeGen\Generators\UnitsNetGen\QuantityGenerator.cs on line 75, see screenshot below.

![image](https://user-images.githubusercontent.com/9335559/196702907-105fd842-e468-49af-b3a6-ea19cd7f121f.png)

Can you do it yourself?

Regards,

Fons

**Comment by Brunni** [comment]
There is already a PR for this. https://github.com/angularsen/UnitsNet/pull/1135
Currently the maintainer @angularsen seems to be unavailable.

**Comment by angularsen** [comment]
@sonnemaf Sorry for the friction. You need to install Git LFS to clone the repo.
https://git-lfs.github.com/

LFS is nice when it works, but GitHub charges for it when monthly bandwidth exceeds a certain amount. 
#1052 suggests downloading tooling binaries on-demand with an init script, instead of having it happen during checkout.
