### ISSUE TITLE
Add quantity for Impulse (integral of force over time)

### ISSUE THREAD

**Issue by Sigvess92** [angularsen/UnitsNet#1139]
We are using UnitsNet to handle force plate data and derived metrics. We utilize quantities such as Force, Torque and ForceChangeRate, but have not been able to figure out what to do with impulse data ([integral of force over time](https://en.wikipedia.org/wiki/Impulse_(physics))). Creating and maintaining our own impulse type is not optimal, especially if it could also be of use to others by adding it to the main repo.

Does a suitable quantity for impulse exist already under a different name? Is there a reason why such a quantity doesn't/shouldn't be a part of UnitsNet or can it be added? I could contribute with a PR on this request if accepted.

**Comment by Brunni** [comment]
Did you check https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for further information?

**Comment by Sigvess92** [comment]
> Did you check https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for further information?

Yes, and it seems to me that it should tick all the boxes in the "A quantity is a good fit to add" section. Did you mean to refer to a specific point in the document?

**Comment by angularsen** [comment]
@Sigvess92 
Sorry for the late reply, I have been missing out on email notifications for some time.

I think Impulse is a great fit, please go ahead with the PR.

What units do you propose?

I see some commone ones here:
https://www.translatorscafe.com/unit-converter/en-US/impulse/

**Comment by Sigvess92** [comment]
@angularsen 
Great! Will hopefully get it prioritized soon.

Newton seconds is by far the most common unit, but it is probably a good idea to include everything in the source you linked.

**Comment by Sigvess92** [comment]
@angularsen Created PR: https://github.com/angularsen/UnitsNet/pull/1178

**Comment by angularsen** [comment]
Merged by #1178
