### ISSUE TITLE
[Support] Parsing PJ

### ISSUE THREAD

**Issue by akasolace** [angularsen/UnitsNet#1142]
First of all, thank you for making this library open-source.

In my energy conversion app, I am using the function `Energy.TryParseUnit()`. 

I had already encountered not recognized abbreviations that I could fix using `MapUnitToDefaultAbbreviation`, for example: 
 
`UnitAbbreviationsCache.Default.MapUnitToDefaultAbbreviation(VolumeUnit.CubicKilometer, "bcm");`

But now I have encountered unit PetaJoule "PJ" and the parsing is throwing an error. I have tried something like the following but it does not work 
`UnitAbbreviationsCache.Default.MapUnitToDefaultAbbreviation(new Energy(1000, EnergyUnit.Gigajoule), "joule");`  

Any help would be welcome. 

Thank you

**Comment by Brunni** [comment]
Hi. As far as I can see, Petajoule is currently not available as EnergyUnit, right?

https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Units/EnergyUnit.g.cs

So I guess we would need to create a PR to add PJ.

Of course, the question is then about TeraJoule, ExaJoule etc. https://en.wikipedia.org/wiki/Orders_of_magnitude_(energy)

**Comment by akasolace** [comment]
@Brunni I think I have a PR ready. However, I could not run the test because the project cannot build despite having installed .NET 5.0.  (VS Studio is asking me to install many other framework like 4.0, 4.7.2, to build the project) I am using visual studio 2022 preview are you aware of any issue regarding using the outdated framework with the latest VS studio? 

![image](https://user-images.githubusercontent.com/1136496/197869993-bb583557-aefb-4098-9b7c-21441393fd18.png)

**Comment by angularsen** [comment]
@akasolace Try removing `net40;net47` temporarily from `UnitsNet.csproj` and any other projects, if you don't have these frameworks installed.

```
    <TargetFrameworks>netstandard2.0;net40;net47</TargetFrameworks>
```

**Comment by akasolace** [comment]
@angularsen indeed removing net4.0 allowed me to build and run the test that were all successful. 
I removed the draft status to my PR #1143 , but it does not pass the CI (see https://ci.appveyor.com/project/angularsen/unitsnet/builds/45180101).  Please let me know what I should do next to finalize this PR .... thank you

**Comment by angularsen** [comment]
I'm not sure what wrong exactly, but master branch built just fine now and also we have recently switched to Azure DevOps: https://dev.azure.com/unitsnet/Units.NET

**Comment by angularsen** [comment]
v5 was merged into master, so net40 and net47 targets are no longer present.
