### ISSUE TITLE
Get abbreviation from IQuantity

### ISSUE THREAD

**Issue by rolandow** [angularsen/UnitsNet#1155]
I would like to show the localized abbreviation based on a IQuantity.

I managed to construct a quantity based on values from the database; a quantity and a string represented in this format: LengthUnit.Centimeter. I used the same method as the json converter to get it back to a Quantity.

Now in my application I would like to show only the abbreviation of the unit, using the localization support from Units.NET. But since I only have my IQuantity object, I cannot figure out a way to get to the abbreviation ("cm" in this case).

So, I got this working, by creating an extension method:

```csharp
var quantity = 25;
string myUnit = "LengthUnit.Centimeter";
IQuantity q = quantity.ToQuantity(myUnit);
```

I am using the 5.0 alpha release.

**Comment by rolandow** [comment]
I can access the AbbrevationCache, but I cannot search for an abbrevation based on a string. That would be helpfull. Or add the GetAbbrevation to the IQuantity interface?

**Comment by tmilnthorp** [comment]
You should be able to call .ToString(“a”);

Call the overload with the culture.

**Comment by rolandow** [comment]
Hmm, I had to add the cultureinfo, so `q.ToString("a", null)` seems to work. Thanks!
