### ISSUE TITLE
Please Add "MegaJoulePerTonne" to SpecificEnergy

### ISSUE THREAD

**Issue by kuhnm** [angularsen/UnitsNet#1168]
From an third party system I get measurements. 
They have specific energy values with an unit abbreviation of "MJ/t".  (MegaJoulePerTonne)
Physical this is the same like KiloJoule/Kilogramm.
I can't change this in the data source, so I ask for either an added Abbreviation or a new unit.

**Comment by angularsen** [comment]
I believe this could be added relatively easy as a new unit `MegaJoulePerTonne` to the `SpecificEnergy` quantity.

Would you be interested in attempting a pull request?

Steps here, and I'm happy to assist.
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

**Comment by kuhnm** [comment]
Thank You!
After some holidays I started to prepare a machine with the requirements.
But .Net5 SDK is not any more supported and my company security rules don’t like unsupported software.
Is it also possible to use .Net6 ?

Mit freundlichen Grüßen,
Matthias Kuhn
Softwareentwickler
Informationstechnologie für Erzeugung (C-TIER)
EnBW Energie Baden-Württemberg AG
Durlacher Allee 93 · 76131 Karlsruhe
Telefon +49 (0) 7 21/63- 1 25 73· Fax +49 721 63-1 31 66
***@***.***
www.enbw.com<http://www.enbw.com/>

[JUNI_18/Logos/Rund/Bearbeitet/FB.png]<https://de-de.facebook.com/EnBW/>  [JUNI_18/Logos/Rund/Bearbeitet/Insta.png] <https://www.instagram.com/enbw_ag/>   [JUNI_18/Logos/Rund/Bearbeitet/TW.png] <https://twitter.com/enbw?lang=de>   [JUNI_18/Logos/Rund/Bearbeitet/TY.png] <https://www.youtube.com/user/enbw>

EnBW Energie Baden-Württemberg AG · Sitz der Gesellschaft: Karlsruhe
Amtsgericht Mannheim · HRB Nr. 10795
Vorsitzender des Aufsichtsrats: Lutz Feldmann
Vorstand: Andreas Schell (Vorsitzender), Dirk Güsewell, Thomas Kusterer, Colette Rückert-Hennen, Dr. Georg Stamatelopoulos

Von: Andreas Gullberg Larsen ***@***.***>
Gesendet: Dienstag, 13. Dezember 2022 23:42
An: angularsen/UnitsNet ***@***.***>
Cc: Kuhn Matthias ***@***.***>; Author ***@***.***>
Betreff: Re: [angularsen/UnitsNet] Please Add "MegaJoulePerTonne" to SpecificEnergy (Issue #1168)


I believe this could be added relatively easy as a new unit MegaJoulePerTonne to the SpecificEnergy quantity.

Would you be interested in attempting a pull request?

Steps here, and I'm happy to assist.
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fangularsen%2FUnitsNet%2Fwiki%2FAdding-a-New-Unit&data=05%7C01%7Cm.kuhn%40enbw.com%7C71bbcafd5434409bde3308dadd5b38f7%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C638065681129473949%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dfFvAbFB%2FpXWVjEzqy8ef4ZqlhhszGC%2FGfFKDnybNHI%3D&reserved=0>

**Comment by angularsen** [comment]
@kuhnm The release/v5 branch was merged into master branch in December. I believe all net5.0 has been upgraded to net6.0 since then. Please fetch the latest master branch and give it another go?

**Comment by kuhnm** [comment]
I downloaded master on Monday.
But the question was because in the docu you linked is: .NET5.0 as prerequisite


Mit freundlichen Grüßen,
Matthias Kuhn
Softwareentwickler
Informationstechnologie für Erzeugung (C-TIER)
EnBW Energie Baden-Württemberg AG
Durlacher Allee 93 · 76131 Karlsruhe
Telefon +49 (0) 7 21/63- 1 25 73· Fax +49 721 63-1 31 66
***@***.***
www.enbw.com<http://www.enbw.com/>

[JUNI_18/Logos/Rund/Bearbeitet/FB.png]<https://de-de.facebook.com/EnBW/>  [JUNI_18/Logos/Rund/Bearbeitet/Insta.png] <https://www.instagram.com/enbw_ag/>   [JUNI_18/Logos/Rund/Bearbeitet/TW.png] <https://twitter.com/enbw?lang=de>   [JUNI_18/Logos/Rund/Bearbeitet/TY.png] <https://www.youtube.com/user/enbw>

EnBW Energie Baden-Württemberg AG · Sitz der Gesellschaft: Karlsruhe
Amtsgericht Mannheim · HRB Nr. 10795
Vorsitzender des Aufsichtsrats: Lutz Feldmann
Vorstand: Andreas Schell (Vorsitzender), Dirk Güsewell, Thomas Kusterer, Colette Rückert-Hennen, Dr. Georg Stamatelopoulos

Von: Andreas Gullberg Larsen ***@***.***>
Gesendet: Donnerstag, 12. Januar 2023 11:36
An: angularsen/UnitsNet ***@***.***>
Cc: Kuhn Matthias ***@***.***>; Mention ***@***.***>
Betreff: Re: [angularsen/UnitsNet] Please Add "MegaJoulePerTonne" to SpecificEnergy (Issue #1168)


@kuhnm<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkuhnm&data=05%7C01%7Cm.kuhn%40enbw.com%7C73d5085e3e7c456027d208daf488c9bd%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C638091165587909491%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ldNmwKP14P0kOagxNEflpyfE3kEnLELvUjrztvVguAQ%3D&reserved=0> The release/v5 branch was merged into master branch in December. I believe all net5.0 has been upgraded to net6.0 since then. Please fetch the latest master branch and give it another go?

**Comment by angularsen** [comment]
Aha, I updated the docs now

**Comment by kuhnm** [comment]
Thank you,
I made a local branch and wanted to upload it, but I get a GitHub refusal
I tried VisualStudio2022 and git for windows.

"C:\Program Files\Git\bin\git.exe" push -u --recurse-submodules=check --progress "origin" refs/heads/add-MegaJoulePerTonne-unit:refs/heads/add-MegaJoulePerTonne-unit
warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information
info: please complete authentication in your browser...
remote: Permission to angularsen/UnitsNet.git denied to kuhnm.
fatal: unable to access 'https://github.com/angularsen/UnitsNet.git/': The requested URL returned error: 403
Done
I have an GitHub User Account, but never pushed anything to Github.


Mit freundlichen Grüßen,
Matthias Kuhn
Softwareentwickler
Informationstechnologie für Erzeugung (C-TIER)
EnBW Energie Baden-Württemberg AG
Durlacher Allee 93 · 76131 Karlsruhe
Telefon +49 (0) 7 21/63- 1 25 73· Fax +49 721 63-1 31 66
***@***.***
www.enbw.com<http://www.enbw.com/>

[JUNI_18/Logos/Rund/Bearbeitet/FB.png]<https://de-de.facebook.com/EnBW/>  [JUNI_18/Logos/Rund/Bearbeitet/Insta.png] <https://www.instagram.com/enbw_ag/>   [JUNI_18/Logos/Rund/Bearbeitet/TW.png] <https://twitter.com/enbw?lang=de>   [JUNI_18/Logos/Rund/Bearbeitet/TY.png] <https://www.youtube.com/user/enbw>

EnBW Energie Baden-Württemberg AG · Sitz der Gesellschaft: Karlsruhe
Amtsgericht Mannheim · HRB Nr. 10795
Vorsitzender des Aufsichtsrats: Lutz Feldmann
Vorstand: Andreas Schell (Vorsitzender), Dirk Güsewell, Thomas Kusterer, Colette Rückert-Hennen, Dr. Georg Stamatelopoulos

Von: Andreas Gullberg Larsen ***@***.***>
Gesendet: Donnerstag, 12. Januar 2023 12:57
An: angularsen/UnitsNet ***@***.***>
Cc: Kuhn Matthias ***@***.***>; Mention ***@***.***>
Betreff: Re: [angularsen/UnitsNet] Please Add "MegaJoulePerTonne" to SpecificEnergy (Issue #1168)


Aha, I updated the docs now

**Comment by angularsen** [comment]
You need to fork the repo to get your own copy at github.com/{your_username}, then you are allowed to push the branch there and create a pull request back to the original repository.

Some more information in step 6 of the wiki:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#6-create-pull-request

Let me know if you have trouble figuring it out, I'll try to assist.

**Comment by kuhnm** [comment]
Thank You!
After a working week with customers, I just got the time to upload the changes.
I also created a pull request (https://github.com/angularsen/UnitsNet/pull/1184)
and hope You like it.


Mit freundlichen Grüßen,
Matthias Kuhn
Softwareentwickler
Informationstechnologie für Erzeugung (C-TIER)
EnBW Energie Baden-Württemberg AG
Durlacher Allee 93 · 76131 Karlsruhe
Telefon +49 (0) 7 21/63- 1 25 73· Fax +49 721 63-1 31 66
***@***.***
www.enbw.com<http://www.enbw.com/>

[JUNI_18/Logos/Rund/Bearbeitet/FB.png]<https://de-de.facebook.com/EnBW/>  [JUNI_18/Logos/Rund/Bearbeitet/Insta.png] <https://www.instagram.com/enbw_ag/>   [JUNI_18/Logos/Rund/Bearbeitet/TW.png] <https://twitter.com/enbw?lang=de>   [JUNI_18/Logos/Rund/Bearbeitet/TY.png] <https://www.youtube.com/user/enbw>

EnBW Energie Baden-Württemberg AG · Sitz der Gesellschaft: Karlsruhe
Amtsgericht Mannheim · HRB Nr. 10795
Vorsitzender des Aufsichtsrats: Lutz Feldmann
Vorstand: Andreas Schell (Vorsitzender), Dirk Güsewell, Thomas Kusterer, Colette Rückert-Hennen, Dr. Georg Stamatelopoulos

Von: Andreas Gullberg Larsen ***@***.***>
Gesendet: Dienstag, 17. Januar 2023 20:05
An: angularsen/UnitsNet ***@***.***>
Cc: Kuhn Matthias ***@***.***>; Mention ***@***.***>
Betreff: Re: [angularsen/UnitsNet] Please Add "MegaJoulePerTonne" to SpecificEnergy (Issue #1168)


You need to fork the repo to get your own copy at github.com/{your_username}, then you are allowed to push the branch there and create a pull request back to the original repository.

Some more information in step 6 of the wiki:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#6-create-pull-request<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fangularsen%2FUnitsNet%2Fwiki%2FAdding-a-New-Unit%236-create-pull-request&data=05%7C01%7Cm.kuhn%40enbw.com%7C8c9fa741ac434b4b52de08daf8bdc5cc%7Cee920d5446e44e1eaa996d010a689325%7C0%7C0%7C638095791198056053%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wKqYJurU9TF6nRbixcPfm0it2lVYX7BbX6qFmcTxgXs%3D&reserved=0>

Let me know if you have trouble figuring it out, I'll try to assist.

**Comment by angularsen** [comment]
Thanks! #1186 is merged
