### ISSUE TITLE
Add hardness conversion

### ISSUE THREAD

**Issue by LHTXQ** [angularsen/UnitsNet#1172]
**Is your feature request related to a problem? Please describe.**
It is hoped that the function of hardness conversion of metal materials can be added. The conversion method can be found in ISO 18265.
(Perhaps this feature is a little outside the scope of "unit conversion" and cumbersome to implement.)
![image](https://user-images.githubusercontent.com/38943319/209425815-d6abf556-88c5-48e0-ae61-01315a96743d.png)

**Describe the solution you'd like**
The GUI for this feature should look like this (for library design reference): 
![image](https://user-images.githubusercontent.com/38943319/209425750-76d79d47-ebf4-4854-ad52-54deff5e05a5.png)

**Comment by angularsen** [comment]
This seems more complicated than just unit conversions.
It is probably better solved in the application, outside Units.NET library.
