### ISSUE TITLE
Split into subpackages

### ISSUE THREAD

**Issue by hughesjs** [angularsen/UnitsNet#1180]
**Is your feature request related to a problem? Please describe.**
It's unfortunate to have to ship all units if my application is only using a small subsection.
For instance, if I'm making a package concerned with weights, mass, and distance, there's not much point including `Candela` in my application.

**Describe the solution you'd like**
Split the solution into domain packages along the lines of `UnitsNet.Newtonian`, `UnitsNet.Electricity` etc.

**Describe alternatives you've considered**
A package for each unit rather than each domain, but that could get cumbersome

**Comment by angularsen** [comment]
Hi, yes I have been doing some investigation into this.
Work in progress branch here: #1181

Please review the design proposal and the problems discovered so far, if you have any ideas or comments about this approach. If you want to help move that project forward, that would also be helpful. I don't have much time to spend on the project so it moves slowly.
