### ISSUE TITLE
Precision issues even when ignoring binary issues

### ISSUE THREAD

**Issue by MisinformedDNA** [angularsen/UnitsNet#1188]
**Describe the bug**
Conversion from pounds to ounces is not precise enough.

**To Reproduce**
Steps to reproduce the behavior (just an example):
1. Add nuget UnitsNet 5.0.0-rc013
2. Add this to a program and inspect mass. `var mass = Mass.FromPounds(1).Ounces;`

**Expected behavior**
`mass` is equal to 16

**Actual behavior**
`mass` is equal to 15.999999977510706

**Additional context**
The use case is manufacturing software that needs 8 digits of precision. And this isn't an issue with bits, but with the precision of the conversion factors.

The [legal conversion](https://en.wikipedia.org/wiki/Pound_(mass)) from pounds to kilograms is `0.45359237`, which is correct in the code. However, the conversion from kilograms to ounces should then be $x / 0.45359237 * 16$, which is equivalent to 

`35.273961949580412915675808215204` with the code having a much less precise 
`35.2739619`

To easily solve this, I propose replacing this line:

```
(MassUnit.Kilogram, MassUnit.Ounce) => new Mass(_value * 35.2739619, MassUnit.Ounce),
```

with this

```
(MassUnit.Kilogram, MassUnit.Ounce) => new Mass(_value / 0.45359237 * 16, MassUnit.Ounce),
```

**Comment by MadsKirkFoged** [comment]
If you are looking for better conversion precision in general and you are okay with losing a bit of computation speed you could look into our UnitsNet clone: [EngineeringUnits](https://github.com/MadsKirkFoged/EngineeringUnits)
