### ISSUE TITLE
Power is using the decimal type

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#1194]
I'm upgrading to 5.1.0 in my projects and noticed that Power is using the decimal type.

I don't think this is a bug so much as questioning if this is expected? It has been this way since [2014](https://github.com/angularsen/UnitsNet/pull/44), I only just noticed since the value property in v5 now returns the underlying type rather than always double.

I would expect this type to be consistent with much of the other types: double.

Per the PR:

> I was thinking about this previously and I think decimal might be a better backing datatype because it can exactly represent powers of 10 because it's a decimal floating point type (double is binary floating point). It would make sense to use it since we're mainly concerned with SI units which are powers of 10, however it's a major breaking change and decimal is less efficient for calculations...

I don't think this is applicable anymore given the test checking within a tolerance. Let me make a PR and we can discuss,.

**Comment by angularsen** [comment]
I'm all for it, double down on double.
BitRate, Information and Power are the types using decimal now. 3 out of 100+. It doesn't make any sense.

The only concern is breaking changes that requires another major version bump and that integer quantities like `Information` may start getting rounding errors it did not previously have. 

Even so, a consistent type is better in the end and I would rather look into some generics support to support decimal and other number types if anyone cares enough about it to champion it.

**Comment by Muximize** [comment]
+1, the breaking changes with Power are preventing us from upgrading to v5 without lots of casting. I'd like to applaud @tmilnthorp for his PR efforts.

**Comment by tmilnthorp** [comment]
> I'd like to applaud @tmilnthorp for his PR efforts.

Thanks!

**Comment by angularsen** [comment]
@Muximize #1205 was resolved by #1207 , can you take it for a spin if this unblocks you?

Changing Power to double will be a breaking change, and you'll have to wait for v6 prerelease nugets for that. No ETA yet. Tracked by #1195 .

**Comment by Muximize** [comment]
Alas, we're using the conversion properties in quite a few places so we have to wait for v6.

I should have paid attention and protest against this change landing in v5 in the first place 😅

**Comment by angularsen** [comment]
Fixed in #1195 for v6
