### ISSUE TITLE
Typo in public BaseUnits

### ISSUE THREAD

**Issue by markeglin** [angularsen/UnitsNet#1198]
I happen to notice what appears to be a typo in the BaseUnits constructor when setting the "IsFullyDefined" property.
Hope this helps out - this is a great package !
Mark 

        public BaseUnits(
            LengthUnit? length = null,
            MassUnit? mass = null,
            DurationUnit? time = null,
            ElectricCurrentUnit? current = null,
            TemperatureUnit? temperature = null,
            AmountOfSubstanceUnit? amount = null,
            LuminousIntensityUnit? luminousIntensity = null)
        {
            Length = length;
            Mass = mass;
            Time = time;
            Current = current;
            Temperature = temperature;
            Amount = amount;
            LuminousIntensity = luminousIntensity;

            IsFullyDefined = Length is not null &&
                             Mass is not null &   <--------- should be &&
                             Time is not null &&
                             Current is not null &&
                             Temperature is not null &&
                             Amount is not null &&
                             LuminousIntensity is not null;

**Comment by angularsen** [comment]
Wow, great find. Are you reading the code base line by line? 😅
Incidentally, binary `&` and logical `&&` do produce the same result.

Fixed in:
ea064e0 - BaseUnits: Fix & instead of &&
