### ISSUE TITLE
Wiki still states that v5 is in beta

### ISSUE THREAD

**Issue by bitbonk** [angularsen/UnitsNet#1203]
The [Wiki ](https://github.com/angularsen/UnitsNet/wiki/Upgrading-from-4.x-to-5.x)states that v5 is still in beta

> ⚠️ v5 is still in alpha to finalize some last few minor breaking changes, but it is functional, stable and ready to use.

But this does not reflect the current semantic versions of UnitNet, there have been multiple [non-beta 5 releases](https://www.nuget.org/packages/UnitsNet#versions-body-tab) already.

I would suggest thar you either change the wiki or the semantic version.

**Comment by angularsen** [comment]
Removed the line.
