### ISSUE TITLE
System.Globalization.CultureNotFoundException UnitsNet.ToString() on system that Culture information is not available

### ISSUE THREAD

**Issue by PRIMETSS** [angularsen/UnitsNet#1238]
When .ToString() is called via DotNet #7 App on a UnitsNet Type on a system that either does not have Culture support with the 
`export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT='1'` environment variable set (required to run dotnet on PI) in Culture Invariant mode.

`Unhandled exception. System.TypeInitializationException: The type initializer for 'UnitsNet.UnitAbbreviationsCache' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at UnitsNet.UnitAbbreviationsCache..cctor()
   --- End of inner exception stack trace ---
   at UnitsNet.UnitAbbreviationsCache.get_Default()
   at UnitsNet.UnitFormatter.GetFormatArgs[TUnitType](TUnitType unit, Double value, IFormatProvider culture, IEnumerable`1 args)
   at UnitsNet.QuantityFormatter.ToStringWithSignificantDigitsAfterRadix[TUnitType](IQuantity`1 quantity, IFormatProvider formatProvider, Int32 number)
   at UnitsNet.QuantityFormatter.Format[TUnitType](IQuantity`1 quantity, String format, IFormatProvider formatProvider)
   at UnitsNet.Temperature.ToString(String format, IFormatProvider provider)
   at UnitsNet.Temperature.ToString(String format)
   at UnitsNet.Temperature.ToString()`

On OpenWRT SNAPShot (r22514) (Busybox Linux-musl  ARM64) running on a Raspberry PI CM4 install latest DotNet SDK Version: 7.0.202 an ' System.Globalization.CultureNotFoundException' is thrown. 

**Expected behavior**

`string temp = sensorAht20.GetTemperature().ToString("F2")`

Expected to return a 2 decimal places Temperature, eg '22.2' on system where Culture is not available.

![image](https://user-images.githubusercontent.com/11331370/231058859-08cba0c5-3c02-4148-bee7-3798fa57dc84.png)

[https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization)

**Comment by tmilnthorp** [comment]
Thanks for the info. This is an oversight in our fallback mechanism.

@angularsen I wonder if #1210 would be the best fix here.

**Comment by angularsen** [comment]
@tmilnthorp Yes I think we can solve it as part of that feature, maybe make a note to test this scenario.

**Comment by aradalvand** [comment]
Same issue here.
Any time frame as to when #1210 is likely to be merged?

**Comment by pgrawehr** [comment]
@PRIMETSS Just curious: Why do you need that in the first place? Culture support works just fine on the Raspberry Pi (at least for me), so this setting seems unnecessary. Or is it the container you're using?

**Comment by PRIMETSS** [comment]
To get DotNet 7/8 (Core) runtime to currently function on OpenWRT Busybox musl-linux using package `icu71` you need to set `export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT='1'` 

This package has now updated to icu72 recently, and have not checked if this removed that 'workaround' but from memory I think I still had same issue after.

![image](https://github.com/angularsen/UnitsNet/assets/11331370/559fb4e3-1f3f-4759-a60a-0ee89b0c5c54)

**Comment by angularsen** [comment]
Will try to make some progress this weekend.

**Comment by angularsen** [comment]
A possible fix is merged in #1266 , it would be good if you have the chance to build it locally and try it out. I have a few more fixes before I'm ready to publish a new nuget.

**Comment by angularsen** [comment]
#1266 is out in [Release UnitsNet/5.22.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.22.0)
