### ISSUE TITLE
How to add a unit to an existing quantity?

### ISSUE THREAD

**Issue by jasekiw** [angularsen/UnitsNet#1246]
I am trying to add a custom unit for our project that should go under ElectricResistivity. It is MeterPerSiemens (m/S) and is a 1 to 1 conversion to OhmMeter.

I tried following the documentation below however it only gives examples on how to add a custom quantity with units. I want to add a unit to an existing quantity (ElectricResistivity), not a new one.
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units

How would I go about adding a unit to an existing quantity? Once that is determined, I think the documentation should be updated to include the instructions.

**Comment by angularsen** [comment]
Hi, I've added some more info to the top of the wiki page. In particular, why adding units to existing quantities is currently not feasible.

Please take a look and let me know if it helps or how it could improve further:
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units

**Comment by jasekiw** [comment]
@angularsen Thank you for the section in the documentation. It makes it much more clear. Seeing as it's not possible to add a unit, would this unit be a candidate to officially add it to the library? I don't want to go through the effort of creating a PR if it is going to get denied. Thanks!

**Comment by angularsen** [comment]
Yes, that sounds reasonable to add.
Please go ahead with the pull request, just follow the instructions in the wiki and ping me if you have any questions. 👍
