### ISSUE TITLE
Pixels?

### ISSUE THREAD

**Issue by aradalvand** [angularsen/UnitsNet#1248]
Hey, sorry if this is a dumb question, but doesn't UnitsNet have units for pixels (like for raster images) and frame rates (in videos)? I couldn't find anything relevant.

**Comment by aradalvand** [comment]
Sorry for posting this as a bug report, it's not, it's just a question.

**Comment by angularsen** [comment]
Hi, no there are no such units. The closest would be Frequency for frame rate.

Generally speaking, we try to add only the most common quantities and units. In particular, quantities with multiple units to convert between. 

Some more info about criteria for adding new units here: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#great--but-before-you-start-

My hunch is that these units won't add enough value to include, if they only have a single unit and can't convert to other quantities.

**Comment by aradalvand** [comment]
Understandable. Thank you.
