### ISSUE TITLE
VolumeFlowUnit: HectoliterPerTime as volume flow missing.

### ISSUE THREAD

**Issue by andrerodi** [angularsen/UnitsNet#1253]
In the (beer) brewing sector the unit of hectoliter is used constantly. In the _VolumeUnit_ enum that unit is implemented, but is missing in the _VolumeFlowUnit_ enum.

It would be great if this unit could be implemented, since all machines we build use this as the base unit for volume flow.

If no one has the time to implement this feature, I would consider implementing it myself and therefore create a pull request once I implemented it. I'm just a total noob to this, since I have never contributed to any repo other then my own.

![image](https://github.com/angularsen/UnitsNet/assets/89607119/cccffbae-fb19-444b-ac49-73cc4a09c6ab)

**Comment by angularsen** [comment]
Hi, that should be useful to add. Please go ahead with the pull request. 

Steps outlined here, but you should be looking at adding a "prefix" to the existing unit. Just add "Hecto" to the prefix array in JSON, see how it's done for other units.

https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

Let me know if you have any questions on the changes to make or for general things like forking and pull requests. I'm happy to help!
