### ISSUE TITLE
ReciprocalVolume?

### ISSUE THREAD

**Issue by chucker** [angularsen/UnitsNet#1260]
**Is your feature request related to a problem? Please describe.**
I have a particulate matter sensor that gives measured values in µg/m^3 (so I can use `Density`), but then also measured _counts_ in #/m^3.

Wikipedia seems to call this https://en.wikipedia.org/wiki/Number_density.

I've also found the `ReciprocalArea` type, which is pretty close, except I need `ReciprocalVolume`.

**Describe the solution you'd like**
`NumberDensity` and/or `ReciprocalVolume` types would be nice, with factory methods such as `FromInverseCubicMeter`.

**Comment by chucker** [comment]
(`NumberConcentration` might also be the correct name here. I'm not sure.)

**Comment by ricardoboss** [comment]
See also: https://en.wikipedia.org/wiki/Concentration#Number_concentration

**Comment by angularsen** [comment]
This feels a tiny bit fringe/exotic, but I'll accept it. 

From googling a bit, it seems number density is maybe the more commonly used term.
I have no hard preference, but reciprocal volume seems the least common of them.

I'd suggest NumberDensity, alternatively NumberConcentration.
If you want to go ahead with a pull request, steps are outlined here: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'm happy to assist.

**Comment by chucker** [comment]
@ricardoboss made a PR (#1409); reopen
