### ISSUE TITLE
Mass.GetUnitInfosFor returns Empty enumeration for BaseUnits

### ISSUE THREAD

**Issue by holmes-mike** [angularsen/UnitsNet#1272]
**Describe the bug**
```csharp
var massUnit = Mass.Info.GetUnitInfosFor(UnitSystem.SI.BaseUnits);
```
returns empty enumeration

**Expected behavior**
returns MassUnit.Kilogram

**Comment by angularsen** [comment]
Would be fixed by https://github.com/angularsen/UnitsNet/pull/1233

However, that PR was recently closed. I asked the author on whether they wanted to complete it.
