### ISSUE TITLE
Add Kilofoot/Kilofeet/kft to the Length conversions

### ISSUE THREAD

**Issue by tjrtfarnham** [angularsen/UnitsNet#1273]
It was not obvious from the documentation how I could modify the Length.json to add Kilofoot conversions.  Is this an addition that would be accepted.  It seems trivial for @angularsen to implement this, but I would be happy to generate a pull request if I am given guidance on how I go about adding it.  Thanks for your help.

**Comment by angularsen** [comment]
Hi, late reply, was on vacation.

There are detailed steps here on adding units: 
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

Let me know if anything is still unclear!

**Comment by angularsen** [comment]
For Kilofoot in particular, add a prefix "Kilo" to the unit Foot. See how other units add prefixes, such as Meter adding Centi/Milli etc.

**Comment by angularsen** [comment]
Solved by #1286  in 5.23.0
