### ISSUE TITLE
[AmountOfSubstance] Add picomoles and femtomoles

### ISSUE THREAD

**Issue by eugene-zhary** [angularsen/UnitsNet#1288]
I use your awesome library for some accurate laboratory measurements. Previously I was making a very similar [request for picograms and femtograms](https://github.com/angularsen/UnitsNet/pull/1240). Thank you so much for your approval! Now I'm opening this issue and kindly asking about adding the same feature for moles. I will be happy to extend the library with such units

| Name | SI symbol | Value |
| - | - | - |
| picomole | pmol | 10⁻¹² |
| femtomole | fmol | 10⁻¹⁵ |

Have a nice weekend, thank you!

**Comment by angularsen** [comment]
Hi and thank you.

Adding prefixes is almost always OK, so you can just go ahead with pull requests for those.

I'm not 100% sure Femto will pass all the round-trip conversion tests, but we do have units with that prefix already so it probably will be OK.
