### ISSUE TITLE
Deserialization of an empty unit cause a stackoverflow

### ISSUE THREAD

**Issue by shaeussler** [angularsen/UnitsNet#1292]
Deserialization of an empty unit cause a stackoverflow.

```
            var jsonSerializerSettings = new JsonSerializerSettings()
            {
                Converters = new List<JsonConverter>() { new UnitsNetIQuantityJsonConverter(), new UnitsNetIComparableJsonConverter() },
            };

            JsonConvert.DeserializeObject<Length>("{}", jsonSerializerSettings);
```

**To Reproduce**
Steps to reproduce the behavior (just an example):
1. Add nuget UnitsNet 5.26.0 and UnitsNet.Serialization.JsonNet 5.5.0 to a dotnet 7.0 project.
2. Build using Visual Studio 2022 
3. Run the code above

**Expected behavior**
No stackoverflow

**Comment by angularsen** [comment]
Thanks for reporting, do you by chance have time to debug and attempt to fix it with a pull request?
I'm happy to assist, but my time is very limited these days.

**Comment by shaeussler** [comment]
See PR: https://github.com/angularsen/UnitsNet/pull/1293
