### ISSUE TITLE
Readme still uses QuatityType and such, but those have been removed in v5

### ISSUE THREAD

**Issue by lorenzbiotex** [angularsen/UnitsNet#1297]
**Describe the bug**
Following along with the readme trying to make use of the lib leads to problems because you get errors about Types not existing on Quatity. Apparently in v5 release this was removed, but the readme was not updated to explain the new usage of the lib.

**To Reproduce**
Steps to reproduce the behavior (just an example):
1. look at the github landing page for the repo

**Expected behavior**
instructions on how to use the lib consistent with the current version 5, instead of the version 4 of the library

**Comment by angularsen** [comment]
Thanks for reporting, I pushed some improvements to the readme just now.
#1299 

Let me know if that helps or if there is anything I missed.
