### ISSUE TITLE
Unit testing overhaul - new algorithm and tolerance proposal

### ISSUE THREAD

**Issue by MH-ZShearer** [angularsen/UnitsNet#1309]
**Is your feature request related to a problem? Please describe.**
I originally thought the existing method of unit testing round trips of conversion rates via percent error comparison were inefficient. However, the more time I have spent thinking about this issue and working on an alternative, the less I know what the actual issue is.

**Describe the solution you'd like**
Personally, I like the significant figures approach over the percent error approach. I'm struggling to justify one approach over the other though.

**Describe alternatives you've considered**
Minimally, increase the default accepted percent error from `1e-5`. Ideally, to `1e-9`.

**Additional context**
I was initially convinced that the percent error comparison was inadequate, however I'm no longer convinced. However, I don't want my efforts to look at an alternative to go to waste so I'm presenting my thoughts and potential solution for your review and feedback.

<hr />

_Edit: Two "advantages" I thought about with significant figure comparison is that the output can be displayed "lined up" to quickly identify the difference and the arbitrary percent error that is selected would be replaced by an integer._

<hr />

The below algorithm needs to be provided the expected and actual values as well as the number of significant digits to compare. The expected value's log<sub>10</sub> is used to determine what the allowed difference can be. The difference ends up being calculated as `(power + 1) / 2`, so the `maxDelta` effectively allows `actual` to be `+/- 0.5`, relative to the significant digit's position.

The only use case that I've been able to identify as being "better" than percent error comparison is when `expected` is `0.0`. With the percent error comparison, there is no tolerance, and the actual value **must** be `0.0`. With the significant figures approach, _n_ significant figures translate to **expected +/- 10<sup>-n</sup> + 0.5**.
<sub>Note: After further review, this is only because a special use case was added to handle zero a certain way, as if the ones place was a significant digit.</sub>

Something to keep in mind, the expected precision for a round trip calculation _should_ only be concerned with float error, assuming the to/from equations are inverse operations.  However, the operations are not always inverse operations. This translates into a tolerance that _should_ be stricter but must still have some leniency. Additionally, higher round trip precision should be encouraged as all calculations are relative to base unit conversions.

```cs
private static bool IsAccurateToSignificantFigures(double expected, double actual, int significantFigures)
{
    var power = 0.0 - significantFigures + 1;

    if (expected != 0)
        power = Math.Floor(Math.Log10(Math.Abs(expected))) - significantFigures + 1;

    var maxDelta = Math.Pow(10, power) / 2;
    var delta = Math.Abs(expected - actual);

    return delta < maxDelta;
}
```
```cs
> IsAccurateToSignificantFigures(1004, 1005, 3);
// true
> IsAccurateToSignificantFigures(1001, 1009, 3);
// false
> IsAccurateToSignificantFigures(1, -1, 1);
// false
> IsAccurateToSignificantFigures(0, 0.0001, 3)
// true
> IsAccurateToSignificantFigures(9.995, 9.99499999999, 3);
// true
```
I was concerned with this new method being significantly slower due to additional math being performed so I ran some benchmarks. Even though an increase in time isn't _as_ relevant for the testing library, there are a lot of tests to run, and this change shouldn't be impactful to the overall testing time. It appears this new method is roughly 3.5x slower than the current method. I would deem this to be acceptable, but that is not my call.

<sub>_~~Note: Upon running multiple benchmarks, the results varied significantly.~~ See below for details regarding performance benchmarking._</sub>

```
|    Method |      Mean |     Error |    StdDev |    Median | Rank | Allocated |
|---------- |----------:|----------:|----------:|----------:|-----:|----------:|
| OldMethod | 0.0020 ns | 0.0027 ns | 0.0022 ns | 0.0012 ns |    1 |         - |
| NewMethod | 0.0068 ns | 0.0059 ns | 0.0052 ns | 0.0055 ns |    2 |         - |
```

<hr />

_Edit: Upon further investigation, it turns out I overlooked the following warnings._

```
ZeroMeasurement
  BenchmarkDictionaryLookup.NewMethod: Default -> The method duration is indistinguishable from the empty method duration
  BenchmarkDictionaryLookup.OldMethod: Default -> The method duration is indistinguishable from the empty method duration
```

_Effectively, this means the times are so small, Benchmark.NET is unable to provide accurate results. So I ran it again, iterating a million times and removed the `Debug.Assert` call (I don't benchmark often), and got the below results. They're effectively equivalent._

```
|    Method |     Mean |     Error |    StdDev | Rank | Allocated |
|---------- |---------:|----------:|----------:|-----:|----------:|
| NewMethod | 1.267 ms | 0.0052 ms | 0.0046 ms |    1 |       1 B |
| OldMethod | 1.274 ms | 0.0074 ms | 0.0069 ms |    1 |       1 B |
```

**Comment by MH-ZShearer** [comment]
As a follow up regarding other unit testing "issues", I would like to further address the library's default error tolerance as well as how unit test comparison values are represented. Inaccurate `expected` values can have a negative impact on the unit testing as a whole. Take, for example, the `PoundsForceInOneNewton` value's current value to the precise value (`1 / 4.4482216152605`):

```
Current: 0.22481
Precise: 0.2248089430997104829100394134 (approx.)
Error:   0.00047% (5 sig. digits)
```

This error compounds with the error tolerance of the library (default 0.001%). That measurement alone would move the library to almost 0.0015% error, 50% more than currently stated. On top of this issue lies an inherent issue with the unit testing. Unit conversion regularly uses unsavory conversion rates, some even resulting in repeating decimals. If you were to give me two similar numbers above and ask me which one was more precise, I would select the "Current" one because precision is sometimes perceived as conciseness.

In #1308, the unit test values are represented as equations to prevent the above concise/precise issue from happening for maintainers. I understand it is easier to copy/paste the values into Wolfram Alpha, or similar, but if a unit test is under scrutiny, I believe it should require more time to evaluate it.

My proposal around all of this, even if the comparison method isn't changed from percent error (not sure it should be), is that library wide precision needs to be increased and the approach for "acceptable" unit test values should be re-evaluated. Take, for example, the #1308 PR that modifies the unit conversion rates towards the real-world values. Based on some quick tests, round-trip conversions pass a `0.000000001%` (`1e-11`) error tolerance without issue. I believe this is what should be strived for as it incurs no performance degradation and provides additional confidence to the users of Units.NET that the numbers are precise.

But to talk about the elephant in the room, many of the conversion rates are not precise and are good enough for most use cases. In those cases, I believe the tolerance of those units should be required to be overridden (change `1e-9` to `1e-5`) manually. I understand this may take some (read: a lot of) work, but if accepted, I will make the necessary changes. I would like more of the user base to provide feedback for this as I understand our position in our industry, and subsequent requirements, is higher than most users.

Ultimately, you're the maintainers and I will respect your final decision on this but wanted to provide my feedback beforehand. Worst case scenario, our application can create its own, similar unit testing that requires tighter tolerances.

**Comment by angularsen** [comment]
A lot of good information here, but there is a lot of text to digest and some ideas in several directions.

Can you help me understand better your proposal, by summarizing your exact proposed changes and any open questions to discuss, in a bullet list?

If I read it right, there are two ideas or discussion that each require a summary of changes/discussions:
1. Error as significant digits vs relative/percentage (you mention you are not sure the change is worth it)
2. Tighter error tolerance by default, f.ex. 1e-11 instead of 1e-5, requiring manual overrides for some units
3. Also, in https://github.com/angularsen/UnitsNet/pull/1308#discussion_r1305724451 you mention you do not agree with fixed constants in test assertions and calculations in JSON conversion functions, this could be a third discussion

**Comment by angularsen** [comment]
I will try to find time to get back to this sometime soon.
