### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by wldevries** [angularsen/UnitsNet#1310]
**Describe the bug**
https://github.com/angularsen/UnitsNet#example-wpf-app-using-ivalueconverter-to-parse-input

The link to the WPF sample using IValueConverter does not link to the correct source code.

It links to https://github.com/angularsen/UnitsNet/tree/master/Samples/WpfMVVMSample

It should be https://github.com/angularsen/UnitsNet/tree/master/Samples/MvvmSample.Wpf

**Comment by angularsen** [comment]
Thanks! Fixed the readme now.
