### ISSUE TITLE
ElectricResistanceUnit do work no more

### ISSUE THREAD

**Issue by BernhardJosef** [angularsen/UnitsNet#1315]
**Describe the bug**
The Unit 'Ohm' is now unknown.

**To Reproduce**
Enum unitOhm = UnitParser.Default.Parse("Ohm", typeof(ElectricResistanceUnit));

**Expected behavior**
Support of ElectricResistanceUnit from mOhm to TOhm.

**Screenshots**
UnitsNet.UnitNotFoundException: "Unit not found with abbreviation [Ohm] for unit type [UnitsNet.Units.ElectricResistanceUnit].".

**Additional context**

**Comment by angularsen** [comment]
Did this ever work? In what version?

The abbreviation is defined as `Ω` in JSON.
https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/ElectricResistance.json#L11-L22

```cs
// Throws
// UnitParser.Default.Parse("Ohm", typeof(ElectricResistanceUnit))

// OK
UnitParser.Default.Parse("Ω", typeof(ElectricResistanceUnit))
```
