### ISSUE TITLE
Unit Arithmetic 

### ISSUE THREAD

**Issue by rjs5327** [angularsen/UnitsNet#1322]
**Is your feature request related to a problem? Please describe.**
Allow for there to be math between units to make combined units
Torque = Force * Length

Basically adding in the unknown unit classes from the https://github.com/MadsKirkFoged/EngineeringUnits library and adding this function to Units Test

**Comment by rjs5327** [comment]
Also Please Add to the Documentation a example of how to do the math

        public static MassMomentOfInertia SolidCylinderInertia(Mass mass, Length radius)
        {
            return MassMomentOfInertia.FromKilogramSquareMillimeters( mass.Kilograms * radius.Millimeters * radius.Millimeters / 2.0);
        }

**Comment by rjs5327** [comment]
Also some documentation on Why this is not allowed 

        public static Torque TorqueAcc(MassMomentOfInertia InertiaTotal, RotationalAcceleration Rad_Sec2, Torque FrictionTorque)
        {
// Does not Work - Throws a error 
            Torque torque = InertiaTotal* Rad_Sec2;
            return  torque + FrictionTorque;
        }

But this works and is allowed

        public static MassMomentOfInertia BallScrewInertia(Length Diameter, Length Length, Density density)
        {
            Volume screwVolume =  Volume.FromCubicMillimeters(Math.PI * (Diameter.Millimeters / 2)* (Diameter.Millimeters / 2) * Length.Millimeters);
            Mass mass = density*screwVolume;
            return SolidCylinderInertia(mass, Diameter / 2);
        }

Both ways there is a * used but one is ok and the other is not allowed .  I see it as best practice is to not rely on it working but i dont follow why it works and does not work

**Comment by angularsen** [comment]
Sorry for late reply. This question is not clear to me. 

All multiplication and division operator overloads are manually added, so we can add more if something is missing.

For example, see how `Length.extra.cs` defines arithmetic between different quantities relating to itself:

https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/Quantities/Length.extra.cs#L126-L184
