### ISSUE TITLE
Wrong Plural for MeterPerMinute Speed Units Names

### ISSUE THREAD

**Issue by Markussp256** [angularsen/UnitsNet#1330]
**Describe the bug**
For Speed we have many Units of the form [LengthUnit]Per[TimeUnit]. For instance MeterPerSecond. The plural of it we get by taking the plural of the Lengthunit and the singular of the TimeUnit, for instance MetersPerSecond. However for Units with Meter and Minute also the TimeUnit is currently in Plural form. This makes the method names somehow inconsistent.

Speed has for example the static method FromMetersPerMinutes and FromInchesPerMinute. This also affects all corresponding Units with a prefix, e.g. NanoMetersPerMinutes.

**Expected behavior**
I would appreciate new methods without the s. The current methods with s should still be usable for a while to not break any code but with a warning that it will be deprecated.

**Comment by angularsen** [comment]
Thanks for reporting, could you please post a list of the units with wrong plural form on #1200 ?
