### ISSUE TITLE
Include yard-based density units

### ISSUE THREAD

**Issue by aharres** [angularsen/UnitsNet#1332]
It would be nice to have yard-based density units like `DensityUnit.PoundPerCubicYard`.

**Comment by angularsen** [comment]
Sounds reasonable to add. If you are willing to attempt a pull request, detailed steps are here:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

**Comment by aharres** [comment]
I created a pull request here: [https://github.com/angularsen/UnitsNet/pull/1334](url)

**Comment by angularsen** [comment]
Merged #1334

**Comment by aharres** [comment]
Awesome! Thanks.
