### ISSUE TITLE
Automatically retrieve Type based on Unit

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [angularsen/UnitsNet#1336]
**Is your feature request related to a problem? Please describe.**

I'm working on UI elements (sliders, steppers, etc.), where users can define the unit type of each control at runtime. 

**Describe the solution you'd like**

I'd like to automatically retrieve the type (`Length`, `Angle`, `Scalar`, etc.) based on the chosen unit `LengthUnit.Meter`, `AngleUnit.Degree`, etc. 
I need this information to parse quantities from input strings:

```c#
            if (Quantity.TryParse(_type, "0.31 km", out IQuantity quantity))
                _displayText.Text = quantity.ToUnit(_unit).ToString();
```

**Describe alternatives you've considered**

My current workaround is based on manipulating strings:
```c#
            var typeName = _unit.GetType().Name;
            typeName = typeName.Remove(typeName.Length - "Unit".Length);
            _type = Type.GetType($"UnitsNet.{typeName}, UnitsNet");
```

**Comment by angularsen** [comment]
Hi, it's not super straight forward to discover, but you can do it like this:

```cs
Enum unit = LengthUnit.Centimeter;
Type quantityType = Quantity.From(1, unit).GetType();


// 10 cm
Quantity.Parse(quantityType, "100 mm").ToUnit(unit).Dump();
```

**Comment by angularsen** [comment]
Something we could add that maybe would make this a bit easier:
```cs
UnitInfo unitInfo = Quantity.GetUnitInfo(LengthUnit.Centimeter);

// If we had a property on QuantityInfo to expose the quantity type
Type quantityType1 = unitInfo.QuantityInfo.Type;
Type quantityType2 = Quantity.ByName[unitInfo.QuantityName].Type;
```

**Comment by mariuszhermansdorfer** [comment]
Thanks for a prompt response @angularsen!

The workaround you suggested works very well!

**Comment by angularsen** [comment]
Glad to hear it!
