### ISSUE TITLE
New Unit - Grade (Slope)

### ISSUE THREAD

**Issue by mariuszhermansdorfer** [angularsen/UnitsNet#1337]
**Is your feature request related to a problem? Please describe.**
In architecture and landscape architecture, there are multiple ways of representing a [grade](https://en.wikipedia.org/wiki/Grade_%28slope%29):
![image](https://github.com/angularsen/UnitsNet/assets/49192999/bf02cbd4-d770-4f21-97f5-c363c257af68)

It can be defined as:
- an angle (26.6°)
- a percentage value (50%)
- a per mille value (500‰)
- a ratio written as a fraction (1/2)

![image](https://github.com/angularsen/UnitsNet/assets/49192999/49067df0-26e0-406b-9dd4-46f796b39da7)

**Describe the solution you'd like**
I'd like `UnitsNet` to group all the above representations within one `GradeUnit` to allow for seamless conversions. Currently, using the `RatioUnit`, it is possible to convert from a percent value to per mille, but angle is missing. Also, it'd be great to have support for fractions. similarly to how the `LengthUnit` supports feet and inches.

**Comment by angularsen** [comment]
I think this sounds useful and has a wide range of applications.
Would you be interested in attempting a pull request?

Detailed steps here:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'm happy to assist.

**Comment by mariuszhermansdorfer** [comment]
Thanks @angularsen!

The description for a PR looks very manageable, I’ll gladly give it a shot. I could definitely use some help with the fraction part, though. 

Let me cook up a first sketch and submit it as a draft PR so that I can ask for more specific feedback.

**Comment by mariuszhermansdorfer** [comment]
@angularsen,

I have a draft PR which passes all the tests except for this one:
![image](https://github.com/angularsen/UnitsNet/assets/49192999/2a5dff00-2c3e-4439-b952-d787dbad76d7)
Any ideas why this can be the case?

Also, I defined `Percent` as the main unit, do you agree with this approach, or would you prefer using `Fraction` as default?

```json
{
  "Name": "Grade",
  "BaseUnit": "Percent",
  "XmlDocSummary": "The grade, or slope, of a surface is the tangent of its angle compared to the horizontal, indicating its steepness. It's often expressed as a ratio or fraction of vertical rise to horizontal run, where a larger value means a steeper angle.",
  "XmlDocRemarks": "https://en.wikipedia.org/wiki/Grade_%28slope%29",
  "BaseDimensions": {
    "L": 1
  },
  "Units": [
    {
      "SingularName": "Percent",
      "PluralName": "Percent",
      "FromUnitToBaseFunc": "{x}",
      "FromBaseToUnitFunc": "{x}",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "%" ]
        }
      ]
    },
    {
      "SingularName": "Permille",
      "PluralName": "Permille",
      "FromUnitToBaseFunc": "{x} / 1e1",
      "FromBaseToUnitFunc": "{x} * 1e1",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "‰" ]
        }
      ]
    },
    {
      "SingularName": "Degree",
      "PluralName": "Degrees",
      "FromUnitToBaseFunc": "Math.Tan({x}) * 1e2",
      "FromBaseToUnitFunc": "Math.Atan({x} / 1e2) * (180 / Math.PI)",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "°", "deg" ]
        },
        {
          "Culture": "ru-RU",
          "Abbreviations": [ "°" ]
        }
      ]
    },
    {
      "SingularName": "Fraction",
      "PluralName": "Fractions",
      "FromUnitToBaseFunc": "{x} * 1e2",
      "FromBaseToUnitFunc": "{x} / 1e2",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "" ]
        }
      ]
    }
  ]
}

```

**Comment by tm-ren** [comment]
Sorry to interfere.
Is this not simply an extension to the Ratio quantity with more units?
Perhaps more operators are required so that it is easier to obtain?
For example, dividing a length by another length is simply a ratio whose value could be obtained as a percentage as per your first image.
Similarly, any quantity divided by another of the same type is a ratio. Meaning, any quantity multiplied by a ratio is a quantity of the same type.

I personally think its more useful to extend the usage of an existing generic quantity rather than introducing a different quantity that represents the same thing.

**Comment by mariuszhermansdorfer** [comment]
I generally agree with your suggestion @tm-ren. But how would you treat the angle conversion to degrees? Does it make sense to have an angle as a generic Ratio unit?

**Comment by tm-ren** [comment]
An angle is a ratio technically. Consider:
`arcLength = radius * arcAngleInRadians`

Angles are special enough that it makes sense they are quantities in their own right.
How about implementing an easy way to initialise an Angle quantity from a Ratio quantity?

**Comment by mariuszhermansdorfer** [comment]
Makes sense. I need a simple way of converting between units too. As far as I know, one can only convert between units within the same Quantity, or can a cross-quantity conversion be easily implemented?

**Comment by angularsen** [comment]
Good point!
I thought at first there were new units here that justified having a
separate quantity, but I realize now that it may be better to reuse Ratio
and instead offer methods or extension methods to convert to Angle 👍

**Comment by mariuszhermansdorfer** [comment]
How do you suggest we proceed from now? I guess #1338 should be ignored then. Please let me know how I can help.

**Comment by angularsen** [comment]
Out sick today, will get back to you on this.

**Comment by angularsen** [comment]
@mariuszhermansdorfer I propose this:

1. Drop the PR and create a new one, sorry! 🙈 
2. Add `CustomCode/Quantities/Ratio.extra.cs` with method `public Angle ToSlopeAngle()`, the file does not already exist, but see how other `.extra.cs` files are done
3. Modify https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/Quantities/Angle.extra.cs to add method `public Ratio ToSlopeRatio()`


The units you requested should then already be covered by either `Angle` or `Ratio`, right?
- an angle (26.6°) `AngleUnit.Degree`
- a percentage value (50%) `RatioUnit.Percent`
- a per mille value (500‰) `RatioUnit.PartPerThousand`
- a ratio written as a fraction (1/2)  `RatioUnit.DecimalFraction` 

Creating string "1/2" is currently not supported, but maybe something we could add to Ratio if useful.
Some related discussion/work in #478, #1106.

**Comment by mariuszhermansdorfer** [comment]
Makes sense @angularsen. I'll act accordingly.
