### ISSUE TITLE
Add Molality units 

### ISSUE THREAD

**Issue by peterjamesnugent** [angularsen/UnitsNet#1340]
**Is your feature request related to a problem? Please describe.**
Add Molarity units (e.g. mol/kg).

**Describe the solution you'd like**
Add mol/kg and other derivative units (e.g. mol/g etc.)

**Describe alternatives you've considered**
mol/kg are not covered by the existing units (although there are some with molar units). 

**Additional context**
Happy to write the code and raise a PR if you agree it's worth adding.

https://en.wikipedia.org/wiki/Molality#Unit

Not to be confused with Molarity which is per unit volume: https://en.wikipedia.org/wiki/Molar_concentration

**Comment by angularsen** [comment]
I was convinced this was a typo until you clarified 😄 
This seems useful enough, would you be interested in attempting a pull request?

Detailed steps here and I'm happy to help if you have any questions.

https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit
