### ISSUE TITLE
Units of time on Mars

### ISSUE THREAD

**Issue by piotrstenke** [angularsen/UnitsNet#1346]
**Is your feature request related to a problem? Please describe.**
So, there's this friend rover of mine. Not so long ago, we used to hang out together almost every single day, but since it got delegated to a new mission on Mars, we started to loose touch. Every time I attempt to organize a Zoom call at a specific hour (say 2 o'clock), my friend doesn't show up. It turns out that time on Mars is different than that on Earth! Well, what do you know! Relocating to another planet really does move you apart!

Thus comes my suggestion to include Martian time units - the Sol (a.k.a. a Mars-day), Mars-year, Mars-minute and Mars-second. Including only the Sol is also plausible, as this is the most common unit of all mentioned here.

Though not an official unit, Sols are used by multiple space agencies, including both [NASA ](https://science.nasa.gov/mars/facts/) and [ESA](https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/Exploration/ExoMars).

**Describe the solution you'd like**
Include the Sol (or all mentioned units) as units of Duration.

**Describe alternatives you've considered**
End friendship with my friend rover. :(

**Additional context**
https://en.wikipedia.org/wiki/Timekeeping_on_Mars
https://en.wikipedia.org/wiki/Mars_sol

**Comment by angularsen** [comment]
I'm a little hesitant to add this one, sorry. To me, it seems this is not widely used enough?

As outlined in https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#great--but-before-you-start-, we simply have to say no sometimes to avoid bloating the library until we have a better solution to splitting up into multiple modules.

This need can easily be solved outside UnitsNet, with extension methods and similar.

**Comment by angularsen** [comment]
Okay on second thought, you are just asking about some extra units on `Duration`. That is fair. My mind went to new quantity for some reason. Let's add it!

**Comment by angularsen** [comment]
I'm fine with adding Sol day, but does month and year have an exact and well defined duration or do they have issues like leap years and varying month durations like on Earth?
