### ISSUE TITLE
Brackets missing when there are multiple denominators in units string

### ISSUE THREAD

**Issue by glyn-horsham** [angularsen/UnitsNet#1349]
According to the BODMAS mathematical convention, division comes before multiplication, therefore, the unit definitions where there are multiple denominators should be in brackets to avoid confusion between, say, W/m^2·C and (W/m^2)·C

For example, for heat transfer coefficients:
"Abbreviations": [ "kcal/h·m²·°C", "kcal/m²·h·°C", "kcal/hr·m²·°C", "kcal/m²·hr·°C" ]
should be
"Abbreviations": [ "kcal/(h·m²·°C)", "kcal/(m²·h·°C)", "kcal/(hr·m²·°C)", "kcal/(m²·hr·°C)" ]

This applies to multiple units in the code, from glancing though, I have found HeatTransferComponents and VolumetricHeatCapacity, but there maybe others.

**Comment by angularsen** [comment]
Thank you for reporting, would you be interested in attempting a pull request?

We can't remove abbreviations, it would be a breaking change on parsing and should be done as part of #1200 , but we can safely add the new variations and we can also change which abbreviation is first in the list of abbreviations, which is used by `ToString()` by default.

**Comment by angularsen** [comment]
Fixed by #1405
