### ISSUE TITLE
Accuracy Issue when converting from CubicMeters to CubicInches

### ISSUE THREAD

**Issue by cjab3r** [angularsen/UnitsNet#1357]
**Describe the bug**

When converting 10 cubicMeters into cubicInches, the result will be slightly different from the desired value as shown by the following unit test

<img width="502" alt="image" src="https://github.com/angularsen/UnitsNet/assets/156094439/3f52ae50-5f2c-45e2-93ff-a45546bdca10">

this should be the correct value (it is possible to confirm it as well from other sources)

![image](https://github.com/angularsen/UnitsNet/assets/156094439/0417cc35-9e29-4a26-8fec-b9041ffbda6c)

**To Reproduce**

<img width="358" alt="image" src="https://github.com/angularsen/UnitsNet/assets/156094439/209fa248-8497-4949-9579-b1ab13c1e621">

**Comment by angularsen** [comment]
Thank you, will look into it soon.

**Comment by angularsen** [comment]
Thanks for reporting, this was indeed a flaw in the constant used.
I did check that the related unit CubicFoot was already good.

Nuget with the fix should be out shortly.

[Release UnitsNet/5.43.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.43.0)
