### ISSUE TITLE
VolumeFlow conversion for UkGallonsPerHour is incorrect. 

### ISSUE THREAD

**Issue by mswpearson** [angularsen/UnitsNet#1389]
**Describe the bug**
The defined VolumeFlow conversion value for UkGallonsPerHour is incorrect by a significant amount.

**To Reproduce**
N/A

**Expected behavior**
The conversion value is configured as 791887.667, but after a google search and some manual testing I found the conversion value should be more like 791889.294.

This is a significant difference of around 2.5 units.

**Screenshots**
Google suggestion:
![image](https://github.com/angularsen/UnitsNet/assets/34303175/0a6c33e1-540c-40cc-826d-f76ef6dc2ca9)

Failing unit test:
![image](https://github.com/angularsen/UnitsNet/assets/34303175/79859723-d2df-4768-947f-bde84d0e5193)

Manual generation of the real conversion value:
![image](https://github.com/angularsen/UnitsNet/assets/34303175/86a62049-d911-42a1-9c4e-590348f91ee3)

Configured value in VolumeFlow.json
![image](https://github.com/angularsen/UnitsNet/assets/34303175/56b56ed3-13e4-43b8-9649-5292b4b2a2fc)

**Additional context**
I was writing unit tests to ensure the right conversions were taking place in my application. 

A test for the conversion between L/s to gal (imp.)/h was failing due to the values being not quite right, even to a small degree of accuracy.

This prompted me to find the root cause of the issue which appears to be this inaccurate configured conversion value.

Funnily enough, in the original commit for this quantity the conversion number and the value used in the tests is different! Maybe I'm misunderstanding that test value though. Original commit: https://github.com/angularsen/UnitsNet/commit/4eb94e9256c423c8fa3d9ee42b004ccc16906b68

**Comment by lipchev** [comment]
I've also noticed some issues while doing one of my PRs targeting v6. In my change-set I've tried to resolve them by unifying the conversions using the same constant:
 
`VolumeFlow.json`:
```
 {
   "SingularName": "CubicFootPerSecond",
   "PluralName": "CubicFeetPerSecond",
   "FromUnitToBaseFunc": "{x} * 0.028316846592",
   "FromBaseToUnitFunc": "{x} / 0.028316846592",
   "Localization": [
     {
       "Culture": "en-US",
       "Abbreviations": [ "ft³/s" ]
     }
   ]
 },
 {
   "SingularName": "CubicFootPerMinute",
   "PluralName": "CubicFeetPerMinute",
   "FromUnitToBaseFunc": "{x} * 0.028316846592 / 60",
   "FromBaseToUnitFunc": "{x} / (0.028316846592 / 60)",
   "Localization": [
     {
       "Culture": "en-US",
       "Abbreviations": [ "ft³/min", "CFM" ]
     }
   ]
 },
 {
   "SingularName": "CubicFootPerHour",
   "PluralName": "CubicFeetPerHour",
   "FromUnitToBaseFunc": "{x} * 0.028316846592 / 3600",
   "FromBaseToUnitFunc": "{x} / (0.028316846592 / 3600)",
   "Localization": [
     {
       "Culture": "en-US",
       "Abbreviations": [ "ft³/h", "cf/hr" ]
     }
   ]
 },
```
`StandardVolumeFlow.json`:

```
  {
    "SingularName": "StandardCubicFootPerSecond",
    "PluralName": "StandardCubicFeetPerSecond",
    "FromUnitToBaseFunc": "{x} * 0.028316846592",
    "FromBaseToUnitFunc": "{x} / 0.028316846592",
    "Localization": [
      {
        "Culture": "en-US",
        "Abbreviations": [ "Sft³/s" ]
      }
    ]
  },
  {
    "SingularName": "StandardCubicFootPerMinute",
    "PluralName": "StandardCubicFeetPerMinute",
    "FromUnitToBaseFunc": "{x} * 0.028316846592 / 60",
    "FromBaseToUnitFunc": "{x} / (0.028316846592 / 60)",
    "Localization": [
      {
        "Culture": "en-US",
        "Abbreviations": [ "scfm" ]
      }
    ]
  },
  {
    "SingularName": "StandardCubicFootPerHour",
    "PluralName": "StandardCubicFeetPerHour",
    "FromUnitToBaseFunc": "{x} * 0.028316846592 / 3600",
    "FromBaseToUnitFunc": "{x} / (0.028316846592 / 3600)",
    "Localization": [
      {
        "Culture": "en-US",
        "Abbreviations": [ "scfh" ]
      }
    ]
  }
```

Perhaps we could do the same for the Uk stuff as well?

**Comment by lipchev** [comment]
Well, I was going to make one.. However there are a quite a few matches when we search for `Hour` so I was thinking of making one "Unifying the conversion format for all time based units". 
@angularsen Do you think we should make this for v5 or v6?

**Comment by angularsen** [comment]
We can do both v5 and v6 if you are up for it 👍

**Comment by angularsen** [comment]
I'm fine either way, no need for any particular grouping for review purposes.
But, since the change will be fairly similar across the board, then larger PRs may speed things up. 
However we can merge in in smaller pieces if it makes it easier for you.
