### ISSUE TITLE
New Units - Molecular Mass (Dalton)

### ISSUE THREAD

**Issue by rogerfydp** [angularsen/UnitsNet#1397]
**Is your feature request related to a problem? Please describe.**
Within existing quantity [Mass](https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/Mass.json) there is no units often used for "Molecular mass"

**Describe the solution you'd like**
[Molecular mass](https://en.wikipedia.org/wiki/Molecular_mass) (m) is the mass of a given molecule. The unit [dalton](https://en.wikipedia.org/wiki/Dalton_(unit)) (Da) is often used.

Will be nice to extend the quantity mass (if it's the proper one) to include [Dalton (unit)](https://en.wikipedia.org/wiki/Dalton_(unit)) such as,

- **Daltons (Da)** - Used for individual molecules or small biomolecules.
- **Kilodaltons (kDa)** - Used for larger molecules, such as proteins.
- **Megadaltons (MDa)** - Used for very large molecular complexes, such as viruses and large protein assemblies.
- **Gigadaltons (GDa)** - Used for extremely large molecular structures.

**Describe alternatives you've considered**
None. Using other mass units for 'molecular mass' is not common.

**Comment by angularsen** [comment]
Hi, sure this sounds reasonable to add.
Would you be interested in attempting a pull request? I'm happy to assist.

Detailed steps here:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

**Comment by rogerfydp** [comment]
Hi, thanks for accepting it!

I can do a pull request, no problem.

I was adding the quantity **mass.json** in the following way,

```json
{
  "SingularName": "Dalton",
  "PluralName": "Daltons",
  "BaseUnits": {
    "M": "Dalton"
  },
  "FromUnitToBaseFunc": "{x} * 1.66053906660e-27",
  "FromBaseToUnitFunc": "{x} / 1.66053906660e-27",
  "Prefixes": ["Kilo", "Mega", "Giga"],
  "Localization": [
    {
      "Culture": "en-US",
      "Abbreviations": ["Da"]
    }
  ],
  "XmlDocSummary": "A Dalton, also known as the unified atomic mass unit, is a unit of mass commonly used to express the mass of atoms and molecules. It is defined as one twelfth of the mass of an unbound neutral atom of carbon-12 in its nuclear and electronic ground state.",
  "XmlDocRemarks": "https://en.wikipedia.org/wiki/Dalton_(unit)"
}
```

Taking initially the value from Wikipedia. But when double checking with other sources I see variations, here some examples.

| Source  | Value |
|---------|--------|
| [Wikipedia](https://en.wikipedia.org/wiki/Dalton_(unit)) | 1.66053906892(52)×10−27 kg |
| [CODATA (2018)](https://physics.nist.gov/cuu/pdf/JPCRD2018CODATA.pdf) (page 50) |  1.66053906660(50)x10−27 |
| [UCLA](https://www.chem.ucla.edu/~harding/IGOC/A/amu.html) |  1.660538921x10−27 kg |
| [chemeurope.com](https://www.chemeurope.com/en/encyclopedia/Atomic_mass_unit.html) |  1.660538782(83)×10−27 kg |

On the other hand, on Wikipedia's article, in the references we can find

- [Bureau International des Poids et Mesures (2019): [The International System of Units (SI)] 9th edition, English version, page 145](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf) which value is `1 Da = 1.66053906660(50)×10−27 kg` which matches with `CODATA 2018`.

Therefor I would like your opinion on the value to take, to comply with your project. Do you have any other reference or source?

Thanks!

**Comment by angularsen** [comment]
@rogerfydp Sorry for the late reply.
I don't have any domain knowledge here, but generally I would follow SI definitions.

The wiki article seems quite thorough, but I'm confused why the wiki constant differs from CODATA/SI and I can't see any reference to where they got their value.

Until we learn otherwise, I'd say use CODATA/SI. They seem fairly up to date at least.
