### ISSUE TITLE
Add new unit conversion for mmol/kg

### ISSUE THREAD

**Issue by Martian42** [angularsen/UnitsNet#1402]
**Is your feature request related to a problem? Please describe.**
Add Molality unit prefix for millimole per kg (mmol/kg)

**Describe the solution you'd like**
Add SI unit conversion to the relevant existing Json files from new units descripted above.

**Describe alternatives you've considered**
The units are not covered by the existing UnitNet, but they are within existing Json files.

**Additional context**
Happy to write the code and raise a PR if you agree it's worth adding. They are units type already considered in Unitnet but simply adding to the range of conversion capability. All units above are commonly used world wide for a wide ranges of field.

**Comment by Martian42** [comment]
Please note μS/cm, mg/L is already in UnitNet. I can't change the name of the issue.

**Comment by angularsen** [comment]
Sorry for late reply, I replied in #1403
