### ISSUE TITLE
Removing the operators with `TimeSpan` in v6?

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#1413]
I just found minor breaking change between v5 and v6 that I don't believe was mentioned anywhere:

```
        /// <summary>Get <see cref="Mass"/> from <see cref="TimeSpan"/> times <see cref="MassFlow"/>.</summary>
        public static Mass operator *(TimeSpan time, MassFlow massFlow)
        {
            return Mass.FromKilograms(massFlow.KilogramsPerSecond * time.TotalSeconds);
        }

        /// <summary>Get <see cref="Mass"/> from <see cref="MassFlow"/> times <see cref="Duration"/>.</summary>
        public static Mass operator *(MassFlow massFlow, Duration duration)
        {
            return Mass.FromKilograms(massFlow.KilogramsPerSecond * duration.Seconds);
        }
```

The `TimeSpan` overload has been removed (relying on the implicit conversion to `Duration`), and while we have the inverse overload in `Duration` (i.e. `*(Duration duration, MassFlow massFlow)`) the following expression is no longer correctly inferred:

```
var massEvaporated = (weightAssay.Date - currentValue.Date) * evaporationRate; // does not compile
```

Everything is fine if we inverted the order of operations: 

```
var massEvaporated = evaporationRate * (weightAssay.Date - currentValue.Date); // no problem
```

I personally don't mind the removal (note that the implicit conversion from `TimeSpan` is lossless in my upcoming proposal for v6), but if we wanted - there would be no particular difficulty in having the operation overload added to the `MassFlow.extra.cs`.

I assume this affects all multiplications with `TimeSpan` (e.g. `VolumeFlow` and such)..

**Comment by angularsen** [comment]
I think it's important that UnitsNet don't add unnecessary friction on this, so if some overloads don't work with implicit cast to Duration, then we should add the corresponding TimeSpan overload.

**Comment by Muximize** [comment]
This was discussed here: https://github.com/angularsen/UnitsNet/pull/1354#discussion_r1493344825

And implemented here: https://github.com/angularsen/UnitsNet/pull/1365

**Comment by angularsen** [comment]
@Muximize I believe we can adapt #1365 to take into account left hand args of TimeSpan, and autogenerate explicit overloads for these cases, right?

**Comment by Muximize** [comment]
Yes, this will add 28 additional operators to the current set of units. I tested two ways of doing this:

1. Generating the operators exactly like the others, adding to `QuantityRelationsParser.cs`:
```csharp
var timeSpanQuantity = pseudoQuantity with { Name = "TimeSpan" };
relations.AddRange(relations
    .Where(r => r.LeftQuantity.Name is "Duration")
    .Select(r => r with { LeftQuantity = timeSpanQuantity, LeftUnit = r.LeftUnit with { PluralName = "Total" + r.LeftUnit.PluralName } })
    .ToList());
```

2. Just reversing the operands so they use the implicit conversion, adding to `QuantityGenerator.cs`:
```csharp
if (relation.RightQuantity.Name is "Duration")
{
    Writer.WL($@"
        /// <summary>Get <see cref=""{relation.ResultQuantity.Name}""/> from <see cref=""TimeSpan""/> {relation.Operator} <see cref=""{relation.LeftQuantity.Name}""/>.</summary>
        public static {relation.ResultQuantity.Name} operator {relation.Operator}(TimeSpan timeSpan, {relation.LeftQuantity.Name} {leftParameter}) => {leftParameter} {relation.Operator} timeSpan;
");
}
```

**Comment by angularsen** [comment]
Without fully groking the full context here, I _think_ solution 1 feels natural?
I'm fine either way as long as there is a comment next to it explaining why.

**Comment by angularsen** [comment]
Nr2 seems the most straight forward though, but I was puzzled by `relation.RightQuantity.Name`, should it not be LeftQuantity?

**Comment by Muximize** [comment]
Normally, if a quantity (say Power) has a relation with Duration, then `power * duration` will be in `Power` and `duration * power` will be in `Duration`

Because implicit conversion only works for the right operand, we have to generate `timespan * power`. We cannot add this to `TimeSpan` (not ours) and not to `Duration` (not part of the operator) so we have to add it to `Power`, and we inter it from `power * duration`. Hence the `relation.RightQuantity.Name`

We do a similar thing with relations involving `double`.
