### ISSUE TITLE
Quantiy SpecificFuelConsumption units symbols contain invalid characters

### ISSUE THREAD

**Issue by josefprinz** [angularsen/UnitsNet#1417]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (just an example):
1. Add nuget UnitsNet 4.9.0 to a .NET 4.0 project
2. Build using Visual Studio 2017 Community v15.9.2
3. See error: "foo"

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by angularsen** [comment]
That is an ancient version, try upgrading the nuget. The latest 4.x is https://www.nuget.org/packages/UnitsNet/4.152.0.

Beyond that, we don't really support older major versions unless there is something very wrong and easy to fix.

The latest major versions are 5.x and pre-release of 6.x.
https://www.nuget.org/packages/UnitsNet/5.57.0
https://www.nuget.org/packages/UnitsNet/6.0.0-pre011

**Comment by angularsen** [comment]
Also, netstandard2.0 is required for 5.x so it would require minimum .NET 4.6.2.
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0
