### ISSUE TITLE
Can not set QuantityName for Custom Units

### ISSUE THREAD

**Issue by Chef904** [angularsen/UnitsNet#1418]
I cannot set the QuantiyName for a custom Unit because the constructor is internal.

This is the code exampe in this repo:

```
public QuantityInfo QuantityInfo => new(
            nameof(HowMuch),
            typeof(HowMuchUnit),
            new UnitInfo[]
            {
                new UnitInfo<HowMuchUnit>(HowMuchUnit.Some, "Some", BaseUnits.Undefined, nameof(HowMuch)),
                new UnitInfo<HowMuchUnit>(HowMuchUnit.ATon, "Tons", BaseUnits.Undefined, nameof(HowMuch)),
                new UnitInfo<HowMuchUnit>(HowMuchUnit.AShitTon, "ShitTons", BaseUnits.Undefined, nameof(HowMuch)),
            },
            HowMuchUnit.Some,
            Zero,
            BaseDimensions.Dimensionless);
```

But in an other Assembly where i have my custom units, i cannot add the quantity Name to my UnitInfo:

![grafik](https://github.com/user-attachments/assets/8f650ca1-8609-4d33-8734-9255738f70aa)

**Comment by angularsen** [comment]
Hi, thanks for reporting. This seems like an oversight, now fixed.

**Comment by angularsen** [comment]
[Release UnitsNet/5.58.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.58.0)
