### ISSUE TITLE
Access modifier on `UnitsNetSetup.Default.QuantityParser` is non-public

### ISSUE THREAD

**Issue by gmkado** [angularsen/UnitsNet#1427]
`QuantityParser.Default` has an obsolete attribute with message "Use UnitsNetSetup.Default.QuantityParser instead", but this field is internal.  What is the recommended way to access the `QuantityParser`?

https://github.com/angularsen/UnitsNet/blob/e08025456013d6a4826f1bd6c3276d7a43560836/UnitsNet/CustomCode/QuantityParser.cs#L40C46-L40C61

**Comment by lipchev** [comment]
@angularsen In my upcoming proposal for v6 I've prepared some extensions for configuring the UnitsNetSetup, which (IMO) don't require us to remove the `UnitParser.Default`, `QuantityParser.Default` etc.. I personally think those are still useful (the access via `UnitsNetSetup.Default` is pretty verbose)..

**Comment by angularsen** [comment]
It is now public, in both v5 and v6.
52aba985

Also, we decided to keep the static `Default` getters, like `QuantityParser.Default` for convenience.
#1480
