### ISSUE TITLE
Duration seconds to nanoseconds is not precise

### ISSUE THREAD

**Issue by EddyHaigh** [angularsen/UnitsNet#1434]
**Describe the bug**
Using `UnitsNet.Duration.FromSeconds(1).Nanoseconds` produces `999999999.9999999` which not precise compared to other similar down scaled conversions for duration e.g. ms, µs.

**To Reproduce**
1. Add nuget UnitsNet 5.60.0 to a .NET 8.0 project
2. Build using Visual Studio 2022 Community v17.12.1
3. In a ConsoleApp write `UnitsNet.Duration.FromSeconds(1).Nanoseconds` to the console

**Expected behavior**
Nanoseconds produced from converting from seconds should produce `1000000000` rather than losing precision

**Screenshots**
![image](https://github.com/user-attachments/assets/bc195b12-f15a-4ccf-87c8-8f8d45ff4da2)

**Additional context**
The normal TimeSpan (`TimeSpan.FromSeconds(1).TotalNanoseconds`) contains a more accurate nanoseconds

**Comment by lipchev** [comment]
Hi Eddy, 

this is a known limitation of the current implementation: having a `double` as the underlying value type, the conversions often introduce a small rounding error. Here's a quote that we should have probably added to the wiki page long ago:

> The double data type in C# uses a binary floating-point representation, which complies with the [IEC 60559:1989 (IEEE 754)](https://en.wikipedia.org/wiki/IEEE_754) standard for [binary floating-point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic).

Hopefully this won't be required with my upcoming proposition for replacing the `double`s  (the PR should be out this weekend).
