### ISSUE TITLE
TemperatureChangeRate conversion wrong way around

### ISSUE THREAD

**Issue by vierlijner** [angularsen/UnitsNet#1435]
In file TemperatureChangeRate I think they put the from and to formulas the wrong way around. From minutes to sec is * 60 instead of / 60.

**Comment by vierlijner** [comment]
I saw this because of commit #1429

**Comment by angularsen** [comment]
No I believe it is correct, but you are perhaps confused by the "inversion" of a temperature unit over time?

DegreeCelsiusPerMinute is simpler to look at, and `"FromBaseToUnitFunc": "{x} * 60",` does get you from base unit `DegreeCelsiusPerSecond` to `DegreeCelsiusPerMinute`. E.g. `(1 DegreeCelsiusPerSecond) * 60 => 60 DegreeCelsiusPerMinute`

We also verify the direction by having both roundtrip tests and oneway tests, and double checking with Google confirms it.


![image](https://github.com/user-attachments/assets/77e5f977-8ba4-47c4-8b21-8b01dbc690b6)

![image](https://github.com/user-attachments/assets/dbffbc54-30e9-4203-bfb4-89064e67ebe1)

![image](https://github.com/user-attachments/assets/416f51d9-14fb-4898-8818-4d5c2464ddd0)

![image](https://github.com/user-attachments/assets/725cc60d-9f94-49fd-a64a-04748a4c1e89)

**Comment by vierlijner** [comment]
O yes I see, I forgot that it's divide by time, so you have to invert the operation. Thank and sorry, I had to verify it first. (but in my head it was so obvious, but to fast).

**Comment by angularsen** [comment]
No problem 😄
