### ISSUE TITLE
Calculate/ implement a unit containing 2 units different

### ISSUE THREAD

**Issue by vierlijner** [angularsen/UnitsNet#1436]
### "Problem"
Now we have to do for every possible combination write out all combinations and formulas and tests. For example in [speeds](https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/Speed.json). You have written out many combinations, but I think this is not necessary!
When we have ft/s to km/h, we do ft/s to m/s and then to km/h and do this for all combinations (and that are a lot). So write out all PluralNames and all formulas to and from the base unit.
But we know that m/s is the base and we can calculate from length m to all other length and can do this also for the second unit seconds in duration.

### Solution
So can we better delete all options in speed and calculate this automaticly based on the base units/ dimensions?
Again with the example ft/s to km/h, we first calculate from ft to km in Length and than use this calculated outcome to convert s to h and then we also have the answer. And we don't have witten out all combination in speeds, because we have this also combined in length and duration.

#### Your opinion
I know this is a big change, but I think it's more robust and reduces the combinations to write (out).

What are your thought on this?

_P.s. I haven't thought about implementation details, first I want to know if you allready thought about this or had give this a (failed) try!_

**Comment by lipchev** [comment]
Have a look at [this article](https://en.wikipedia.org/wiki/International_System_of_Units#Definition), it captures a lot of the nuances regarding the base-units and their derivatives. [This one](https://en.wikipedia.org/wiki/Dimensional_analysis) also has a lot of the formalism on the subject nicely laid out. 

What you're suggesting looks like the definition of the [coherent units of measurements](https://en.wikipedia.org/wiki/Coherence_(units_of_measurement)) however, in practice there a bunch more "conventional" units- which often don't have corresponding base units- take for example the "Knot" or the "Mach".

It is technically possible to obtain a lot of the conversion coefficients from the "Dimensions" / "BaseUnits" of the json definitions, but not all.

**Comment by angularsen** [comment]
Thanks for the idea, I'm not sure how we would approach this to solve all our existing units, but I'm open to simplifying the setup. 

Although the current setup with JSON files describing each unit with many overlapping definitions is kind of verbose, it is also fairly easy to reason about and easy for new contributors to add new units. But it would be interesting if we could basically generate most of the existing units, and a bunch of new ones, and then just manually add any units that are not easily generated.

If you want to take a stab at an implementation and play with it to see how far you can get in generating our existing units, I'm interested to learn what you can come up with 😃

I'll close this for now, but we'll reopen if you want to pursue this.
