### ISSUE TITLE
UnitParser: fix the nullability of the Parse / TryParse overloads

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#1445]
Can we add this to #1200 

- [`public Enum Parse(string? unitAbbreviation, Type unitType, IFormatProvider? formatProvider = null)`](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L65):  `unitAbbreviation` should be non-nullable..
- [`public bool TryParse<TUnitType>(string unitAbbreviation, out TUnitType unit) where TUnitType : struct, Enum`](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L141) : `unitAbbreviation` should be nullable
- [`public bool TryParse(string unitAbbreviation, Type unitType, [NotNullWhen(true)] out Enum? unit)`](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L172):  `unitAbbreviation` should be nullable

**Comment by lipchev** [comment]
Oh I just realized this also the case for the static method on the quantities (e.g. `Mass.TryParseUnit(..)`):

- [`public static bool TryParseUnit(string str, out MassUnit unit)`](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/Mass.g.cs#L835)
- [`public static bool TryParseUnit(string str, IFormatProvider? provider, out MassUnit unit)`](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/Mass.g.cs#L850)

**Comment by angularsen** [comment]
Added it

**Comment by angularsen** [comment]
Fixed by #1446
