### ISSUE TITLE
Support non-linear unit conversions

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#21]
Currently the unit attributes support either a constant factor or a linear expression of the form y = ax + b. The latter was needed for conversion between temperature units. All other units so far use only a conversion factor.

However, there are non-linear units and unit conversions and there is currently no way of adding those using the current T4 templates.

Examples of non-linear units and unit conversions:
http://en.wikipedia.org/wiki/Sound_pressure
http://www.sengpielaudio.com/calculator-soundlevel.htm

Possible solution:
Use Expression to describe the conversion function, such as 

[Length(x => 1000x)] Kilometer,
[SoundPressureLevel(x => 10_Math.Log(x_x/Math.Pow(20e-6, 2))] Decibel

The generated code will then call the expression to calculate the value. Note that this may(?) have significant performance impact, need to investigate. In that case, we should only use this for units that need it and keep the linear function for all other units since the compiler can reduce that to simple multiplication by and addition of constants.

---

Side note on sound pressure level as an example of non-linear unit:
- Decibel is a generic unit, not just for sound.
- Decibel in in this case is defined as sound pressure relative to a reference sound pressure, typically 20 micropascals in air, but wikipedia also states that underwater 1 micropascal is used. So this expression might need to take a second parameter, the reference value. Might become complicated to use. Need a real application or usage scenario for this unit to make sure it gets implemented right.

**Comment by JKSnd** [comment]
Just putting it on your radar that I have a need to represent an AmplitudeRatio in dBu (reference 0.775 V rms). I'm going to do some more reading and evaluating and will come up with a PR soon.

**Comment by anjdreas** [comment]
This thread is old, check out our logarithmic units, such as https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/Scripts/UnitDefinitions/AmplitudeRatio.json

Is something like that what you are looking for?
