### ISSUE TITLE
Operations between Pressure, ForcePerLength, Force, etc.

### ISSUE THREAD

**Issue by samirem** [angularsen/UnitsNet#269]
Hi!

I'd like to be able to perform operations between various units, for example Force/Area=Pressure.

The way I currently do it is (Force.Newtons/Area.SquareMeters).Pascals(). This isn't all that bad, but when performing a lot of calculations it's quite nice to avoid all this boilerplate code.

Is this something that the library has any interest in implenenting? Do you otherwise recommend that I implement some kind of extension myself?

Thanks.

**Comment by eriove** [comment]
Operator overloads should exist for most units. Feel free to add more with a pull request if you are missing any. As an example you can take a look at [Force.extra.cs](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/CustomCode/UnitClasses/Force.extra.cs) (which contains your example).
