### ISSUE TITLE
Points, Pixels, Dots, Dots/Inch, Pixels/Inch

### ISSUE THREAD

**Issue by jay1891** [angularsen/UnitsNet#271]
Hey Andreas, UnitsNet is a very nice library! What I can't find is a conversion between pixels, points, dots, mm, inch, and also between pixels/inch, dots/inch.

Are there any plans to add this in the future?

**Comment by eriove** [comment]
How would you like to use these conversions in code? Is there a global relation between pixels, points and dots or is it platform specific?

**Comment by jay1891** [comment]
There are global relations between them.

A detailed list of conversions:
- http://www.unitconverters.net/typography-converter.html

For more detail, the following can clarify:
- https://graphicdesign.stackexchange.com/questions/199/point-vs-pixel-what-is-the-differenceµ

**Comment by anjdreas** [comment]
@jay1891 Interesting. I think we should be able to do something here, but we need a design proposal. Would you care to draft up some pseudocode or bulletpoints describing how you envision using this?

I just brifely skimmed the links and the stackexchange link comments pointed out some possible challenges, such as non-square pixels and PPI vs DPI.

**Comment by jay1891** [comment]
Hey Andreas, I just discovered the UnitsNet library, I see what I can do.

Related to the non-square aspect you mention. Pixels themself have no shape. A pixel is image data e.g. RGB data that can be placed in a grid. From the moment the pixel is rendered on screen or printed it will get a shape on screen or paper, and thereby an x & y length for each pixel because of a certain amount of ppi (screen) or dpi (printer) in each direction. Then knowing a certain number of pixels, and knowing the ppi or dpi in each direction, the length can be calculated for these number of pixels. With this length a conversion is possible to points, inch, feet, millimeters.

In the cases I currently I have I start with 2 variables, I know the number of pixels, and the ppi. I can then calculate the length. If I understand the UnitsNet design good, and if I have the length, then I should be possible to do: length.DTPPoints, length.PrinterPoints, length.Inches, length.Feet, length.Millimeters ?

I think the DTPPoints & PrinterPoints parts are missing and could maybe be valuable? There are at least standarized. 
https://en.wikipedia.org/wiki/Point_(typography)
http://www.dozenalsociety.org.uk/history/points.html

DTPPoints :
       /// <summary>
        ///     Get Length in Desktop Publishing Points.
        /// </summary>
        public double DTPPoints
        {
            get { return _meters * 39.37007874 * 72; }
        }
1 meter = 39.37007874 inch & 1 inch = 72 points 

PrinterPoints :
       /// <summary>
        ///     Get Length in Printer Points.
        /// </summary>
        public double PrinterPoints
        {
            get { return _meters * 39.37007874 * 72.27; }
        }
1 meter = 39.37007874 inch & 1 inch = 72.27 points

To easily come from Pixels to the length in the first place, maybe the following could also be valuable?
        /// <summary>
        ///     Get Length from Pixels.
        /// </summary>
        public static Length FromPixels(long pixels, long pixelsPerInch)
        {
            return new Length(<I can add the formula later if it can be relevant?>);
        }

Some specific platform assumptions could be made for the ppi. Specifically on the web (WC3), and also by Microsoft (Windows) the conversion from pixels to inch, point, cm and other units has been standardized, and the standard ppi is 96.
**W3C**: https://www.w3.org/TR/css3-values/#absolute-lengths
**Microsoft:** https://github.com/jeremejevs/milk-manager/blob/master/wp-toolkit/Microsoft.Phone.Controls.Toolkit/Common/LengthConverter.cs
For more details, see also the following discussion:
https://stackoverflow.com/questions/139655/convert-pixels-to-points

In general I can also add this logic in our code as extension methods. But if it could be interesting, I can send them later for evaluation, to see if it can be relevant to add to the library?

**Comment by jay1891** [comment]
I have to say that there are different definitions of a point, but only the 2 I mention previously (DTPPoints & PrinterPoints) are from what I understand/experience the most widely used. I don't know if the UnitsNet library would apply an approach as the following?

`       /// <summary>`
`        ///     Get Length in Points.`
`        /// </summary>`
`        public double Points(PointType pointType)`
`        {`
`            get { <switch case for the point types> }`
`        }`

The PointType enum could then maybe contain the following Point types (https://en.wikipedia.org/wiki/Point_(typography)) (see also list below)? But this method approach various with the property approach you currently have?

Origin | Year | µm | inch
-- | -- | -- | --
Truchet | 1694 | ≈ 188 | ≈ 0.007 400 48
JIS,[6] CSS q, DIN[7] | 1976 | = 250 | ≈ 0.009 843 | =  5⁄508
Fournier | 1737 | ≈ 345 | ≈ 0.013 582 677
Johnson, ATA | 1886 | = 351.36 | = 0.013 833 | =  83⁄6000
Japan[8] | 1962 | = 351.4 | ≈ 0.013 835
variant[who?] |   | ≈ 351.406 | ≈ 0.013 835
Hawks | 1879 | ≈ 351.456 | = 0.013 837
TeX pt |   | = 351.459 80 | ≈ 0.013 837 | =  100⁄7227
PS, CSS pt, TeX bp | 1984 | = 352.7 | = 0.013 888 | =  1⁄72
Tex nd[9] | 1975 | = 375 | ≈ 0.014 764 | =  15⁄1016
Tschichold |   | ≈ 375.94 | ≈ 0.014 801 | =  250⁄16891
Didot | 1770 | ≈ 375.97 | ≈ 0.014 802
Berthold |   | = 376 | ≈ 0.014 803 | =  47⁄3175
TeX dd[10] |   | ≈ 376.065 | ≈ 0.014 806
Mozilla dt[11] | 1997 | = 376.296 | = 0.014 8 | =  2⁄135
Antenna House dd[12] |   | ≈ 376.682 | = 0.014 83
L’Imprimerie nationale |   | = 400 | ≈ 0.015 748

**Comment by anjdreas** [comment]
It took me some time to get to this, but thanks for the thoroughly prepared information.

So, if I get this right, you propose to introduce some widely used and standardized units for absolute lengths in typography; *DTP Points*, *Printer Points* and *W3C Pixels*. There are many other variants, but they are less widely used.

Here are some example usages:
```
Length inch = Length.FromInches(1);
double dtpPoints = inch.DtpPoints; // 72
double printerPoints = inch.PrinterPoints; // 72.27
double w3cPixels = inch.W3cPixels; // 96
Length inchDtp = Length.FromDtpPoints(72); // 1 in
Length inchPp = Length.FromPrinterPoints(72.27); // 1 in
Length inchW3c = Length.FromW3cPixels(96); // 1 in
```

This would be easy to implement by adding `DtpPoint`, `PrinterPoint` and `W3cPixel` to [Length.json](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/UnitDefinitions/Length.json).

I think some of the other units listed in [Typography Converter](http://www.unitconverters.net/typography-converter.html) should also be added: *twip, pica*
But I am unsure about these: *character*, *en*

I still find W3C pixels hard to grok.
> The reference pixel is the visual angle of one pixel on a device with a pixel density of 96dpi and a distance from the reader of an arm’s length. For a nominal arm’s length of 28 inches, the visual angle is therefore about 0.0213 degrees. For reading at arm’s length, 1px thus corresponds to about 0.26 mm (1/96 inch).

When is this usecase practical for converting pixels into a length?

If I understand correctly we are talking about the perceived length, or view angle, when looking at a screen at a certain distance and a certain DPI. I can't seem to make sense of this part.

I get printing, where you have an image X/Y pixels wide/long and it has a DPI of 300 so you can figure out how many inches wide/long its print will be. Same with PC monitors, where size and resolution is known so you know how many pixels per inch (PPI) and thus can render a 5cm long line. However, I don't get W3C's pixels, and translating that to a physical length.

Hope you can enlighten me! :-)

Other than that, I think I understand what you want to accomplish and this looks straight forward to me. Let me know what you think.

**Comment by jay1891** [comment]
The **DtpPoint** and **PrinterPoint** I definitely think are useful and very widely accepted/standarized. 

You mention:
> I get printing, where you have an image X/Y pixels wide/long and it has a DPI of 300 so you can figure out how many inches wide/long its print will be. Same with PC monitors, where size and resolution is known so you know how many pixels per inch (PPI) and thus can render a 5cm long line. However, I don't get W3C's pixels, and translating that to a physical length.

The DPI (Printing) & PPI (Screen) use cases you describe are exactly the main uses cases, I think, but maybe the UnitsNet library doesn't have to add anything for this? 

Personally I would not add the **W3C pixel feature**, because it is more controversial, and I don't understand it enough either e.g. the part with the angle... to which you refer in the following:
> The reference pixel is the visual angle of one pixel on a device with a pixel density of 96dpi and a distance from the reader of an arm’s length. For a nominal arm’s length of 28 inches, the visual angle is therefore about 0.0213 degrees. For reading at arm’s length, 1px thus corresponds to about 0.26 mm (1/96 inch).

**Comment by jay1891** [comment]
Thank you for looking into this Andreas! :)

**Comment by anjdreas** [comment]
Well thank you, it's only grown into what it is thanks to guys like yourself contributing to it.

So I guess we agree on at least an initial feature here:
* Add DtpPoint and PrinterPoint to Length
* I would also add Twip and Pica while at it, they seem referenced in a lot of the articles you linked

Would you care to do a pull request?

I really want the person with the idea to add it as you know the domain best and it makes it a lot easier to add future units you come up with later. Plus, it adds a bit of flair to your github account having contributed to an open source project :-)

**Comment by anjdreas** [comment]
https://github.com/anjdreas/UnitsNet#contribute

**Comment by jay1891** [comment]
@anjdreas yesterday I created a pull request. If there are any remarks, please let me know.

**Comment by anjdreas** [comment]
Thanks! I saw, will review it soon
