### ISSUE TITLE
Create strongly typed object from database

### ISSUE THREAD

**Issue by bragma** [angularsen/UnitsNet#289]
Hi,
mine is not an issue (great lib!) but a request for ideas. I have to define some generic measure types in my DB having a name, a type and a default unit. This will allow users to create values chosing the type of value from the predefined types. As an example, suppose I define the measure type "Height", with default unit "Length.Centimeter". Users can then enter values related to height and store them (as doubles) in the DB.
Now, when I retrieve the heights I can decide to convert them to meters or inches or feetinches.
I'm not sure about how to do that. As a start, UnitsNet does not distinguish between Metric/Imperial units, but I can do that myself, not a problem here.
As an experiment I'm more or less using the same method show in the unitsconverter and json serializer to store the unit as a string in the DB. Still I'm not sure on how to create an object of the specified unit type and call methods to convert them from metric to imperial units.
Probably it's a newbie question, but how can I create object of the correct type and be able to cast conversion methods on them? Deserialization from Json requires me to specify the type, does this mean I need a large switch/case for all quantitytypes (ex: Power, Energy, Length, Mass, etc) for populating a specific Power, Energy mass typed variable?
Thanks for any idea on how to proceed.

**Comment by angularsen** [comment]
Hi there,

Take a look at this section in the README: https://github.com/angularsen/UnitsNet#example-creating-a-unit-converter-app.

If I understand your case correctly, it's a matter of storing something like this in your DB: 
```
UnitPreference: "Metric"
HeightQuantity: "Length"
HeightDefaultUnit: "Centimeter"
HeightUnit: "Centimeter"
HeightValue: 180
HeightMetricUnitOptions: ["Meter", "Centimeter", "Millimeter"]
HeightImperialUnitOptions: ["Yards", "Foot", "Inch"]
```

Then present those options in the UI for height selection, based on whether imperial or metric is selected. When user changes from Metric to Imperial, then you could also auto-convert to the most sensible imperial unit and store that immediately.

Upon typing a new value, just store the new value in DB as `HeightValue`.

Upon selection of a different unit: 
```
string prevUnit = "Centimeter";
string newUnit = "Inch";
double heightValueFromUi = 180;
string heightQuantity = "Length"; // from DB
double convertedValue = UnitConverter.ConvertByName(heightValueFromUi, heightQuantity, prevUnit, newUnit); // 70.8661 inches - store this as HeightValue in DB

**Comment by bragma** [comment]
@angularsen Thanks, this is more or less what I am doing. I was wondering if I could get away from defining lists of units for metric and imperial, but thinking about it it just does not make any sense.

**Comment by angularsen** [comment]
Right, I think this is best left to each application define - although we could provide some lists of imperial vs metric units for all our units, you usually want to filter it down to some few units anyway.

**Comment by bragma** [comment]
I've ended up with a list of units and preferred conversions, from unit to unit trying to preserve scale. As an example, it may make sense to convert cm to in, but not cm to mi. A more sensible way is to convert between km and mi, or in and cm, etc. So, I still needed to handle the logic myself.

**Comment by angularsen** [comment]
Yup, that makes sense.
