### ISSUE TITLE
Adding TonneSquareMeter to MassMomentOfInertia

### ISSUE THREAD

**Issue by penenkel** [angularsen/UnitsNet#292]
I would like to add TonneSquareMeter as a unit of MassMomentOfInertia. Do I only have to modify the corresponding Json file or is there more to it?

**Comment by plubbr** [comment]
Updating the JSON is the first of just a handful of steps. See the [Wiki page](/angularsen/UnitsNet/wiki/Adding-a-New-Unit) for more direction.
