### ISSUE TITLE
Obscure units

### ISSUE THREAD

**Issue by SeanSt** [angularsen/UnitsNet#296]
Found the custom units explanation, will use those -- but I would LOVE to have access to someones Well Logging units.

In my work I deal with some extremely obscure units that have limited convertibility.  Examples include: 

- Fluidity (measured in dial divisions per minute on a gieseler plastometer (a fixed torque motor with a specified shaft and paddle arrangement)) 

- Vitrinite (measured in points of observation on a 100 point reticule grid) 

Just wondering if it would make sense to push up definitions for these units or if it would be increasing the size of the package for things that no-one else is likely to ever use.  Note that these are not SI units but they are "real" units (recognized by ASTM and other (international) standards).

Thanks again for your time,
Sean

**Comment by angularsen** [comment]
I think this falls outside the core UnitsNet library, but as have been discussed in other issues, we could always create a new domain-specific nuget, such as `UnitsNet.WellLogging`. `PkSpatial` is one such library that is external to `UnitsNet`, but based on it.
The main point is that the domain-expert (you) needs to take responsibility for such a nuget, whether it is hosted here in this repo or elsewhere. If you want to use the `UnitsNet.` prefix, I think it's best if it is hosted here to make it easier to find everything in one place.
