### ISSUE TITLE
Convert length to area/volume

### ISSUE THREAD

**Issue by MattReimer** [angularsen/UnitsNet#300]
Hey,

I didn't see a way to get an equivalent area or volume unit from a length unit. Is there one?

like `m ==> m^2 ==> m^3`

**Comment by angularsen** [comment]
Hi, could you please elaborate? I'm not sure I follow. A real world example would be helpful.

**Comment by MattReimer** [comment]
Sorry, that wasn't a particularly good example. 

I'm talking about converting units to their area/volume equivalents. 

something like this:
```csharp
LengthUnit myLengthUnit = Length.ParseUnit(someString);

# Now I want to get the equivalent volume unit
VolumeUnit myVolumeUnit = myLengthUnit.ConvertToVolume();

# Want to get VolumeUnit.CubicMeter back
```

It's fine if I have to do a lookup table, I was just wondering if you had some clever way to get there.

**Comment by angularsen** [comment]
Ah, I see. There is no built-in for this today. We generally don't have good mappings between 1D/2D/3D of units. I think maybe this is a very specific need and is best kept in application code - although it could very well be added to the library if someone can argue this is something that many more would benefit from.

A look up table is probably the easiest and I would recommend that.
If you have a lot of mappings you could get fancy and use reflection based on names to automatically map between units (meter => squaremeter => cubicmeter).

**Comment by MattReimer** [comment]
Ok. sounds good. Thanks.
