### ISSUE TITLE
Request: Molar Mass

### ISSUE THREAD

**Issue by gratestas** [angularsen/UnitsNet#303]
together with my colleague @ferittuncer, we are modelling a thermodynamic library for a several chemical species. To be able to freely change unit frame, we need to have a `MolarMass `quantity type data on hands. 

For this purpose we propose to contribute to the library by including this type. 

Waiting for feedbacks. Best regards

**Comment by eriove** [comment]
It definitely fits in the library, perhaps it would be worthwhile to add "Amount of substance" (with the SI unit Mole) at the same time?

See [this](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit) page for a description on how to add new quantities.

**Comment by ferittuncer** [comment]
So you suggest to create a new quantity type "AmountOfSubstance" with a unit "Mole", am I right?

I agree that it's a good idea to implement this before other molar based quantities.

About the naming: I think "SubstanceAmount" is better instead of "AmountOfSubstance". What do you think?

**Comment by angularsen** [comment]
On the phone, but this all sounds good to me. I also see there is pound
mole unit maybe worth adding.

About naming, I leave that to you domain experts. AmountOfSubstance is my
preference solely based on that is the naming used in wiki.
