### ISSUE TITLE
Proposal: LapseRate

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#313]
This quantity is commonly used in meteorology.

Lapse rate is the rate of change in temperature observed while moving upward through the Earth’s atmosphere. 

As there is no other quantity proportioning temperature to length, I think it's useful to implement it.

What are your thoughts?

**Comment by angularsen** [comment]
Never heard of this unit before, but meteorology is widely used so I guess this unit has a place in the library. On a side note I am a little concerned with bloating the library and we probably need to start looking for a strategy to split up the library into smaller and more specific chunks at some point, but that is a different discussion.

There are possibly many combinations of units here, with any combination of `Temperature` and `Length` units, so let's only add the commonly used ones.

**Comment by ferittuncer** [comment]
I am going start to work on this soon and add one or two units among the most common ones. 

About splitting,  I guess it will be hard to decide which belongs to which package. Because we should find a way to partition quantities in such a way that each partition only rely itself for conversions etc. Like a software design we have to strive for loosely coupled cohesive partitions. 

Let's create another issue about this and discuss there if you like.
