### ISSUE TITLE
Auto-Generated Abbreviations with Prefixes for Russian

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#315]
As discussed [here](https://github.com/angularsen/UnitsNet/pull/305) we should extend the script to support Russian.

**Comment by angularsen** [comment]
It should be a matter of extending [Add-PrefixUnits in GenerateUnits.ps1](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/Scripts/GenerateUnits.ps1#L158) and removing any redundant Russian prefixes in the `.json` definition files.
