### ISSUE TITLE
LapseRate Unit: KiloDegreesCelsiusPerMeter instead of DegreesCelsiusPerKilometer

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#319]
I recently sent a pull request for LapseRate quantity which is merged, but I see that I created a unit `KiloDegreesCelsiusPerMeter` instead of `DegreesCelsiusPerKilometer`. I want to fix it but I don't know how to prefix a unit which comes after `Per`. 

I checked other quantities, there is no other quantity which has a prefix after `Per`. So I wonder, is it possible? If not, should I use `MilliDegreesCelsiusPerMeter` instead?

**Comment by angularsen** [comment]
It will have to be defined "by hand", defining each unit separately in the quantity json. It can't use the prefixes structure for this, it's a weakness in the design.
