### ISSUE TITLE
New maintainer candidate: Ferit Tunçer

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#320]
Hi guys,

I vote we bring on another maintainer: @ferittuncer 

He has been super active recently and producing quality pull requests from the beginning. I also think he asks some good questions and seem eager to improve this library. I did reach out to him yesterday and he would gladly join as a collaborator.

Yay or nay? :-)

**Comment by eriove** [comment]
Yay! :-)

I agree

**Comment by JKSnd** [comment]
Those are great reasons to bring him on! I agree too

**Comment by angularsen** [comment]
Awesome, it's settled then. Welcome @ferrituncer ! I just added you as a collaborator so you can now push directly to master branch and [release new nugets](https://github.com/angularsen/UnitsNet/wiki/Collaborators:-Release-New-Nuget).

> With great power comes great responsibility

and all that ;-) 

Cheers!

**Comment by ferittuncer** [comment]
Thank you folks, I am glad to be part of this team! I'll do my best to help to maintain Units.NET and be responsible, I promise! 😇
