### ISSUE TITLE
Delta Abbreviation: ∆ instead of ▲

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#327]
We decided in #324, that symbol for delta abbreviation to be ∆. For consistency, we should replace every delta symbol with ∆ instead of ▲ (or whatever currently it is).

**Comment by angularsen** [comment]
To avoid creating a breaking change, the old unit abbreviation should stay, but we add the new abbreviation before it in the list so that it takes presedence in ToString(). We can then add to our #180 wishlist for future removal in a major version bump.

**Comment by angularsen** [comment]
Fixed in #339
