### ISSUE TITLE
Proposal for collaborators: Add changelog when releasing nuget

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#332]
@JKSnd @eriove @ferittuncer Consider this a proposal until we agree on it. I would very much like your input before we decide to make it a routine.

I added a new step in the wiki to also add a GitHub release with a minimal changelog since previous release. It's not a lot of extra work, and makes it easy to read this as a changelog for each release.

I have been sporadically doing this in the past, but I think we should make this a routine since we are now more people that can create nugets and releases.

I have created/edited releases for tags down to 3.76.0 (October).

Releases: https://github.com/angularsen/UnitsNet/releases/
Wiki: https://github.com/angularsen/UnitsNet/wiki/Collaborators:-Release-New-Nuget

New bullet point in wiki:
* [Create release by editing tag](/angularsen/UnitsNet/releases) in GitHub, copy in all notable commit messages since previous tag (usually pull request commits)

So, what do you think? Yay or nah-adds-effort-and-not-much-value?

**Comment by ferittuncer** [comment]
I think we should keep changelogs. If we could find an automation tool which writes changelogs from commit messages it would be great though. This would also incentivize writing better commit messages.

**Comment by JKSnd** [comment]
I love changelogs. I'm into it.

**Comment by angularsen** [comment]
Cool, just waiting for @eriove to chime in before we decide.

**Comment by eriove** [comment]
Change logs are good. Let do this.

**Comment by angularsen** [comment]
Alright then, it's settled :-) Leaving the wiki as-is and from now on let's try to remember this extra step when releasing nugets.
