### ISSUE TITLE
Additional net40 and net45 compiled Dlls

### ISSUE THREAD

**Issue by hsddeveloper201505** [angularsen/UnitsNet#334]
Hi,
your project is very useful and works great in our software, but i have to use only net 4.0 or net 4.5 compiled dlls.
Can you add additional compiled to your package?

regards
Stefan

**Comment by angularsen** [comment]
Hi, we are [targeting .NET 3.5 Client](https://github.com/angularsen/UnitsNet#build-targets) so I believe this should work for both 4.0 and 4.5 - although admittedly it's been a while since I tried. What errors are you getting trying to use this, and are you using the [nuget](https://www.nuget.org/packages/UnitsNet/) or are you building the UnitsNet .dll yourself?

**Comment by hsddeveloper201505** [comment]
I'm using the provided nuget package.
There are no errors using .NET 3.5 but we use the runtime 4.0 in our application. When we add an older compiled Dll, the older runtime will be additionally loaded and causes more memory usage and performance issues.

**Comment by angularsen** [comment]
I see, we are also targeting netstandard 1.0. Is that compatible with your .NET 4.5 requirement? It does require .NET Core 1.x SDK though.

I guess we can add the net40 target, I hadn't thought of the runtime argument you mention and I don't immediately see any downsides to this except bigger nuget download and longer compile time. I created a PR #335 for it, but I first need to understand whether netstandard 1.0 can cover this usecase or if there is actually a need for net40 in addition?

**Comment by hsddeveloper201505** [comment]
It doesn't work with the netstandard 1.0 out of the box, because the nuget package Manager always takes the .NET framework 3.5 instead of the netstandard 1.0. We are using the .NET 4.6.2 class library in all of our 200 projects in the solution and don't want to modify all the projects to take the netstandard 1.0 instead of the .Net Framework.
We are looking forward to change the projects to netstandard 2.0 in the future, but for now I have to use the .NET framework library.

**Comment by angularsen** [comment]
Ok, got it. I think I'm fine with adding net40, but I'll check with the other collaborators first to make sure. Let's continue the conversation in the PR.
