### ISSUE TITLE
Collaborators: Access to AppVeyor account

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#338]
@JKSnd @eriove @ferittuncer I figured you should also have access to the AppVeyor account so you are able to fix builds if necessary. Could you send me the email address for your appveyor account (if you have one) or the email you want to be registered with.

If you don't want access, that is also fine.

**Comment by JKSnd** [comment]
My appveyor account is linked to this GitHub account. Is giving access against GitHub user names possible? If not, we can try the email address that my GH account was created with.

**Comment by angularsen** [comment]
I can't seem to add github usernames, only emails or GitHub teams and I don't see an easy way to create a team for us collaborators without moving the repo over to a new GitHub organization.
So I guess I need email. 
If you don't want to post this publicly you can email me at andreas.larsen84@gmail.com .

**Comment by ferittuncer** [comment]
Please add me with this e-mail: `ferit@cryptolab.net`

**Comment by angularsen** [comment]
Done

>

**Comment by ferittuncer** [comment]
I verified that I can access.

**Comment by ferittuncer** [comment]
Shall we close this? @angularsen @eriove @JKSnd

**Comment by angularsen** [comment]
Sure, I still haven't given access to the other two, but at least they have been made aware of it now. It is optional after all.
