### ISSUE TITLE
Question: Why the need to have separate FromUnitToBaseFunc and FromBaseToUnitFunc?

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#347]
Just out of curiosity, why do we need to define separate definitions for FromUnitToBaseFunc and FromBaseToUnitFunc? I mean, we can just define one and then just reciprocate (1/x) the other?

**Comment by angularsen** [comment]
On the phone, but if I am not mistaken there are some conversions such as
for logarithmic units where this is not the case. However I guess we could
default to this behavior if only one of the functions are defined? This way
we can remove the duality for most units and keep it for the few units that
need it.

**Comment by gojanpaolo** [comment]
Just did a quick scan on the unit definitions and found cases where conversions to and from base units are not just a simple division.   I think it would be best to keep the separate definitions for FromUnitToBaseFunc and FromBaseToUnitFunc. It would be much simpler and straightforward that way instead of having "if common unit then reciprocate, else if special unit then must have separate definitions".

https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/PowerRatio.json
https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/Temperature.json
https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/AmplitudeRatio.json
