### ISSUE TITLE
Should we support operator overload: Pressure * Length = ForcePerLength ?

### ISSUE THREAD

**Issue by khanhlu2013** [angularsen/UnitsNet#348]

**Comment by angularsen** [comment]
On the phone, but sure, if we already have ForcePerLength and this is
something you would find useful then I say go ahead and add it 😊

**Comment by angularsen** [comment]
Hi, do you want to do a PR on this?

**Comment by khanhlu2013** [comment]
Hi Andreas!

I never do a PR before and don't have the time right now. Thank you for
asking.

**Comment by angularsen** [comment]
Alright, closing this then as we really want those who needs the feature to add it in order to grow the number of contributors and collaborators.
