### ISSUE TITLE
Crawlspace uses Units.NET

### ISSUE THREAD

**Issue by MartinEden** [angularsen/UnitsNet#349]
Hello, I am using Units.NET in a small open source app I wrote called [Crawlspace](https://bitbucket.org/MartinEden/crawlspace). I don't know whether you would consider it noteworthy enough to put in your README, but I thought I'd let you know in case you do!

**Comment by angularsen** [comment]
Hey @MartinEden , that is cool to hear and of course we'll include it. 
If you could please do a pull request on updating the README, just follow the convention of what is already there, and I'm happy to merge it in. Happy holidays ☃️

**Comment by MartinEden** [comment]
I have opened a PR [here](https://github.com/angularsen/UnitsNet/pull/359).

**Comment by angularsen** [comment]
PR merged.

**Comment by MartinEden** [comment]
Oops, there was a mistake in my PR. New PR here: https://github.com/angularsen/UnitsNet/pull/368

**Comment by eriove** [comment]
I've merged #368
