### ISSUE TITLE
Getting abbreviation list of a quantity

### ISSUE THREAD

**Issue by YektaMirkan** [angularsen/UnitsNet#354]
I am trying to bind abbreviation list of quatities to `combobox` `itemsource` property. But I am not able to do it. Because I couldn't find `abbreviations` property . In c# code I solved this problem with using `LINQ`. But now I need abbreviation list in xaml. So I can't use `LINQ` to get abbreviations from units. There is a way to achive this problem. Using converter class to convert units to abbreviations. But I need a base class otherwise I need to create a converter class for each unit. So these are the only ways that I could find. 
What do you think about base class or abbreviation list?
Or do you have any other solution to get abbreviation list of quatities ?

**Comment by angularsen** [comment]
I don't fully understand your example, but here are some pointers that may help you out:

Example converter app:
https://github.com/angularsen/UnitsNet#example-creating-a-unit-converter-app

Pull request on XAML binding to units using reflection:
https://github.com/angularsen/UnitsNet/pull/353

If you are able to achieve what you want with C#, then you should be able to do the same with XAML by using a view model property that calculates the combobox list content in C# and binding the XAML to it. I personally prefer this approach over complicated/specialized value converters.

Does this help?

**Comment by YektaMirkan** [comment]
I am able to get abbreviation list in xaml but I need to create a converter class for each unit. Because there isn't any base class for units. `Temperature.Units.ToList().Skip(1).Select(Temperature.GetAbbreviation).ToList()` 
I have solved the problem in this way. But I want to create a common converter class which can convert units to abbreviations without knowing unit type. I think this problem can only be solved by using base class otherwise I need to use reflection and it costs me a lot.

**Comment by angularsen** [comment]
Closing this in favor of #371. Help move that forward instead.
