### ISSUE TITLE
Add VolumeFlow

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#357]
Can we add [VolumeFlow](https://en.wikipedia.org/wiki/Volumetric_flow_rate) (Volume/Speed) to the library?
Let me know if we can then I'll submit a PR when I get some free time.
Thank you! :)

**Comment by ferittuncer** [comment]
Do you mean `Volume/Time`? If yes, we have `Flow` quantity.

**Comment by gojanpaolo** [comment]
Ahh yes. Volume/Time. Closing this issue. Thank you!

**Comment by angularsen** [comment]
Is VolumeFlow a more accurate naming or is Flow clear enough?

**Comment by gojanpaolo** [comment]
There is [MassFlow](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/MassFlow.json) so I thought the name would be VolumeFlow.

**Comment by ferittuncer** [comment]
@angularsen We use `Flow` and `MassFlow` too and at first we were confused too. Perhaps renaming it worth the effort.

**Comment by angularsen** [comment]
Ok then, I propose adding VolumeFlow (copy Flow and rename it) and obsoleting Flow so we can deprecate it. I've created #363 so someone can grab it.
