### ISSUE TITLE
Add MassFlux

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#358]
Can we add [MassFlux](https://en.wikipedia.org/wiki/Mass_flux) (Mass/Area/Time) to the library?
Let me know if we can then I'll submit a PR when I get some free time.
Thank you! :)

**Comment by angularsen** [comment]
I don't see why not. I have no idea how widely used it is, but seems to be a well established quantity. 😀

**Comment by gojanpaolo** [comment]
Great! Will submit PR a bit later.
We usually encounter it when multiplying Density and Velocity which becomes MassFlux.
The MassFlux can then be used to get MassFlowRate given an area or used as a factor to calculate another Density or Velocity.
