### ISSUE TITLE
Rename Flow to VolumeFlow

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#363]
To disambiguate it from MassFlow and more consistent naming.

- [ ] Mark all `Flow` units as obsolete via .json file (example: [TemperatureDelta.KelvinDelta](https://github.com/angularsen/UnitsNet/blob/431527d7ae761f789c101ffda73700b00772ff3b/UnitsNet/UnitDefinitions/TemperatureDelta.json#L105))
- [ ] Add `VolumeFlow` .json based on Flow (copied and renamed) 
- [ ] Run `generate-code.bat`

All obsoleted code will be addressed on next major version bump, as listed in #180 .

**Comment by gojanpaolo** [comment]
I'll start doing this. :)

**Comment by angularsen** [comment]
You can, but before this can be reviewed it should rebased on top of origin/master so that you don't include flow unit changes in the PR.

**Comment by gojanpaolo** [comment]
How do I do that? Sorry, kinda new to GitHub.

**Comment by angularsen** [comment]
In git command line, something like this:
```
$ (someotherbranch): git checkout -b mynewbranch origin/master
$ (mynewbranch): ...do stuff...
$ (mynewbranch): git commit
$ (mynewbranch): git push
```

Then create PR from mynewbranch on your fork.

**Comment by gojanpaolo** [comment]
I just did something like this...
$ (AddMoreFlowUnits): git checkout -b RenameFlowToVolumeFlow origin/master

but it didn't get where I left off from AddMoreFlowUnits

**Comment by gojanpaolo** [comment]
So I did the tasks for this issue but branching from PR https://github.com/angularsen/UnitsNet/pull/361 

I guess I'll just wait for that PR to be accepted before I submit PR for [RenameFlowToVolumeFlow branch](https://github.com/gojanpaolo/UnitsNet/tree/RenameFlowToVolumeFlow) ?

**Comment by angularsen** [comment]
Ah I see. 
Easiest route: Wait until the first branch is merged into master, then branch off master to do the rename.
Harder route: Branch off AddMoreFlowUnits branch now, do the rename, push the branch and create PR with a note saying this should not be merged until the first PR is merged. After it is merged, rebase on top of orgin/master to effectively get to the same state as the easy route, then force push that to update the PR and notify it is ready for review.

Frankly, the latter option does not gain much and adds a lot more friction so I would go with the easy route.

**Comment by gojanpaolo** [comment]
Alright. Let's just do the Easy route. It's quick to do the rename anyway :)
