### ISSUE TITLE
Add FromDiameter to Area.extra

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#377]
Can we add something like:
```
public static Area FromDiameter(Length diameter)
{
	return Math.PI * diameter * diameter / 4;
}
```

I was hesitant to suggest this before but I saw similar functions for [PowerRatio](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/Quantities/PowerRatio.extra.cs) which uses some kind of computation to convert from one unit to another.

**Comment by angularsen** [comment]
Sure, we have several of these from before so I'm fine with this.

**Comment by angularsen** [comment]
On second thought, maybe it should be named `FromCircleDiameter()` to be very clear what is about? At least I find that slightly more informative.

**Comment by angularsen** [comment]
...aaand, consider adding the radius variant while at it. :-)

**Comment by gojanpaolo** [comment]
You bet! :)
