### ISSUE TITLE
Cannot Parse Teaspoons

### ISSUE THREAD

**Issue by dotn8** [angularsen/UnitsNet#390]
Cannot Parse Teaspoons

I'm writing a recipe app. It needs to use US teaspoons; I never want to use metric teaspoons. However, when I go to parse a teaspoon, I get an exception:

	// Tablespoons are parsable
    var a = Volume.Parse("1 tablespoon", CultureInfo.GetCultureInfo("en-US"));
	
	// This throws: UnitsNet.AmbiguousUnitParseException:
	// 'Cannot parse 'teaspoon' since it could be either of these: 29, 34'
    var c = Volume.Parse("1 teaspoon", CultureInfo.GetCultureInfo("en-US"));

There are multiple teaspoon units, so I tried to figure out which ones had "teaspoon" as their abbreviation:

    var unitSystem = UnitSystem.GetCached(CultureInfo.GetCultureInfo("en-US"));
    
	// VolumeUnit.Teaspoon is obsolete, but I just wanted to check the result from this.
    // This returns 9 elements, which are the abbreviations for teaspoons.
    var teaspoonAbbreviations = unitSystem.GetAllAbbreviations(VolumeUnit.Teaspoon);
    
	// This returns an array with a single element, and that element is an empty string.
    var usTeaspoonAbbreviations = unitSystem.GetAllAbbreviations(VolumeUnit.UsTeaspoon);
    
	// This returns 9 elements, which are the abbreviations for teaspoons. This is what I'd expect.
    var metricTeaspoonAbbreviations = unitSystem.GetAllAbbreviations(VolumeUnit.MetricTeaspoon);

So there are two aspects to this issue:

- The obsolete `Teaspoon` unit has abbreviations but the new `UsTeaspoons` unit does not. This means that `UsTeaspoon` is unparsable.
- Both `Teaspoon` and `MetricTeaspoon` have the same exact abbreviations, which makes both of them unparsable.

There needs to be a way to pick which type of teaspoon to use by default in my application.

**Comment by gojanpaolo** [comment]
[Teaspoon](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/Volume.json#L274) and [MetricTeaspoon](https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/UnitDefinitions/Volume.json#L355) does have the same abbreviations. We can fix that by removing the abbreviations in Teaspoon since it is obsolete anyway. That would solve the exception when parsing.

**Comment by gojanpaolo** [comment]
Interesting. We also do have the same scenario where we just want to use UsSurveyFeet and never the international Feet. At first we created a custom LengthParser (you might also want to do the same if your issue needs to be fixed asap) to check if it is one of the Feet abbreviations and return them as UsSurveyFeet. Though we removed the parsing feature in our app later on since its not really needed.

You might also want to see https://github.com/angularsen/UnitsNet/issues/132 which talks about ambiguous unit abbreviations.

Also https://github.com/angularsen/UnitsNet/issues/134 for separating down Teaspoon and Tablespoon to Us and Metic.

**Comment by dotn8** [comment]
@gojanpaolo thank you! I chose to use a custom parser. I wrote a generic one so that we only need one to write it once instead of once for `Length`, once for `Volume`, once for `Mass`, etc.

I'm going to close this issue. Here's my code for future reference:

    // Here's how to use this code:
    var customParser = new CustomUnitParser<Volume, VolumeUnit>();
    customParser.Prefer(VolumeUnit.UsTeaspoons);
    var result = customParser.Parse("1 tsp"); // this works now


    /// <summary>
    /// A way to parse units while preferring certain units over others. Useful for when multiple units have the same abbreviations.
    /// </summary>
    /// <typeparam name="TUnitType">The unit type, e.g., <see cref="Volume"/></typeparam>
    /// <typeparam name="TUnitEnum">The unit type enum, e.g. <see cref="VolumeUnit"/></typeparam>
    public class CustomUnitParser<TUnitType, TUnitEnum> : ICustomUnitParser
        where TUnitEnum : struct, IComparable, IFormattable
    {
        /// <summary>
        /// The unit system to use.
        /// </summary>
        private UnitSystem _unitSystem;

        /// <summary>
        /// The type of <see cref="TUnitType"/>.
        /// </summary>
        private Type _unitType;

        /// <summary>
        /// The list of abbreviations that have a preferred unit.
        /// </summary>
        private readonly List<string> _preferredAbbreviations = new List<string>();

        /// <summary>
        /// Constructs a <see cref="CustomUnitParser{TUnitType, TUnitEnum}"/>.
        /// </summary>
        /// <param name="unitSystem">The unit system to use, or null. If null, the unit system for the current culture is used.</param>
        public CustomUnitParser(UnitSystem unitSystem = null)
        {
            if (unitSystem == null)
            {
                unitSystem = UnitSystem.GetCached(CultureInfo.CurrentCulture);
            }

            _unitType = typeof(TUnitType);
            _unitSystem = unitSystem;
        }

        /// <summary>
        /// Makes this parser prefer <see cref="unit"/> over other <see cref="TUnitEnum"/> units.
        /// </summary>
        /// <remarks>
        /// For example, to prefer US teaspoons over metric teaspoons, call it like this:
        /// <code>
        /// Prefer(Volume.UsTeaspoons);
        /// </code>
        /// </remarks>
        /// <param name="unit">The unit to prefer</param>
        public void Prefer(TUnitEnum unit)
        {
            var currentAbbreviations = _unitSystem.GetAllAbbreviations(unit);

            // Add to the list of abbreviations that we'll have to insert "force" in front of.
            // We're going to insert the word "force" in front of the unit's abbreviation to force UnitsNet to parse the preferred unit.
            _preferredAbbreviations.AddRange(currentAbbreviations);

            _unitSystem.MapUnitToAbbreviation(unit, currentAbbreviations.Select(abbrev => $"force{abbrev}").ToArray());
        }

        /// <summary>
        /// Parses the specified string
        /// </summary>
        /// <param name="str">The string to parse</param>
        /// <returns>The parsed unit</returns>
        public TUnitType Parse(string str)
        {
            // Insert the word "force" in front of the unit's abbreviation, to force UnitsNet to parse the preferred unit.
            foreach (var preferredAbbreviation in _preferredAbbreviations)
            {
                if (!string.IsNullOrEmpty(preferredAbbreviation) && str.IndexOf(preferredAbbreviation) >= 0)
                {
                    str = str.Replace(preferredAbbreviation, "force" + preferredAbbreviation);
                    break;
                }
            }

            // Call the Parse method on the unit type.
            // So for example if TUnitType is Length, then this would call Length.Parse(str).
            var result = (TUnitType)_unitType
                .GetMethod("Parse", new[] { typeof(string) })
                .Invoke(null, new object[] { str });
            return result;
        }

        /// <summary>
        /// Determines if this custom parser can parse the specified type of unit
        /// </summary>
        /// <param name="type"></param>
        /// <returns>True if the unit can be parsed, false otherwise</returns>
        public bool CanParse(Type type)
        {
            return type == _unitType;
        }

        /// <summary>
        /// Non-generic overload of <see cref="Parse"/>
        /// </summary>
        /// <param name="str">The string to parse</param>
        /// <returns>The parsed unit</returns>
        object ICustomUnitParser.Parse(string str)
        {
            return this.Parse(str);
        }
    }

    /// <summary>
    /// Non-generic interface that <see cref="CustomUnitParser{TUnitType,TUnitEnum}"/> implements,
    /// so that you can for example have a list of custom unit parsers.
    /// </summary>
    public interface ICustomUnitParser
    {
        /// <summary>
        /// Parses the specified string
        /// </summary>
        /// <param name="str">The string to parse</param>
        /// <returns>The parsed unit</returns>
        object Parse(string str);

        /// <summary>
        /// Determines if this custom parser can parse the specified type of unit
        /// </summary>
        /// <param name="type"></param>
        /// <returns>True if the unit can be parsed, false otherwise</returns>
        bool CanParse(Type type);
    }
