### ISSUE TITLE
Relative tolerance instead of absolute tolerance

### ISSUE THREAD

**Issue by ferittuncer** [angularsen/UnitsNet#391]
As discussed in #350 we are planning to implement relative tolerance and use a standard relative tolerance value to test units instead of using a different absolute tolerance value for each unit.

Benefits are:
 - Standardized precision
 - Shorter source-code

We can implement it similar to [MathNet.Numerics.Precision.Equality](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Precision.Equality.cs)

**Comment by tmilnthorp** [comment]
I think this can be closed now unless anyone has any objections?

**Comment by angularsen** [comment]
Yup!
