### ISSUE TITLE
Request release 3.88

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#392]
@angularsen Could we please release 3.88? :)
I'm not sure if it can be done via a PR so I just created an issue.
Thank you!

**Comment by ferittuncer** [comment]
Will do it tomorrow, added to my todo list.

**Comment by gojanpaolo** [comment]
Awesome! Thank you! :)

**Comment by angularsen** [comment]
Awesome, thanks @ferittuncer .
That was one huge release list 😆
