### ISSUE TITLE
Area: Add SquareUsSurveyFeet

### ISSUE THREAD

**Issue by gojanpaolo** [angularsen/UnitsNet#396]
Will submit PR over the weekend. :)

**Comment by angularsen** [comment]
Sounds good to me! No need to create an issue first though, unless you are unsure if it will be accepted or needs some discussion in advance. We usually accept new units of existing quantities, but entirely new quantities may be worth discussing first to avoid duplicates and to avoid quantities with just a single unit.

I'll close this one and then you just submit the PR later.
