### ISSUE TITLE
How to extend an existing unit?

### ISSUE THREAD

**Issue by dschuermans** [angularsen/UnitsNet#412]
Hello,

We have a use case in which we need to have MegaNewtonPerMeter in the ForcePerLength unit.

I'm also looking for a unit which supports MegaNewtonPerRadian but I've been unable to find it in any of the existing units.

In my opinion, the documentation available on extending with custom units is a bit short and unclear.
So i'd like to know the best way to approach this.

Do we fork and submit a PR with the new / updated units?
Can we directly create new units in our project and use them? As I can tell, there's nothing really "special" about the existing unit classes.

This is my first time working with your library, so please excuse my dumb questions :)

Kind regards,

Dirk

**Comment by angularsen** [comment]
Hi Dirk, thanks for reaching out. 

I assume you maybe stumbled onto this article?
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units

This is not a good article, in fact it is merely full of old rambling thoughts. I have updated it now to be more clear on why that page exists.

Instead, you should look at this:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

Hopefully that description is easier for you to follow. It should address your questions already.
Please let me know if you still are not sure about this, we are happy to help! :-)

**Comment by dschuermans** [comment]
Hey Andreas,

Thanks for the feedback. We'll fork the repo and submit a PR when ready.

Regarding the MegaNewtonPerRadian, any thoughts on what the unit should be?
It's used in [Rotational Stiffness](https://en.wikipedia.org/wiki/Stiffness#Rotational_stiffness)
Maybe i looked over an existing unit which only needs an additional unit specification added...

**Comment by dschuermans** [comment]
On another note, are there any other requirements besides Powershell 3.0?
We're using VS2015 and i'm unable to load the projects:

```
D:\sources\UnitsNet\UnitsNet\UnitsNet.NetStandard10.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet\UnitsNet.NetStandard10.csproj

D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet\UnitsNet.Serialization.JsonNet.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet\UnitsNet.Serialization.JsonNet.csproj

D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet\UnitsNet.Serialization.JsonNet.Signed.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet\UnitsNet.Serialization.JsonNet.Signed.csproj

D:\sources\UnitsNet\UnitsNet\UnitsNet.NetStandard10.Signed.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet\UnitsNet.NetStandard10.Signed.csproj

D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet.Tests\UnitsNet.Serialization.JsonNet.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet.Serialization.JsonNet.Tests\UnitsNet.Serialization.JsonNet.Tests.csproj

D:\sources\UnitsNet\UnitsNet.Tests\UnitsNet.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\sources\UnitsNet\UnitsNet.Tests\UnitsNet.Tests.csproj

```

Running Build.bat also fails:

![image](https://user-images.githubusercontent.com/6634696/36969338-7e4fe438-2065-11e8-8e1e-882015650f33.png)

**Comment by angularsen** [comment]
Ah, yes, we require Visual Studio 2017. The community edition is free. I'll update the notes.

**Comment by angularsen** [comment]
Updated: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'm not 100% sure, but I believe these are our dependencies:

Requirements:
* PowerShell 3.0
* Visual Studio 2017 (the Community edition is free), with these components:
  * .NET Core SDK 1.1 or greater (`netstandard` targets)
  * Optional: Windows 10 SDK 10.0.16299.0 for UWP C#, VB, JS and for C++ (`WindowsRuntimeComponent` target)

**Comment by dschuermans** [comment]
@angularsen - I managed to load the projects etc and build the whole thing. However, getting the tests to run is another thing...
I think when installing VS2017, it automatically grabbed the latest .NET Core version (being 2.0.5) and the unit tests expect 1.1.2:

```
[05/03/2018 14:13:45 Error] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.1.2'.
```

As i have no real experience with .NET core yet, I have no idea how to resolve this issue...
Any help is appreciated!

**Comment by dschuermans** [comment]
Question: Should i commit the generated code? My gut feeling tells me not to  :)

**Comment by dschuermans** [comment]
Here's the first PR: https://github.com/angularsen/UnitsNet/pull/413

**Comment by angularsen** [comment]
Continuing the conversation in the PR.
Thanks for posting the build error and fix, I have these installed locally:
- .NET Core SDK 1.1.7 (x64)
- Microsoft .NET Core SDK - 2.1.4 (x64)

It seems you need 1.x in addition to 2.x right now, but since 2 is now stable we should probably move on to the 2.x instead.

**Comment by angularsen** [comment]
Updated: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

**Comment by dschuermans** [comment]
And here's the second PR :)

https://github.com/angularsen/UnitsNet/pull/414
