### ISSUE TITLE
Write JSON serialization tests against two versions of UnitsNet.Serialization.JsonNet

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#417]
To catch future breaking changes in UnitsNet, as seen in #416.

The json serialiation tests should run against two `UnitsNet.Serialization.JsonNet` dlls:
- The `UnitsNet.Serialization.JsonNet` project, which is built and run in the tests
- `v1.3.0` or some other "old" version that currently works against latest `UnitsNet`, but may later stop working

I'm not exactly sure how, but it seems you can side-load two versions of a dll and call them separately:

https://stackoverflow.com/questions/42715564/using-2-different-versions-of-the-same-dll
https://devnet.kentico.com/articles/referencing-multiple-versions-of-the-same-assembly-in-a-single-application
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/codebase-element

Alternatively, maybe simpler, is to have two test projects with the same test code and different references to `UnitsNet.Serialization.JsonNet`.

**Comment by gojanpaolo** [comment]
I could try doing this :)

**Comment by angularsen** [comment]
Cool!
