### ISSUE TITLE
Units property should not include Undefined value

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#437]
https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/GeneratedCode/Quantities/Length.g.cs#L164

Similar for all quantities, Length only chosen as an example.

It doesn't make sense to include the `LengthUnit.Undefined = 0` value, since it is not meant to be used. UnitsNet will throw exception if you try to use this value for anything in methods accepting a unit value, as the intent is to help you catch bugs where you forgot to initialize the value such as when deserializing data.

**Comment by bplubell** [comment]
If we remove `Undefined`, should we set the first value to be a value other than `0` (like `Centimeter = 1` instead of `Centimeter = 0`.)?

Is this considered a breaking change, since someone may be be doing their own checking for something like `LengthUnit.Undefined`?

**Comment by angularsen** [comment]
Updated link:
https://github.com/angularsen/UnitsNet/blob/5f2b075eaa8d8f15d294214e9ab61c3f45256f10/UnitsNet/GeneratedCode/Quantities/Length.g.cs#L161-L164

As you can see, I didn't mean to remove the enum value, but rather to not include it in the list of `LengthUnit[] Length.Units { get; }` property. Basically just filter out that particular value from the array.

The motivation for this change, which I forgot to mention in the description, is that some people complained `Undefined` was listed when they were enumerating all Length units and I agree it's not intuitive and I don't see any purpose in keeping that value.

I would not consider this a breaking change, as  I rather consider it a bug that the value was included to begin with.

**Comment by bplubell** [comment]
Ah, that does make more sense. I am submitting a PR to do this - I just took your suggested solution.
