### ISSUE TITLE
UnitsNet.From(x,UnitsNet.Units.LengthUnit.Meter) treats input as inches.

### ISSUE THREAD

**Issue by aurimasmb** [angularsen/UnitsNet#441]
UnitsNet.From(x,UnitsNet.Units.LengthUnit.Meter) treats input values as inches, not meters.

**Comment by angularsen** [comment]
Hm, I can't reproduce: https://dotnetfiddle.net/26FycH

What version are you referencing?

**Comment by angularsen** [comment]
Did you see my example?

**Comment by tmilnthorp** [comment]
I also can not reproduce

**Comment by tmilnthorp** [comment]
Close?
