### ISSUE TITLE
ElectricAdmittance and ElectricConductance are the same unit

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#443]
It seems that ElectricAdmittance and ElectricConductance are the same unit, but I wanted to double check with everyone before removing anything.

**Comment by angularsen** [comment]
Their difference lies in DC (direct current) vs AC (alternating current), if I recall my electronics basics right.

http://engrhub.blogspot.com/2015/07/impedance-resistance-reactance.html

**Comment by tmilnthorp** [comment]
Interesting. Thanks!
