### ISSUE TITLE
Should unit tolerance be a % rather than fixed at 1e-5?

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#450]
I noticed that when adding the Femto and Peta prefixes to PowerDensity that the tests fail. 

[1 W/m³].As( PowerDensityUnit.FemtowattPerCubicMeter ) is calculating 1 / 1e-15 = 999999999999999.87

Obviously this isn't within 1e-5 of 1e15 (actual difference is 0.125).

For a number this large that difference is 0.00000000000001.25% :)

I know that I could override the tolerance in the tests, but perhaps we should think about changing the tolerance across the board? For very small numbers, the opposite is true: 1e-5 may be too large.

**Comment by gojanpaolo** [comment]
See Relative tolerance instead of absolute tolerance #391

**Comment by tmilnthorp** [comment]
Ah thank you - I looked through the list but must have missed this. I will close this and reference that one.
