### ISSUE TITLE
Proposing @tmilnthorp as collaborator

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#452]
@eriove @JKSnd @ferittuncer Trying once more, not sure if you are getting the notifications in gitter. I would like to invite @tmilnthorp as collaborator. He's been very active lately and produced quality PRs from the start.
Vote yes/no please?

I'm leaving a deadline for 3 days, June 27, or I will assume you are positive :-)

**Comment by JKSnd** [comment]
The gitter is giving me 404's when I try to hit the Collaborators conversation...

regardless, I'm a +2 on that.

**Comment by angularsen** [comment]
Weird, logged in with the right user?
You're not missing much action though 😆

**Comment by eriove** [comment]
Sounds good!

I haven't contributed anything in a long time. Feel free to remove me from the list of collaborators if you'd like. I don't mind staying on the list though

**Comment by angularsen** [comment]
@eriove No worries, I expect the interest in the lib to wane as one is maybe not using it much and then maybe the interest picks up again later. I would very much keep you around even if you don't expect to be active anytime soon!

**Comment by angularsen** [comment]
Welcome aboard @tmilnthorp 😄  🎉 This will be great!
