### ISSUE TITLE
Change localisation of LengthUnit enum

### ISSUE THREAD

**Issue by tomaustin700** [angularsen/UnitsNet#466]
Hi,

We are using LengthUnit in our application as the ItemSource for a ComboBox in a WPF application, the enum has its text in American English (Centimeter, Micrometer, etc) however we would like it in British English (Centimetre, Micrometre, etc). Is there any way to change this via localisation? I feel like there isn't but thought i'd ask anyway.

Thanks

**Comment by tmilnthorp** [comment]
We currently have a propsal (#397) to do so, but it is not yet implemented. If I were to implement this, would you help go through the units to specify the en-GB versions?

**Comment by tomaustin700** [comment]
Hi,
I would be happy to help go through the units for en-GB. Let me know what you would like and how you would want it and I'll get it done.

Thanks!

**Comment by angularsen** [comment]
I'll close this issue, please follow up in #397 instead.
