### ISSUE TITLE
Length.Parse for string with points units

### ISSUE THREAD

**Issue by bhasden** [angularsen/UnitsNet#471]
I've tried to track down a solution to this since I'm sure I'm missing something, but so far haven't found anything. I'm using Length.Parse to parse strings with various units. The issue comes in when the string units is points. Because there are two different types of points (DTP point and printer point) with the "pt" abbreviation I end up getting the `Cannot parse '{unitAbbreviation}' since it could be either of these: {unitsCsv}` exception. I've worked around the issue for now with some hacks, but I'm curious what the recommended pattern for parsing something like "1pt" would be.

Thanks in advance.

**Comment by gojanpaolo** [comment]
Parsing ambiguous unit abbreviations are advised to be handled by the client (you :D) since handling it may be domain-specific.
Please see https://github.com/angularsen/UnitsNet/issues/390 for a similar discussion as well as related links. OP was also generous enough to share his solution (generic custom parser).

**Comment by bhasden** [comment]
Thank you. That's very useful information and should resolve my issue.

**Comment by gojanpaolo** [comment]
You're welcome! :)

**Comment by angularsen** [comment]
FYI, I added a new issue after reading this:
[AmbiguousUnitException lists enum integer values instead of enum names · Issue #472 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/issues/472)

**Comment by angularsen** [comment]
And this gotcha section in the README:
https://github.com/angularsen/UnitsNet/blob/master/README.md#gotcha-ambiguousunitparseexception
