### ISSUE TITLE
AmbiguousUnitException lists enum integer values instead of enum names

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#472]
![image](https://user-images.githubusercontent.com/787816/45251822-ff7bf400-b34c-11e8-94d7-ee00e9c8e507.png)

This message is not particularly helpful, it would be better if it read
`Cannot parse "pt" since it could be either of these: DtpPoint, PrinterPoint`

Note the change from single quotes ' to double quotes " too, since we are talking about C# strings here.

**Comment by bplubell** [comment]
I can try and improve this. Working on a PR now.
