### ISSUE TITLE
Having a Unit.SI

### ISSUE THREAD

**Issue by Mobz87** [angularsen/UnitsNet#519]
I find myself having a lot of:

```
entropy.JoulesPerKelvin
enthalpy.JoulesPerKilogram
pressure.Pascals
```

And a lot of:

```
MassFlow.FromKilogramsPerSecond(...)
VolumeFlow.FromCubicMetersPerSecond(...)
Power.FromWatts(...)
```
in my code.

I would love at have a option to not have to write the long SI-units (fx. KilogramsPerSecond).

If I could write instead:

```
entropy.SI
enthalpy.SI
pressure.SI
```

```
MassFlow.FromSI(...)
VolumeFlow.FromSI(...)
Power.FromSI(...)
```

Then my code would look much more clean and there would be less errors.
What do you think of this idea? And how difficult would it be to implement?

**Comment by tmilnthorp** [comment]
We were discussing having a UnitSystem class where you would define the 7 base units (as well as have a predefined SI system), and allow From and As to take a UnitSystem. This would allow you to convert or define everything in a consistent system of your choosing. However it is not possible at this time.

The auto generated operator overloads will need to be worked on first to get it to work generically.

**Comment by angularsen** [comment]
What @tmilnthorp said. When we (read @tmilnthorp ) extends with a new `UnitSystem` class, and we have a default instance for SI base units, then your examples above makes perfect sense to me.

`Mass.FromSI(1)` being equivalent to `Mass.From(1, UnitSystem.SI)` or perhaps `new Mass(1, UnitSystem.SI)` and maybe even defaulting to SI like this `new Mass(1) // 1kg`?

**Comment by angularsen** [comment]
#524 on the way already, wow.

**Comment by tmilnthorp** [comment]
Only works for base (single dimension of 1) units right now of course. Need to add all the operator overloads to allow derived unit conversion

**Comment by Mobz87** [comment]
You guys are awesome!

`new Mass(1) // 1kg` that will be a great new option!

**Comment by tmilnthorp** [comment]
I will look at that next. Right now it's just a system definition. I'd like to add a UnitSystem overload to the From/As methods.

**Comment by angularsen** [comment]
Closing this issue in favor of #547 on v4 branch.
