### ISSUE TITLE
Serialization in human readable form

### ISSUE THREAD

**Issue by Batboa** [angularsen/UnitsNet#555]
I have a use case where we want  to serialize Length and other IQuantity, but instead of having them in the format that is currently provided of `"{\n  \"Unit\": \"MassUnit.Kilogram\",\n  \"Value\": 10.0\n}";` We want to keep the serialized version in a human readable format of `10 kg`. Since the `ToString ` and `Parse` functionality are already great it should be easy to leverage those for this. Example of https://github.com/Batboa/UnitsNet/commit/66553b5664894a020150e26879737357519321a6.

**Comment by Batboa** [comment]
I've very willing to work with the maintainers of this project to get this commit into a format this fits what you want for this project.

**Comment by angularsen** [comment]
Hi, this could definitely work for most quantities and units. However, there are several units where you would get exceptions due to either ambiguous unit abbreviations (f.ex. `Length.DtpPoint` and `.PrinterPoint`) or missing unit abbreviations (f.ex. `Ratio.DecimalFraction`).

```csharp
var cm = Length.FromCentimeters(1);
Console.WriteLine(cm.ToString(LengthUnit.DtpPoint)); // 28.35 pt
Console.WriteLine(cm.ToString(LengthUnit.PrinterPoint)); // 28.45 pt

var fiftyPercent = Ratio.FromPercent(50);
Console.WriteLine(fiftyPercent.ToString(RatioUnit.DecimalFraction)); // 0.5
Console.WriteLine(fiftyPercent.ToString(RatioUnit.PartPerMillion)); // 500,000 ppm
```

**Comment by Batboa** [comment]
Is the missing unit abbreviation an actual issue? It seems that the serializer I proposed will maintain the existing behavior of a units `Parse` method. So if there exists a unit that does not have an abbreviations like in your example of a `DecimalFraction` for `Ratio` the value will serialize and deserialize properly. Then if an abbreviation is required and is missing an error will be thrown. I will add tests to display this behavior.

As for ambiguous unit abbreviations the user of the API will need to provided some type of object that contains the priority unit type in case of conflict. I'll push an example of a way this could be done to my project and open a PR.

**Comment by tmilnthorp** [comment]
The purpose of serialization is to store or transport data. Being human-readable is not the goal. Perhaps we can help more if we understand what you are trying to achieve?

**Comment by angularsen** [comment]
I agree, I don't fully understand the motivation for this kind of serialization. It would help to know more what you want to accomplish.

As mentioned, serialization is typically about storing in a representation that is robust to future changes and should be machine readable. I don't consider using abbreviations robust, we have several examples of changing our minds or fixing errors in abbreviations in the past. Abbreviations are also different for different languages - so I assume you want to use Invariant culture?

Then there is the problem of ambiguous unit abbreviations where units of the same quantity can have the same abbreviation, or possibly even units of different quantities too although I can't think of an example off the top of my head.

This simply feels like the wrong solution to an already well-solved problem, but please, maybe I am just missing a good use case for this so I'm all ears to hear you out.

Best,
Andreas

**Comment by Batboa** [comment]
Our reason for a different type of serialization is for use in a web api. Internally we want to use UnitsNet, but when returning an object that contains multiple units to the api consumer, the consumer doesn't want a specialized contract for the json of a unit. They want the representation that can be read using any technology they choose.

**Comment by angularsen** [comment]
Thanks for explaining. You should be able to use UnitsNet internally without any problems, and choose whatever representation makes sense to the customer facing web API - just as you already demonstrated in your PR. 

It is very possible that in your particular case it makes sense to return human readable strings in the API, but I think this is a special case and not something I would generally recommend. Therefore I would also not provide this implementation out of the box, sorry! Thanks for sharing the solution though.
