### ISSUE TITLE
Nuclear "Reactivity" Unit (conversion involves ratio of base unit)

### ISSUE THREAD

**Issue by trb5016** [angularsen/UnitsNet#559]
I'm trying to add a [Reactivity Unit](https://ansn.iaea.org/Common/documents/Training/TRIGA%20Reactors%20(Safety%20and%20Technology)/chapter2/physics119.htm) used by nuclear engineers to determine criticality of a reaction.

The base unit is "k-effective"  and another unit is "Rho"

I'm trying to define "Rho" as:
```
    {
      "SingularName": "Keffective",
      "PluralName": "Keffective",
      "FromUnitToBaseFunc": "x",
      "FromBaseToUnitFunc": "x",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "keff" ]
        }
      ]
    },
    {
      "SingularName": "Rho",
      "PluralName": "Rho",
      "FromUnitToBaseFunc": "1/(1-x)",
      "FromBaseToUnitFunc": "(x-1)/x",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "ρ" ]
        }
      ]
    }
```

With the UnitTest being:
`protected override double RhoInOneKeffective => 0;`

But the unit test fails because:
`    UnitsNet.Tests.CustomCode.ReactivityTests.FromValueAndUnit [FAIL]
      Values are not equal within tolerance: 1E-05
Expected: 1
Actual: NaN`

I *think* I've set the definition correctly, and it's failing because, looking at the test cases, I think it's trying to test for "Rho=1" which is NaN, and then when it's trying to loop back it gets messed up and fails the test.

Any insight would be appreciated: 1) Is this just not possible to do, or 2) have I defined the unit incorrectly.

**Comment by trb5016** [comment]
Yep, I agree the non-continuity is the problem.  I actually think the unit is working properly and as expected, it's just all the test code gets unhappy because it's using '1' as the test case.  I thought about just tweaking my projects build scripts to not test this specific unit, but that feels unclean haha.

For now, I've changed the "Reactivity" base unit to 'rho', and defined a few others I need (including pcm) and just created separate functions for converting between keff and rho.

(From the technical perspective, while you can equate rho and keff to each other, it's practically rare that it needs done, because while they're both "reactivity" they're typically used for referring to totally separate calculations)

Thanks for looking at it.  If you want to keep this open to see if anyone has ideas, that would be cool, but I'm fine closing it because I recognize the obscurity of the issue.

**Comment by angularsen** [comment]
Well, my first ideas are along the lines of:

1. Add option to bypass tests for this particular unit.
2. Add option in codegen scripts to choose a different test value than `1` in our `.json` definitions, something like this:
```json
  {
      "SingularName": "Keffective",
      "PluralName": "Keffective",
      "FromUnitToBaseFunc": "x",
      "FromBaseToUnitFunc": "x",
      "TestFieldValue": 2,
      "TestFieldName": "RhoInTwoKeffective"
  }
```

Then the generated field would use the given name, and you set a new correct value:
```c#
protected override double RhoInTwoKeffective => -1;
```

Then generated tests would be updated to use new value `2`, like this one:
```c#
        [Fact]
        public void MeterPerSecondSquaredToAccelerationUnits()
        {
            Acceleration meterpersecondsquared = Acceleration.FromMetersPerSecondSquared(2);
        }
```

Could that work? Might not require too much work and is hopefully generic enough to cover future, similar challenges.

**Comment by tmilnthorp** [comment]
Why not just make an overridable property for the ToUnit tests that is the value to convert from? Default is one. No extra json necessary.

**Comment by angularsen** [comment]
I like it

**Comment by angularsen** [comment]
The only drawback is naming of field says PerOneMeter etc. I can live with that.

**Comment by trb5016** [comment]
I like tmilnthorp's idea too.  There's been instances in other situations where I wanted to change the test value from '1' because it makes it a "better" check, so that would be handy for that too.

I don't think the naming would be much of an issue since 99% of the time it will still be PerOne[unit].

Thank you both for your ideas.  I'll close this out.
