### ISSUE TITLE
Serialization of array of units does not work

### ISSUE THREAD

**Issue by dschuermans** [angularsen/UnitsNet#565]
Hey there,

Much to my surprise, the UnitsNetJsonConverter can't handle serializing an array of units to JSON.

Unit test which produces this issue:

```
JsonSerializerSettings settings = new JsonSerializerSettings()
            {
                Converters = new[]
                {
                    new UnitsNetJsonConverter(),
                }
            };

Length single = Length.FromMeters(1);

string jsonSingle = JsonConvert.SerializeObject(single, settings);

Assert.IsNotNull(jsonSingle);

Length[] multiple = new[] {Length.FromMeters(2), Length.FromMillimeters(3), Length.FromCentimeters(2)};

string jsonMultiple = JsonConvert.SerializeObject(multiple, settings);

Assert.IsNotNull(jsonMultiple);
```

It fails in `GetPrivateInstanceField` of the UnitsNetJsonConverter

Any idea's?

**Comment by dschuermans** [comment]
Managed to get it working, but need to refactor it a bit to make it more clean

**Comment by dschuermans** [comment]
See PR #566

**Comment by dschuermans** [comment]
@angularsen it's the compatibility project thats failing the UT. Am i missing something?

**Comment by angularsen** [comment]
Can only answer briefly right now, but yes the compatibility project is a
bit special. If I recall correctly it references an old version of UnitsNet
(3.x something I believe), in order to test that the latest serialization
code works with older versions of UnitsNet. Maybe your change introduced
some assumptions about UnitsNet internal structure that does not exist in
older UnitsNet versions?

I can take a closer look later.

**Comment by dschuermans** [comment]
> Can only answer briefly right now, but yes the compatibility project is a bit special. If I recall correctly it references an old version of UnitsNet (3.x something I believe), in order to test that the latest serialization code works with older versions of UnitsNet. Maybe your change introduced some assumptions about UnitsNet internal structure that does not exist in older UnitsNet versions? I can take a closer look later.

Yes, the compatibility project indeed references the older nuget package and it links to the same UT as the conversion project. Since I changed the functionality of the converter itself, the UT in the compatibility project does not have this change so it fails :(

**Comment by angularsen** [comment]
Great, will you do another PR on it?

**Comment by dschuermans** [comment]
> Great, will you do another PR on it? I see you closed the first one.

Well, I'd need to sort out the issue with the compatibility project's UT failing, otherwise the build fails...

**Comment by angularsen** [comment]
Any progress here?

**Comment by dschuermans** [comment]
Nope, don't have time left after work & renovations at home i'm afraid :(

**Comment by angularsen** [comment]
No problem, I'll close this issue for now just to clean up the issue list. Please reopen if you pick it up later.
