### ISSUE TITLE
Unit deserialization does not work when unit or value are in lowercase

### ISSUE THREAD

**Issue by dschuermans** [angularsen/UnitsNet#568]
When providing a json such as this:

`{ "unit": "LengthUnit.Meter", "value": 12 }`

The `TryDeserializeIComparable` function fails because it attempts to find "Unit" and "Value" keys on the JToken.
JToken appears to be case sensitive so another way around it is to cast JToken to JObject and then use `.GetValue(nameofValueUnit.Unit), StringComparison.OrdinalIgnoreCase)`as per https://stackoverflow.com/questions/49886411/json-net-jtoken-keys-are-case-sensitive?noredirect=1&lq=1

Will post fix soon as i'm working on it right now

**Comment by dschuermans** [comment]
The following should do the trick 😄 
```
 JToken token = JToken.Load(reader);

// See if it's an empty object
if (!token.HasValues)
{
      return null;
 }

JToken unit = ((JObject) token).GetValue(nameof(ValueUnit.Unit), StringComparison.OrdinalIgnoreCase);
 JToken value = ((JObject) token).GetValue(nameof(ValueUnit.Value), StringComparison.OrdinalIgnoreCase);

 if (unit == null || value == null)
{
      JsonSerializer localSerializer = new JsonSerializer()
      {
           TypeNameHandling = serializer.TypeNameHandling,
      };
      return token.ToObject<IComparable>(localSerializer);
}
else
{
     return new ValueUnit()
     {
         Unit = unit.ToString(),
         Value = value.ToObject<double>()
     };
}
```

**Comment by dschuermans** [comment]
Will add to #567

**Comment by dschuermans** [comment]
Well, I just read through the RFC spec: https://tools.ietf.org/html/rfc8259

Can't find anything related to case sensitivity though... the RFS spec even has an example object that that has both pascal & camel cased properties.

Anyway, I just found it odd it wasn't working.. I spent a few years in the web app area, and when working in JavaScript with JSON, all properties were camelCased even though the properties on the ASP.NET web api were Pascal cased.

So yea, maybe you're right and shouldn't this be included.
Maybe I ought to test it first if I configure JSON.NET to use camelCasing when serializing / deserializing and see if that works.
But i have a feeling it won't, since the code is directly working with JToken's

I'll let you know what I find.

**Comment by dschuermans** [comment]
And here's Google take on JSON:

https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format

**Comment by dschuermans** [comment]
@angularsen have a look at this:

![image](https://user-images.githubusercontent.com/6634696/49502608-b36e1c00-f875-11e8-9c61-a57e61b014d6.png)

As you can see, I configured my JSON.NET to camelCase properties. I then created a dummy object with 3 properties: a string, an int and a length property.
In the screenshot it clearly shows that my string, int and length properties are correctly serialized in camelCase, however the Length object itself is **not** serialized in camelCase but still Pascal case ☹️

**Comment by dschuermans** [comment]
Although I am starting to believe this might be an issue with JSON.NET itself as I can't see any code in the UnitsNetJsonConverter which could explain this behavior...

**Comment by dschuermans** [comment]
Hooray, figured it out 😄 

Because the UnitsNetJsonConverter is a generic JsonConvert (i.e. there's no type specified for which the JsonConverter is used) it will be run against any type that's being serialized (which to me seems like a bad idea to begin with?)

So the first time around it will try to serialize a Unit, which in turn will tell the serializer to serialize a ValueUnitObject, which in turn calls the WriteJson method **again** on the converter.

![image](https://user-images.githubusercontent.com/6634696/49506422-562a9880-f87e-11e8-8a23-a702bdc785c1.png)

Copying the ContractResolver from the original serializer solved the problem...

**Comment by angularsen** [comment]
Awesome! Nice find.

**Comment by dschuermans** [comment]
Sadly there doesn't seem to be a similar fix when reading json though ☹️ 
I'm still stuck with the case sensitivity there on JToken

**Comment by dschuermans** [comment]
@angularsen  question though, I have wondered why there isn't some sort of IUnit interface that all units implement?
I'm pretty sure it would make this JSON conversion a lot more straight forward and I've had uses cases in the past where I wish i'd have such an interface, can't recall the exact scenarios atm though

**Comment by angularsen** [comment]
We have IQuantity that Length, Mass etc implement. But we can't have IUnit, because that is currently an enum value (LengthUnit.Meter, MassUnit.Kilogram etc).

I'm sure we can improve IQuantity to make JSON serialization easier, any particular ideas you are thinking of?
Also, check out v4 branch as things have changed a bit there. 

https://github.com/angularsen/UnitsNet/pull/487

**Comment by angularsen** [comment]
Any progress here? v4 is now released btw.

**Comment by dschuermans** [comment]
Nope, don't have time left after work & renovations at home i'm afraid :(
We still need to upgrade to v4 ourselves

**Comment by angularsen** [comment]
No problem, I'll close this issue for now just to clean up the issue list. Please reopen if you pick it up later.

**Comment by dschuermans** [comment]
@angularsen going to pick this up again now.

I have the same issues, even with the one from v4.

Using the local serializer is good to prevent loops while serializing, but the root cause here is actually because a single converter is used to converter multiple types (IComparable & ValueUnit) which breaks the single responsibility principle IMO

I'm working on a JsonConverter prototype that inherits from JsonConverter<IQuantity> instead of just JsonConverter.
This way I don't have to deal with the arrays as JsonNet does it for me and it significantly reduces the lines of code in the converter (115 lines vs 219).
Also a lot of the type checking code becomes obsolete.

The only "issue" i'm facing is why the effort to support serialization and deserialization for IComparable?
By default, JsonNet cannot serialize or deserialize any interfaces so the user has to provide their own converter anyway.
If they happen to have their own type that has a "unit" and "value" field which implements IComparable, it will trigger our converter when it's not supposed to.

We provide one for IQuantity but i can't comprehend the use-case where one might use IComparable?
The only thing i can think of is when they would be mixing UnitsNet types with other IComparable implementations but if they're serializing those to JSON, they would have to provide their own converter anyway.
So why not make the user deal with serializing & deserializing IComparable when they represent UnitsNet types?

I'd opt for 2 converters then in this case, one for IQuantity and one for IComparable which the user can opt-in for to use..

**Comment by dschuermans** [comment]
When looking at the test that justifies support for IComparable:

![image](https://user-images.githubusercontent.com/6634696/71965589-422f3400-3200-11ea-94cd-5d885a70a081.png)

The types being serialized have **nothing** to do with UnitsNet, so why bother supporting them to begin with?
Use these types in any other project using JsonNet and you'll get the exception that it doesn't know how to serialize IComparable -.-'

**Comment by angularsen** [comment]
Continuing this conversation in #732.
