### ISSUE TITLE
Best practices for working with dynamic units?

### ISSUE THREAD

**Issue by Mobz87** [angularsen/UnitsNet#587]
I'm working on a program where the customer wants to be able to change the 'default units'.

ex
In a Settings-tab:
Pressure (choose) `Bar or Pascal.`
If you select 'Bar' then all input and output are displayed in Bar.

Right now I have hard coded it like:

```
Pressure = Pressure.FromBars(Control.Value);

OutputBox = Pressure.ToUnit(PressureUnit.Bar).ToString();
```

What is Best practices for making dynamic units?

**Comment by angularsen** [comment]
I think you should get far by using this:
- `Pressure.From(value, selectedUnit)`
- `myPressure.As(selectedUnit)`
- `selectedUnit` is the chosen `PressureUnit` stored in settings

**Comment by tmilnthorp** [comment]
_pressure.As(NewUnit); does not change the value of _pressure, it returns the converted pressure.

```csharp
var converted = _pressure.As(NewUnit);
Debug.Print(converted.Value);
```

As for the unit, it's just an enum. In that case you're doing a [.ToString on an enum](https://docs.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=netframework-4.7.2).

To get the abbreviation, do the following:

```csharp
UnitAbbreviationsCache.Default.GetDefaultAbbreviation(NewUnit)
```

**Comment by angularsen** [comment]
To be clear, converted here is `double` not `Pressure`.

`double converted = _pressure.As(NewUnit);`

Is it possible you simply want to do this?

```c#
string psiText = _pressure.ToUnit(PressureUnit.PoundForcePerSquareInch).ToString(); // "20 psi"
```

**Comment by MrFoged** [comment]
I posted from the the wrong account :-)
Thanks I just do that!

**Comment by angularsen** [comment]
Ok, I'm closing this issue. Just reopen if there is anything else.
