### ISSUE TITLE
Complex Units

### ISSUE THREAD

**Issue by SGStino** [angularsen/UnitsNet#592]
I'm searching for something that can handle slightly more complex units like representing avogadro's number [J/(mol K)] etc.

This would mean that these compound units aren't strongly typed anymore so i'm not sure if this is the goal of this library?

**Comment by tmilnthorp** [comment]
Take a look at my PR, #593. I am not sure if this is enough, but it's hopefully a start!

**Comment by SGStino** [comment]
Hey, certainly a usefull addition, but wasn't entirely what i meant. Shouldn't have used a fixed constant as an example.

I mean something like combining some units in a formula resulting in a more complex intermediate.

```MolarEnergy.FromJoulesPerMole(1) / Temperature.FromKelvins(1)``` would result in the same unit as Avogadro's number, but doesn't look like its feasible at the moment.

Or another one: [J/(kg K)]
```pecificEnergy.FromKilowattHoursPerKilogram(1) / Temperature.FromKelvins(1)```

So writing formulas would usually boil back to taking the SI unit from the Quantity object, running the formula, and trying to create a new unit quantity from the result.

Storing intermediates would be in the old way without typing, strongly or not.

Take for example a classic: `Q = m.c. ΔT` 
Q would be representable as EnergyUnit
m as MassUnit
 ΔT as TemperatureDeltaUnit
but specifying c would have to be in the SI unit, as it can't be represented (yet)?
While there are many different options here: some specify it as [kJ/(kg K)], some as [Kcal/(kg °C)], certain people would even use[btu/(lb°F)] ..

**Comment by SGStino** [comment]
I've investigated how math.js solves this for example, and it seems upon first glance that they have baseunits: Mass, Length, Volume, Temperature, ...

And compounds like speed are basically an array with the base/primitive unit and the power.

For speed this would be [(unit: LengthUnit.Meters, power:1), (unit: TimeUnit.Seconds, power:-1)]

Comparing if it's the same unit would ofc be only possible at runtime, but would come down to a check of the units and the powers.

I wonder if this could be an approach for v5 perhaps? (or it's already in and I just completly overlooked it?)

**Comment by angularsen** [comment]
Cool stuff, but also heavy to digest late in the evening :-)

We do have `BaseDimensions` on all our quantities, so can possibly do something similar to Math.js, but without the static typing as you observed.

I think maybe we can get some static typing out of it though, please look at my comment here. We seem to be onto the same idea:
https://github.com/angularsen/UnitsNet/issues/515#issuecomment-450319160

**Comment by angularsen** [comment]
Closing this in favor of #515, just to keep discussion in a single place.
