### ISSUE TITLE
Replace GlobalConfiguration.DefaultCulture with CultureInfo.CurrentCulture

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#600]
Replace GlobalConfiguration.DefaultCulture with CultureInfo.CurrentCulture. Breaking change so belongs in #563. 

- CultureInfo.CurrentCulture for number formatting
- Use CultureInfo.CurrentCulture or CultureInfo.CurrentUICulture for abbreviations?

**Comment by angularsen** [comment]
Can we perhaps introduce this by using CultureInfo.CurrentCulture as the backing value and mark the class as obsolete, then remove it in v5?

**Comment by tmilnthorp** [comment]
Good idea 👍
