### ISSUE TITLE
Possible to go with ValueTuple 4.5.0 back to 4.4.0?

### ISSUE THREAD

**Issue by CometSL9** [angularsen/UnitsNet#603]
Currently, using UnitNet >4.0 with .NET Framework 4.6.1 is not possible.

This is due to the use of System.ValueTupe 4.5.0 which was taken in since UnitsNet 4.0.

I do not see any Problems when using ValueTuple 4.4.0.

Background: Win 8.0-Machines can not go further than .NET Framework 4.6.1...

**Comment by angularsen** [comment]
Hi, we can probably downgrade if it truly helps, but I don't quite understand why 4.4.0 works but not 4.5.0?

https://www.nuget.org/packages/System.ValueTuple/4.5.0
https://www.nuget.org/packages/System.ValueTuple/4.4.0

Both these explicitly list .NET 4.6.1 targets without any dependencies. Shouldn't it work?
Can you perhaps create a small repro console app project? Just to isolate the problem from any other dependencies you may have, that potentially could be the root cause.

**Comment by CometSL9** [comment]
Hi,

I've cross-checked it here on a Win 8.1 machine (where .NET Framework 4.6.1 is the best you can get). The error also exists on a Win 7 machine with .NET Framework 4.6.1.

To test it, I've downgraded UnitsNet to 3.111.0 to use ValueTuple 4.4.0 => runs smoothly.
UnitsNet 4.0.0 with ValueTuple 4.5.0 => The program can not be loaded.

I traced (via a classic trace file) that the program is executing up to the very point where an object with UnitsNet is instanciated first. There, it tries to load UnitsNet and ValueTuple dlls- which cease to work - and quits. This quit is hard without any error message or even thrown Exceptions.

Therefore, as far as I can say, (independent of the listed dependencies) ValueTuple 4.5.0 wants .NET Framework 4.7.

Repo should be easy as long as you have a .NET Framework 4.6.1 only-machine...

**Comment by angularsen** [comment]
I see. I'm not going to be difficult, if downgrading solves a problem and does not cause any new problems, we'll absolutely do it. But this sounds a bit like a mistake in ValueTuple nuget and maybe worth discussing with them.

Could you please try to download the UnitsNet source and downgrade to 4.4.0, then build it and try to reference that to verify it does indeed fix the problem for you?

And if it does work, then please submit a pull request on the change. We will probably accept the change unless someone spots a problem in PR review.

**Comment by tmilnthorp** [comment]
This is indeed odd. Did the ValueTuple NuGet package get installed into your project correctly?

**Comment by CometSL9** [comment]
Yes, ValueTuple NuGet is installed correctly => As said, with .NET Framework 4.7 on the machine => no problems at all with UnitsNet > 4.0.0 ...

I'll give the download of the source a try, but it will take a bit.

**Comment by angularsen** [comment]
Any news on this @CometSL9 ?

**Comment by CometSL9** [comment]
Today I have re-checked the issue with the actual Xamarin.Forms 3.5.0.169047. Obviously, it has been resolved by M$ itself. => Issue can be closed! :-)

**Comment by angularsen** [comment]
Very nice, thanks for reporting back.
