### ISSUE TITLE
Suggestion: Add Radioactivity 

### ISSUE THREAD

**Issue by nforwood** [angularsen/UnitsNet#605]
I think the Radioactivity quantity should be added, the SI unit is the becquerel (Bq) but there is also the Curie (Ci).

**Comment by angularsen** [comment]
Sounds widely used enough to me, would you be willing to do a pull request on adding it?
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'm happy to assist if you have any questions on following the steps.

**Comment by nforwood** [comment]
I will certainly try that next week.

**Comment by angularsen** [comment]
Cool, I'll close this issue in the meantime. Look forward to your PR.
