### ISSUE TITLE
Support for additional units

### ISSUE THREAD

**Issue by jstumpges** [angularsen/UnitsNet#632]
Hi, I was wondering if it would be possible to add support for a couple additional units:
Length - "Hand"
Volume - "Imperial Pint"

Appreciate your time!

**Comment by tmilnthorp** [comment]
#634 #635

**Comment by angularsen** [comment]
Nuget on the way out
[Release UnitsNet/4.13.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.13.0)
