### ISSUE TITLE
UnitsNetJsonConverter: Error when deserializing a Length with value "0".

### ISSUE THREAD

**Issue by samirem** [angularsen/UnitsNet#639]
Error when trying to deserialize this JSON:
```
"X": {
  "Unit": "LengthUnit.Meter",
  "Value": 0.0
},
```
The following exception is thrown:
**Newtonsoft.Json.JsonSerializationException: 'Could not create an instance of type System.IComparable. Type is an interface or abstract class and cannot be instantiated. Path 'X', line 1110, position 16.'**

Works fine to deserialize if I change the Value to 1.0:
```
"X": {
  "Unit": "LengthUnit.Meter",
  "Value": 1.0
},
```

**Comment by tmilnthorp** [comment]
What version are you using? I tried this with the latest and it succeeds.

**Comment by samirem** [comment]
I just found out that it was an error in my code. I had changed the type of a variable. Thanks for the feedback!

**Comment by tmilnthorp** [comment]
Thanks for the update!
