### ISSUE TITLE
Add time units

### ISSUE THREAD

**Issue by a-c-rodriguez** [angularsen/UnitsNet#647]
Hi, I was wondering if it would be possible to add support for time units. That is to support conversions like:

weeks to months
seconds to years
decades to days
etc

**Comment by tmilnthorp** [comment]
This currently exists in the Duration quantity: https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/Duration.json

**Comment by a-c-rodriguez** [comment]
Thanks!
