### ISSUE TITLE
Extend Irradiation with MillijouleperSqureCentimeter

### ISSUE THREAD

**Issue by Maradaehne** [angularsen/UnitsNet#648]
Hi,

can you add the Unit MilliJoulePerSquareCentimeter [mJ/cm²] to the Irradiation Unit?

Best Regards.

**Comment by angularsen** [comment]
Please take a look at https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

It is fairly easy to do, let me know if you want to do a pull request. We are happy to assist!

**Comment by Maradaehne** [comment]
Hi, 

I tried to do a pull request (#649), but I am not quite  sure if I did everything correct. Its the first time and I am not very familiar with collaboration here on Github. If I need to do something, please advice me what to do.

Best Regards

**Comment by angularsen** [comment]
Great, I'll take a look soon and get back to you!

**Comment by angularsen** [comment]
Fixed by #650
