### ISSUE TITLE
Parsing units fails with a custom FormatProvder 

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#652]
The following exception is thrown
> Unit not found with abbreviation [кг] for unit type [UnitsNet.Units.MassUnit].

when executing the following code
```
           try
            {
                var oneKg = Mass.Parse("1 кг", new CultureInfo("ru-RU"));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
```
given that the abbreviation for the unit is present [here](https://github.com/angularsen/UnitsNet/blob/54420846fcdbf82441495b220f3f2756ef8895d5/Common/UnitDefinitions/Mass.json#L26)

I think the issue stems from [this line of code](https://github.com/angularsen/UnitsNet/blob/54420846fcdbf82441495b220f3f2756ef8895d5/UnitsNet/CustomCode/UnitParser.cs#L53) which doesn't pass on the culture provider 

using the latest version (4.18)

**Comment by angularsen** [comment]
Great find! I'm quite surprised our tests didn't catch this, but it must have slipped during the big rewrite to v4.x.
