### ISSUE TITLE
New unit request: Pitch for screw threads

### ISSUE THREAD

**Issue by BernhardJosef** [angularsen/UnitsNet#654]
I'm developping measurement software for screw thread measurement. I need a unit for pitch.
The pitch is measured in millimeters or inches per single turn [mm] or [in] in Europe; in US Turns Per Inch [TPI] is used (https://en.wikipedia.org/wiki/Unified_Thread_Standard). 
Especially  in Germany [Zoll] or ["] is used as a synonym for [in].

**Comment by angularsen** [comment]
Hi and thanks for reaching out. I think this is the kind of unit that fall out of the 80/20 thumb rule - we want a library that covers most people's needs with not too many quantities and units. There are so many variations of "X per Y" units that the library would grow very big in binary size if we included them all. Very narrow or application specific units should rather be defined per application. 

There is some limited ability to reuse Units.NET infrastructure for custom quantities and units. You can map unit enums and unit abbreviations:
```c#
UnitAbbreviationsCache.Default.MapUnitToAbbreviation(MyQuantityUnit.MyUnit1, "myUnitAbbreviation1");
Assert.Equal(MyQuantityUnit.MyUnit1, UnitParser.Default.Parse<MyQuantityUnit>("myUnitAbbreviation1"));
```

But parsing, constructing and converting quantities is still work in progress in #588 so you may be interested in subscribing to that thread for updates.

**Comment by lipchev** [comment]
Not that I would want to _(insert colorful expression here)_ but wouldn't the same arguments that I made for #646 apply here as well? 

1. Operators : converting linear <-> rotary motion- for example use the [RotationalSpeed ](https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/RotationalSpeed.json) of a motor to get "Distance"|"Speed" etc. 
2. There is **a lot** of converting between US and SI units in this domain- compared to the chemical industry it seems the me that the imperial unit's popularity is overwhelming (plenty of converters out there)
3. Parsing- the author didn't specify this need explicitly- but did give an example of a synonym that seems appropriate mapping to a regional system.

**Comment by angularsen** [comment]
@lipchev Fair points, maybe I was a bit too quick to disregard it as not common enough.
I don't have time to respond or think through it right now, will get back to you both.

**Comment by angularsen** [comment]
If I read the wiki right, a screw is defined by two values; diameter and pitch. I believe diameter is represented by `Length`, and pitch is defined as length per turn - or distance between the threads. 

@BernhardJosef 
1. Could it be sufficient to use `Length` for both diameter and pitch? 

2. You mention `Zoll` or `"` as German localizations for `in`. Would it work to add that to `LengthUnit.Inch` unit or is it screw thread specific?

3. Could you perhaps show a pseudo code of the calculations or quantity representations you want do do, that you can't solve with Units.NET today? I'm really just trying to get a better understanding of the value it brings to add these units to the library as we have to make sure it's something that will benefit many 😃

**Comment by angularsen** [comment]
@BernhardJosef Do you have any thoughts on my last comment?
