### ISSUE TITLE
Add for static property MinValue and MaxValue a setter

### ISSUE THREAD

**Issue by gsgou** [angularsen/UnitsNet#660]
**Describe the solution you'd like**
For custom implementations would be a nice feature to set the MinValue and MaxValue to specific values. For example:
`Length.MaxValue.Centimeters = new Length(240d, LengthUnit.Centimeter);`

**Comment by gsgou** [comment]
I could change it with Reflection for the moment:
```
var defaultMax = Length.MaxValue.Centimeters;
            var lengthMaxValue = new Length(240d, LengthUnit.Centimeter);
            FieldInfo lengthMaxValueField =
                Length.GetType()
                    .GetRuntimeFields()
                    .FirstOrDefault(a => Regex.IsMatch(a.Name, $"\\A<{nameof(Length.MaxValue)}>k__BackingField\\Z"));
            lengthMaxValueField?.SetValue(Length, lengthMaxValue);
            var newMax = Length.MaxValue.Centimeters;
```
but the new MinValue, MaxValue are not respected when values are changing...

**Comment by angularsen** [comment]
Hi, could you please describe a bit more why this feature would be useful?
And is it nice-to-have or of high value to you?

**Comment by angularsen** [comment]
@gsgou A reminder to follow up on my questions above.
