### ISSUE TITLE
Obsolate wiki page - String formatting

### ISSUE THREAD

**Issue by bukkideme** [angularsen/UnitsNet#671]
Please update wiki page regarding to String formatting. It contains obsolate info.
thanks!
[https://github.com/angularsen/UnitsNet/wiki/String-Formatting](https://github.com/angularsen/UnitsNet/wiki/String-Formatting)

**Comment by angularsen** [comment]
Thanks for pointing it out. I've gone and updated it. Please take a look and comment on if you are missing anything?

**Comment by angularsen** [comment]
[String Formatting · angularsen/UnitsNet Wiki](https://github.com/angularsen/UnitsNet/wiki/String-Formatting)

**Comment by angularsen** [comment]
Closing this as fixed.
