### ISSUE TITLE
Autogenerated implicit cast from double / decimal to unit

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#684]
**Is your feature request related to a problem? Please describe.**
A lot of From() calls are made to create a unit from 0.0. 

**Describe the solution you'd like**
Autogenerate implicit cast from double / decimal from generate-code.

**Describe alternatives you've considered**
Continue making calls to From...() methods. Create static readonly values of 0.0 to make it easier to work with.

**Additional context**
It is possible that this could lead to errors, where people do not realize that the implicit conversion will not necessarily bears the right units. This is true for situation where a value different than 0.0 is used. An exception could be thrown if the value is different than 0.0, although this is not that good coding practice I think.

**Comment by angularsen** [comment]
I'm not sure I follow, could you please post a short code example of what you would like to do?

**Comment by ebfortin** [comment]
After I made this enhancement request I discovered the "Zero" property. So it mostly resolve my issue.

But regardless, it would be good to be able to pass a 0.0 double instead of Length.Zero, for example. 

public SomeMethod(Mass m);
...
SomeMethod(Mass.Zero); // OR SomeMethod(0.0); Implicit cast from double to Mass.

**Comment by angularsen** [comment]
Aha. Yes, I can see how that could be convenient, however I do see a major challenge with that idea.

1. It is not intuitive what unit to expect.
2. Extension methods can't be limited to only the number zero.
3. Even if only the number zero is used, some quantities like temperature have different zero values such as 0 Celsius != 0 Fahrenheit != 0 Kelvins.

So I see more downsides than upsides to supporting this. What do you think?

**Comment by ebfortin** [comment]
Yeah you are right. So I'll use the Zero property and stop complaining :)

**Comment by angularsen** [comment]
No not at all, I'm happy to get fresh minds thinking of how this can all be improved for the better :-) Keep it coming 👍
