### ISSUE TITLE
Add support for MillimetersOfWater units to Pressure

### ISSUE THREAD

**Issue by alexmarshall132** [angularsen/UnitsNet#685]
The Pressure quantity already supports conversion to MillimetersOfMercury. A corresponding addition of MillimetersOfWater would also help. The conversion function can be found here:

https://www.metric-conversions.org/pressure/millimeters-of-mercury-to-millimeters-of-water.htm

**Comment by angularsen** [comment]
Hey, thanks for reporting. Would you be interested in doing a pull request to add this?
It's not too difficult to do and we have some step by step guides: 
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I'd be happy to assist.
