### ISSUE TITLE
Misunderstanding on how TemperatureDelta works

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#696]
**Describe the bug**
It may or may not be a bug. I use TemperatureDelta and when I put in a positive number, it displays as a negative number with ToString().

**To Reproduce**
Steps to reproduce the behavior (just an example):
In a console application or in the C# interactive window of VS2019.
1. Create a TemperatureDelta value using FromKelvins(+10.0). Put it in var t.
2. Call Console.WriteLine(t).

**Expected behavior**
A positive value.

**Screenshots**

**Additional context**

**Comment by ebfortin** [comment]
In interactive c# window it works. I single stepped my code and it still returns a negative. I will need to investigate more before calling this a bug.

**Comment by angularsen** [comment]
Any updates on this?

**Comment by ebfortin** [comment]
Was not a bug. I was just not doing the right thing.

**Comment by angularsen** [comment]
Thanks for the update. Closing this.
