### ISSUE TITLE
Syntax Sugar (Implicit ValueTuple Conversion)

### ISSUE THREAD

**Issue by ZacharyPatten** [angularsen/UnitsNet#699]
There is a feature scheduled for C# 9 that allows type inference on construction (Example: "Acceleration a = new(...);"). That will be some nice syntax sugar for defining measurements.

However... It is possible to simplify things even further with implicit casting operators from ValueTuple types. Example:
```csharp
Acceleration a = (7, AccelerationUnit.MeterPerSecondSquared);
```
You could even simplify things further to something like this, but it will require additional types:
```csharp
Acceleration a = (7, Meters / Seconds / Seconds);
// or
Acceleration a = (7, MetersPerSecondSquared);
```
_(In my opinion)_ These are improvements over using the static factory methods or constructors. Current required code:
```csharp
Acceleration a = new Acceleration(7, AccellerationUnit.MeterPerSecondSquared);
// or
Acceleration a = Acceleration.FromMetersPerSecondSquared(7);
```

**Comment by tmilnthorp** [comment]
I like the ValueTuple conversions, really nice! Boost units does something similar with multiplication e.g. 7 * AccellerationUnit.MeterPerSecondSquared

**Comment by ZacharyPatten** [comment]
The implementation of this issue should be pretty obvious (just add implicit casting operators from ValueTuple types that funnel into the constructors of the measurement types)... but just in case, I have examples in my Towel project if needed for reference.
```csharp
Force<double> force1 = (1d, Kilograms * Meters / Seconds / Seconds);
Force<double> force2 = (2d, Newtons);
```
I quite like the operators in the unit definitions personally, but **Units.Net currently doesn't allow for mix-matching like unit types in derived measurements (Example: Meters / Seconds / Hours)**, so Units.Net probably shouldn't do that unless it is re-structured to store all base types.

With its current structure... Units.Net should just go with the other example I mentioned:
```csharp
Acceleration a = (7, MetersPerSecondSquared);
```
because that is compatible with the current code base.

Either way, it will require additional types (and the help of a using statement to a static class) to get the desired syntax.
