### ISSUE TITLE
The flow unit SCCM is missing

### ISSUE THREAD

**Issue by bitbonk** [angularsen/UnitsNet#713]
A very common unit used in [mass flow controllers](https://en.wikipedia.org/wiki/Mass_flow_controller) is [SCCM](https://en.wikipedia.org/wiki/SCCM_(flow_unit)) (aka. standard cubic centimeters per minute). Unfortunately this unit is missing in UnitsNet.

You already have `VolumeFlowUnit.CubicDecimeterPerMinute` please also add `VolumeFlowUnit.CubicCentimeterPerMinute`.

**Comment by angularsen** [comment]
Hi, would you be willing to do a pull request on it? On the phone now, but
details are on the Readme page.

**Comment by bitbonk** [comment]
Yes, I would. Seems easy enough.

**Comment by bitbonk** [comment]
After further investigation, the unit SCCM (**standard** cubic centimeters per minute) does not belong to same quantity type (*VolumeFlow*) with a unit like *cm³/m*. 

[The wikipedia article](https://en.wikipedia.org/wiki/SCCM_(flow_unit)) suggests that SCCM is the flow rate under "standard conditions for temperature and pressure". So to convert one to the other the actual pressure and temperature seems to be needed.

1. So the question is, how do we get an authoritative answer from an domain expert? 
2. Would UnitsNet have means to convert one quantity to another (e.g. standard volume flow to volume flow) based on a formula that needs additional parameters (pressure and temperature)?

Some reference links:
https://www.instrumart.com/assets/TSI-Alnor-GP-Standard-Vs-Volumetric.pdf
http://www.controlandinstrumentation.com/flow/standard.html
https://www.wolframalpha.com/input/?i=standard+cubic+centimeters+per+minute+vs+cubic+centimeters+per+minute

**Comment by lipchev** [comment]
I'm no domain expert but here are my 5c on the subject:

1. From the reference you provided it seems to me that we would need to define a Quantity of type **Standard Flow Rate** (denoted as Q in the ref. document)
2. This Quantity would have Units such as **std L/min** (or cubic centimeters per second or what have you)
3. You can define conversion methods in either/both **VF** & **SFR** that take the Temperature and Pressure as parameters

The only problem here is the acceptance criteria for new (and obscure) Quantities - such as the proposed SFR - but that is not up to me to decide... However- the question that I expect would come next is "Wouldn't the existing VF quantity type work for you?". 
Personally, I am not sure if VF can/should be decoupled from the  accompanying choices for standard temperature & pressure- could you compare two VFs without known what standard values are assumed? I think a class that combines the 3 quantities makes more sense- one could then compare them using the calculated VFs instead.

**Comment by angularsen** [comment]
I am not familiar with this domain at all, but my intuition tells me @lipchev makes some good points here. It seems like maybe what you are looking for is a wrapper type that holds more information (temperature + pressure + flow rate) to represent flow rate at a certain temperature and pressure. Then you can convert to flow rates at _other_ conditions of temperature or pressure.

If you agree, then I think _maybe_ this is out of scope of UnitsNet library and perhaps better placed per application. Or, if many others would find this concept useful, we could add it to the library. I'm open to suggestions.

**Comment by angularsen** [comment]
Closing this in favor of #724 .
