### ISSUE TITLE
Missing functionality in UnitsNetJsonConverter

### ISSUE THREAD

**Issue by dschuermans** [angularsen/UnitsNet#731]
So i'm in the process of upgrading to UnitsNet 4.42.0 and getting rid of our copy of the UnitsNetJsonConverter, by using UnitsNet.Serialization.JsonNet 4.0.0, because I have incorporated the fixes from our copy in my latest PR (see #712)

However, after running into some issues (e.g. #718) I noticed that the fixes (e.g. array serialization & deserialization) are not incorporated in the current nuget release.

Did you forget to release the nuget?

**Comment by angularsen** [comment]
Huh, not sure. I'll check.

**Comment by angularsen** [comment]
Oh yes, forgot to bump its version so it never got pushed out. JSON nuget 4.1.1 is out. Please let me know if it works as expected.
