### ISSUE TITLE
Add Environmental Reference type for Temperature and Pressure References

### ISSUE THREAD

**Issue by sequc82** [angularsen/UnitsNet#741]
The issue first presented itself in #422 where a reference pressure was needed to convert gauge, absolute and vacuum pressures. It was resolved in #422 with a public property `ReferencePressure.AtmosphericPressure`. It has come up again in #724 when discussing another wrapper type `ReferenceVolumeFlow`, but in this case both the atmospheric `Temperature` and `Pressure`.

Create an `EnvironmentalReference` type, which would be accessible at a level similar to `UnitSystem`.

**For Example:**
```C#
public enum StandardReference
{
    StandardUS,
    StandardISO,
    StandardAGA,
    Normal,
    Custom
}

public struct EnvironmentalReference
{
	public EnvironmentalReference(Pressure p, Temperature t, double RelativeHumidity)
    {
		/*Assign properties here*/
    }
	
	public static Dictionary<StandardReference, EnvironmentalReference> StandardReferences { get; } = new Dictionary<StandardReference, EnvironmentalReference>()
        {
            {StandardReference.StandardUS, new EnvironmentalReference(Pressure.FromPoundsForcePerSquareInch(14.696), Temperature.FromDegreesFahrenheit(60), 0)},
			/*Define subsequent StandardReferences here*/
        };
{
```

I'm still trying to understand the usage and storage of `UnitSystem, but I would think `EnvironmentalReference` would be similar to `UnitSystem`, with the STP conditions being similar to `BaseUnits`, and the `Dictionary` of `StandardReference` would be similar to `UnitSystem.SI` if it stored a collection of `UnitSystem` instead of only SI.

**Comment by angularsen** [comment]
Please see some background on UnitSystem. It was an experimental feature in v4 that we later found to have design flaws for basically any other unit system than SI, so we have some ideas on how to change that for v5.

https://github.com/angularsen/UnitsNet/pull/630
https://github.com/angularsen/UnitsNet/issues/651
https://github.com/angularsen/UnitsNet/issues/666
https://github.com/angularsen/UnitsNet/pull/709
