### ISSUE TITLE
Null Reference Exception from QuantityTypeConverter

### ISSUE THREAD

**Issue by WalkerCodeRanger** [angularsen/UnitsNet#755]
**Describe the bug**
If the `PropertyDescriptor` property of the context which is invoking `QuantityTypeConverter<T>.ConvertFrom()` is null, it throws a `NullReferenceException`.

**To Reproduce**
```csharp
var converter = new QuantityTypeConverter<Length>();
// TypeDescriptorContext with null `PropertyDescriptor` property
ITypeDescriptorContext context = new TypeDescriptorContext();
Length length = Length.FromMeters(1);

string convertedQuantity = (string)converter.ConvertTo(context, culture, length, typeof(string));
```

**Expected behavior**
No exception should be thrown. The conversion should be done as if there were a property with no attributes.

**Additional context**
In our codebase, this is happening indirectly through the `System.Activities.Presentation.WorkflowDesigner.PropertyInspectorView`. Also, the [`ITypeDescriptorContext.PropertyDescriptor` docs](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.itypedescriptorcontext.propertydescriptor?view=netframework-4.8) explicitly state that this property "describes the given context item; otherwise, `null` if there is no PropertyDescriptor responsible for the call."

**Comment by angularsen** [comment]
[Release UnitsNet/4.47.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.47.0)
