### ISSUE TITLE
Provide Default Type Converter for Quanitities

### ISSUE THREAD

**Issue by WalkerCodeRanger** [angularsen/UnitsNet#757]
**Is your feature request related to a problem? Please describe.**
The `QuantityTypeConverter<TQuantity>` class included with UnitsNet provides a type converter that can be used, for example for `Length`, by applying the attribute `[TypeConverter(typeof(QuantityTypeConverter<Length>))]` to each property that requires type conversion. However, this can be *a lot* of properties and is easy to forget to do.

**Describe the solution you'd like**
Typically, when a class is distributed with a type converter, it is associated with the declaration of the class so that the type converter will be picked up by default whenever one is needed. The type converter can still be overridden by applying a type converter attribute to the property. Following the usual convention, I think all quantity types should have a type converter applied to their class using the `TypeConverterAttribute`.

**Describe alternatives you've considered**
Users of the UnitsNet library can work around this using one of two techniques:
1. Apply a `TypeConverter` attribute to each property that requires type conversion.
2. Registering a default type converter using `TypeDescriptor.AddAttributes(typeof(TQuantity), new TypeConverterAttribute(typeof(QuantityTypeConverter<TQuantity>)));`. Note that this must be done very early in the application to ensure the registration is done before the type converter is requested using `TypeDescriptor.GetConverter(typeof(TQuantity))`.

**Comment by WalkerCodeRanger** [comment]
I tried to implement this and had a some issues with JsonNet serialization. Adding the default converter broke the serializing of `Nullable<TQuantity>` types. JsonNet switched to using the type converter to convert to a string rather than using the JSON converter for the quantity type. This appears to be a bug in JsonNet because the JsonConverter should take precedence and indeed it does for non-null quantity types.

**Comment by angularsen** [comment]
Anything I can do to help? I'm not very familiar with type converters and best practices here, in particular in combination with JSON.net.

Recently, in https://github.com/angularsen/UnitsNet/pull/746 `UnitsNetJsonConverter` was deprecated in favor of `UnitsNetIQuantityJsonConverter`. Did you try with this new converter?
