### ISSUE TITLE
Full russian culture support

### ISSUE THREAD

**Issue by andreygolubkow** [angularsen/UnitsNet#766]
When i use Russian culture, some units does not have translate.

I want to add the russian culture support.

I can use English culture, but russian engineers have problems with it.

I want get translate for:
* Speed
* Pressure
* Frequency

But i will happy, if all units have been translated

Thanks!

**Comment by angularsen** [comment]
Hi and thanks for the pull request. I don't know Russian myself, so I would need assistance translating and fixing existing abbreviations in the library. Is that something you or others on your team could help out on?

I believe a lot of the abbreviations are added by the help of google translate and probably not of very good quality.

**Comment by andreygolubkow** [comment]
Yes, i can help you, if i have a time
