### ISSUE TITLE
Missed Unit Curvature&Torsion

### ISSUE THREAD

**Issue by sunlight2424** [angularsen/UnitsNet#778]
Could someone pls add Unit Curvature&Torsion Support in the library, which should be the inversion of length. This is quite useful when try to do space navigations, for example, people try to use °/30m to describe engineering curvature instead of m(-1).

**Comment by angularsen** [comment]
Hi, I'd be happy to assist you adding it.

Please see: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

It sounds like you want a new quantity `InverseLength` perhaps?
https://en.wikipedia.org/wiki/Reciprocal_length

You should be able to copy `Length.json` and adjust its units.
