### ISSUE TITLE
Conversion precision mm to Inch

### ISSUE THREAD

**Issue by Louven** [angularsen/UnitsNet#783]
Hi, 
I wonder why a conversion from Mm to Inch give a strong rounded issue.
Ex : 
Console.WriteLine(Length.FromMillimeters(139.7).ToUnit(UnitsNet.Units.LengthUnit.Inch)); // Gives 5.5 inches
Console.WriteLine(Length.FromMillimeters(139700).ToUnit(UnitsNet.Units.LengthUnit.Inch));// Gives 5500 inches

It is a wanted behavior?

Thanks

**Comment by angularsen** [comment]
I don't understand the problem? 

139.7 mm is 5.5 inches
https://www.google.com/search?client=ms-android-samsung-gs-rev1&sxsrf=ALeKk02C-bxwuzM0LQn1sSQWlaHNANIV2g%3A1589209323087&ei=62i5XobEBOGHwPAPocqK2AM&q=139.700+mm+to+inches&oq=139.700+mm+to+inches&gs_lcp=ChNtb2JpbGUtZ3dzLXdpei1zZXJwEAM6BAgjECdQyJoDWPalA2CerQNoAHAAeAGAAZQCiAHgBJIBBTEuMi4xmAEAoAEB&sclient=mobile-gws-wiz-serp

139700 mm is 5500 inches 
https://www.google.com/search?q=139700+mm+to+inches&oq=139700+mm+to+inches+&aqs=chrome..69i57.7684j0j7&client=ms-android-samsung-gs-rev1&sourceid=chrome-mobile&ie=UTF-8

**Comment by Louven** [comment]
Yes, 
Shame on me .. you can close the subject, I was cheated by Google ..

**Comment by angularsen** [comment]
No problem 😀 glad it worked out.
