### ISSUE TITLE
Default number format should be CultureInfo.CurrentCulture, not CurrentUICulture

### ISSUE THREAD

**Issue by pgrawehr** [angularsen/UnitsNet#787]
The default formatting of numbers (in QuantityFormatter.cs), when no explicit culture is given, should use `CultureInfo.CurrentCulture` not `CultureInfo.CurrentUICulture`. On Windows, the first corresponds to the selection from the control panel "Regional Settings" and defines the locale settings of the user. `CurrentUICulture` represents the language of the UI, which will be english for everyone that uses Windows in english. 

In my case, CurrentUICulture is "de-DE", since my Windows is German, but CurrentCulture is "de-CH", since I use the number format for Switzerland (which is quite different).

**Comment by angularsen** [comment]
Thanks for reporting, you may be right. Will look into it.

**Comment by tmilnthorp** [comment]
It is correct, we're using the wrong one. This would be a behavior break though.

**Comment by pgrawehr** [comment]
No, I don't think this should be wontfix. A PR for this is pending (but apparently waiting for other stuff to get done as well)

**Comment by pgrawehr** [comment]
@angularsen @tmilnthorp Are there any plans when 4.X will be branched out so that some of the pending breaking changes could be implemented for 5.0? The number formatting is unfortunately poor, so that I keep doing it manually.

**Comment by angularsen** [comment]
@pgrawehr There is #982 now. Would you be interested in doing a PR to that branch?

**Comment by pgrawehr** [comment]
I'm quite busy at the moment, but I'll try to adapt #795 for that branch. I also need to check whether there's any leftovers from #788 (such as formatting obtions to remove or improve)

**Comment by angularsen** [comment]
If I am not mistaken, this was fixed in v5 by #986.
