### ISSUE TITLE
Generic quantities update

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#792]
I've been off the development on UnitsNet for some time. Was there any progress made on the use of generic? 

I implemented a double double type, giving 128-bits like float, which would be quite interesting to use with UnitsNet. But without generic quantities, it would be a pain to implement.

**Comment by ebfortin** [comment]
I also did some tests with generic operators. Not quite performing enough yet, but getting there.

**Comment by tmilnthorp** [comment]
I had made #714 to try it out some but haven't got a chance to go back. We merged #698 yesterday that allows math operations on generic types.
