### ISSUE TITLE
Remove unnecessary format strings

### ISSUE THREAD

**Issue by tmilnthorp** [angularsen/UnitsNet#797]
Remove:
- "V" and "v"
- "S" and "s".

Instead of "v", use `IQuantity.Value.ToString()` to get the value string.
Instead of "s", use "f2", "n4" or any of the standard numeric formats.

See https://github.com/angularsen/UnitsNet/wiki/String-Formatting

**Comment by angularsen** [comment]
Fixed in v5 branch.
