### ISSUE TITLE
Incorrect unit conversion for Coefficient Of Thermal Expansion

### ISSUE THREAD

**Issue by joannaz** [angularsen/UnitsNet#807]
**Describe the bug**
The conversion between 1/F to 1/K gives an incorrect value. For example, 10 1/F to 1/K should be 18, but UnitsNet retrieves it as 5.55.

I think the `FromUnitToBaseFunc` and `FromBaseToUnitFunc` for `InverseDegreeFahrenheit` in `Common/UnitDefinitions/CoefficientOfThermalExpansion.json` are the wrong way around.

**To Reproduce**
1. Create a project with UnitsNet.
2. Add the below code.
```csharp
var coefficient = CoefficientOfThermalExpansion.FromInverseDegreeFahrenheit(10);
```
3. See that `coefficient.InverseKelvin` is 5.5555...., not 18.

**Expected behavior**
The conversion from 1/F to 1/K and vice versa should be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/4250241/84163818-cf094280-aa69-11ea-8a2e-14d5f953bec3.png)

**Additional context**
Unit Converter used: http://www.unitconversion.org/unit_converter/thermal-expansion.html

Please let me know if you need anything else or if I'm mistaken. Thanks :)

**Comment by tmilnthorp** [comment]
Hey Joanna, you are correct. I've created #808 to resolve this issue.

Thanks

**Comment by joannaz** [comment]
Great, thanks for the quick fix!

**Comment by angularsen** [comment]
Nuget is on the way out
[Release UnitsNet/4.63.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.63.0)
