### ISSUE TITLE
SI Units Filtering

### ISSUE THREAD

**Issue by ThomasVetterling** [angularsen/UnitsNet#809]
Hello dear Units.Net team,

probably if have a stupid question:

How can I filter the possible Units to only the ones which are SI-Units and derived from SI?
I dont want to show the imperial Units to my users in UI.

Is there a flag for filtering imperial units out of any quantityInfo.UnitInfos ?

Thank you for any hint you can give me.

Yours Thomas Vetterling

**Comment by lipchev** [comment]
Hello Thomas,
Unfortunately this is something that is currently missing from the library- I have started #709 that would address this issue- but haven't had the time to work on it. 
As of right now- my advice to you would be to create lists (I have those defined as xaml resources i.e. x:Arrays) that you populate yourself. If we're talking about user selection- honestly- I think even if you filtered out the non-SI units- most of the time, you'd still be left with way too many units. 

If you don't care about UX but only need to get the list- I have a quick-and-dirty extension somewhere that filters out on the units that are powers of 10.
