### ISSUE TITLE
Milli-g Unit for acceleration type

### ISSUE THREAD

**Issue by MitchGH** [angularsen/UnitsNet#812]
For vibration measurement, the unit of acceleration is often very small and gets defined as "mg" instead of "g" (StandardGravity).
It would be helpful, if this unit can be added for the acceleration type.

**Comment by angularsen** [comment]
Hi, this seems reasonable to me. Would you be willing to do a pull request? 

It should be pretty straight forward.
You add the `Milli` prefix to the JSON definition of Acceleration:
https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/Acceleration.json#L132-L150

Detailed steps are outlined here:
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit
