### ISSUE TITLE
Drop support for Windows Runtime Component

### ISSUE THREAD

**Issue by angularsen** [angularsen/UnitsNet#815]
I just wanted to bring this up again. 
We added support for this in 2016 with #150, mainly because it was requested by a Microsoft team working on providing IoT nuget packages.

It is clear that this effort has stopped and the only two dependencies I can track via
[fuget.org](https://www.fuget.org/packages/UnitsNet.WindowsRuntimeComponent) are:
- https://www.fuget.org/packages/Microsoft.IoT.DeviceCore
- https://www.fuget.org/packages/Zen.IoT.Devices

Both of these stopped getting updates in 2017.

We visited this topic in 2018 in #576 and the Microsoft member that originally requested this feature pretty much confirmed that the Windows Runtime Component effort is dead in its tracks on Microsoft's side of things.

Nothing new has happened since then really, it's just been nagging at the back of my mind and I don't like having crud if it is not actually being used by anyone or it's like 5 people in the world who care.

### Proposal
- Deprecate the nuget package as no longer being maintained with a notice to contact us
- Stop publishing WRC nugets as part of our normal workflow
- Listen for a few months if anyone complains, then reconsider
- If no one complains, then remove all WRC code and build scripts and stop publishing new nugets

Pros:
- Simplifies UnitsNet code base and build pipeline, the wtf-factor goes down a few notches.

Cons:
- The [nuget is still being downloaded](https://www.nuget.org/packages/UnitsNet.WindowsRuntimeComponent) although it is hard to distinguish robots from actual usage.
- We made an effort to make WRC codegen its own separate thing, so it does not really cost us much to keep it around and update it with new units.

**Comment by angularsen** [comment]
Thank you for your opinion on this.

I 66% agree with you 😄 there is a cost however, in on-boarding new contributors having to know what WRC is.

I'm perfectly open to keep it, but I do think it should be removed at some point in the future if we can determine that pretty much no one relies on it anymore. My hunch is that very, very few use this already today.

I can't say for sure that no one is using it, which is why I created the issue hoping someone would notice and chime in saying they were actually using this.

**Comment by angularsen** [comment]
A couple new sources of usage since last time:
- [GitHub search - only forks](https://github.com/search?q=unitsnet.windowsruntimecomponent&type=Code)
- [nuget.org](https://www.nuget.org/packages/UnitsNet.WindowsRuntimeComponent) - 0 listed dependents, 72 downloads of latest release 20 days ago
- [fuget.org](https://www.nuget.org/packages/UnitsNet.WindowsRuntimeComponent)
	- [Microsoft.IoT.DeviceCore](https://www.fuget.org/packages/Microsoft.IoT.DeviceCore) last release 2017
	- [Zen.IoT.Devices](https://www.fuget.org/packages/Zen.IoT.Devices) last release 2017

**Comment by dschuermans** [comment]
Wouldn't it be an option to extract all the WRC stuff into it's own repository and have it live there? Maybe an entire copy of what currently exists is required (idk if code is being shared between the WRC stuff and UnitsNet?)

It won't be getting any new units or fixes that are made to the normal UnitsNet library, but there's probably no need to either?
Then, if someone does find an issue or whatever, it can be fixed there and optionally, a new nuget package published if required?

**Comment by angularsen** [comment]
That is probably a good way to deprecate it, yes. 

Its readme could state that ownership of that code is abandoned and those who needs to keep it up to date would have to take ownership of it and sync in the new units from the main repo and set up their own build pipeline if they need one. The WRC nugets would point to the WRC repo to make it discoverable, in addition to having the nuget text describe the situation.

I personally would like to do this, but if others would rather keep it because it does not add too much burden to this project, then I'm fine with that too. So this issue is basically to hear out opinions of people using UnitsNet or contributing to the project.

**Comment by angularsen** [comment]
I'm removing WRC in v5, until someone comes screaming about adding it back.
Beyond the summary listed above, I'd also like to mention that it shortens the build time, which is already pretty painful on appveyor's slow agents with 10-20 minute build times.

**Comment by angularsen** [comment]
Closed by #496ed5d in release/v5 branch.
