### ISSUE TITLE
Volume and its relationship with Temperature

### ISSUE THREAD

**Issue by expertalex** [angularsen/UnitsNet#818]
Hi 

Thanks a lot for your work, I was interested on it and sow that Volumes and Weights are not linked to Temperature.

For example We Sometimes want to Convert Between Liters at 15 Degrees to Galons at 50 Degrees.

Is your Framework designed to add relationship between Base Units?

CompexVolume = { Volume and Temperature } 

See: When is a Litre not a Litre? 
https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/283253/laymans-guide-on-sta-measurement-v2-march_2011.pdf

**Comment by angularsen** [comment]
Hi there, this concept does not exist in the library.

I get that a liter can fit more gasoline or water at lower temperatures and thus weigh more, so the temperature must be taken into account when converting volume to weight. I don't know this, but I speculate that different materials have different expansion properties that also must be taken into account for these conversions.

This sounds like a very domain specific concern that each application must handle.
Units.NET core library aims to be generic purpose and solve the common use cases when working with quantities and units.

It could be a separate nuget of course, that adds these domain specific features on top of Units.NET.

So, either solve it per application or create a library for others to benefit from. Would that work for you?

**Comment by tmilnthorp** [comment]
I believe this is beyond the scope of this project. That is getting into material library territory. Often, such properties are orthotropic and would require  directionality.

**Comment by MadsFoged** [comment]
I have created a project that tackles that issues.
It is called: [SharpFluids](https://github.com/MadsKirkFoged/SharpFluids)

You can ask for the density of a lot of different fluids at different temperatures and then use the density to convert between volume and weight.
It uses UnitNet to handle the unit-calculations.
It is build as an engineering tool however if you are doing simple stuff it should be easy to understand

**Comment by angularsen** [comment]
Great tip @MadsFoged , thanks!
I will close this issue for now.
