### ISSUE TITLE
Thoughts regarding new ForceUnit "ShortTonForce" / "USTonForce" / whatever?

### ISSUE THREAD

**Issue by lwestfall** [angularsen/UnitsNet#819]
I was surprised to see that there isn't yet a ForceUnit.ShortTonForce (or equivalent) implemented (though it is just another imperial oddity... I digress).

Is there a specific reason this hasn't been implemented yet, or was there just no demand? If not I can make the contribution, in that case what is the preferred name? ShortTonForce makes the most sense in my mind and nicely follows the already present mass unit of "ShortTon," but I'm open to suggestions.

Here's more info on the unit for those unfamiliar: https://en.wikipedia.org/wiki/Ton-force#Short_ton-force

**Comment by angularsen** [comment]
Hi, `ShortTonForce` sounds good and seems to be the term that is used in the wiki you referenced. No reason it isn't added, someone simply hasn't asked for it yet 😊

Please go ahead with a pull request, I'd be happy to merge it in!

Details here: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

Let me know if you need any assistance 👍
