### ISSUE TITLE
Add Unit NTU (Turbidity)

### ISSUE THREAD

**Issue by rgomez90** [angularsen/UnitsNet#825]
**Is your feature request related to a problem? Please describe.**
Add new Quantity => Turbidity + Unit => [NTU]

**Describe the solution you'd like**
New Quantity Turbidity with unit NTU

**Additional context**
I already implemented this in my fork and could build/generate custom code without issues.

But since NTU is not an SI unit, I would like to ask if I should make a PR for this, i.e. add the quantity to the library, instead of creating my own copy.

This is the json for `Turbidity`

```json
{
  "Name": "Turbidity",
  "BaseUnit": "NTU",
  "XmlDoc": "Turbidity is the cloudiness or haziness of a fluid caused by large numbers of individual particles that are generally invisible to the naked eye, similar to smoke in air. The measurement of turbidity is a key test of water quality.",
  "XmlDocRemarks": "https://en.wikipedia.org/wiki/Turbidity",
  "BaseDimensions": {
    "M": 0,
    "T": 0,
    "I": 0
  },
  "Units": [
    {
      "SingularName": "NTU",
      "PluralName": "NTU",
      "FromUnitToBaseFunc": "x",
      "FromBaseToUnitFunc": "x",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": ["NTU"]
        }
      ]
    }
  ]
}
```
My question is about `BaseDimensions`...Due NTU not being SI, there are no `BaseDimensions` for it. Can I do like this and set all to `0`?

If OK, then I would make a PR for this.

**Comment by angularsen** [comment]
Base dimensions default to 0 so you can simply remove the entire BaseDimensions field.

1. Should the singular/plural names be `NTU` or `NephelometricTurbidityUnit`/`...Units`?

For example, should we in code type `var x = Turbidity.FromNTU(10)` or `var x = Turbidity.FromNephelometricTurbidityUnits(10)`? The name is really long, so I can understand if the short hand is preferred.

2. Are there other units of turbidity to consider adding? I couldn't immediately find any, but related measurements are mentioned like [NTU, FNU, FTU, FAU, and JTU](https://support.hach.com/app/answers/answer_view/a_id/1000336/~/what-is-the-difference-between-the-turbidity-units-ntu%2C-fnu%2C-ftu%2C-and-fau%3F-what)

3. Are there conversions from Turbidity to say Mass or Volume or other quantities that it would make sense to add? Something like `Turbidity / Volume = Mass` or similar.

The reason I ask is that there is more value in adding this quantity if it allows us to convert between units or quantities.

**Comment by angularsen** [comment]
Thank you for clarifying.

1. Perfect
2. Based on your description, I don't we should add JTU,FTU etc.
3. We try to avoid bloat by only adding stuff that will actually be used by someone. We can hold off on this.

I am convinced that adding this quantity, even without conversions, does have some value. Mostly because it is so widely used.

Please go ahead with creating a pull request, I will be happy to assist if you have any questions.
https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit
