### ISSUE TITLE
Add horsePower hour energy unit

### ISSUE THREAD

**Issue by ssahon** [angularsen/UnitsNet#827]
is it possible to add horse power hour energy unit (hp-h)? https://www.engineersedge.com/thermodynamics/energy_power_equi.htm
we use it as standard energy unit for US oilfield unit system.

**Comment by angularsen** [comment]
Yes this sounds reasonable.
Would you be interested in doing the pull request?

Steps are outlined here and I'd be happy to assist.
[Adding a New Unit](https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit)

**Comment by ssahon** [comment]
well I tried to make PR but got 403 error

> Pushing add-horse-power-hour-unit
> Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
> unable to access 'https://github.com/angularsen/UnitsNet.git/': The requested URL returned error: 403
> Pushing to https://github.com/angularsen/UnitsNet.git

**Comment by angularsen** [comment]
Ah, yes you would need to fork this repo first to get your own copy, clone that, do the work there (preferably on a feature branch and not on `master` to avoid troubles down the road) and push the branch up to your fork.
Then you create a pull request from your fork's branch, to this repo.

There are many guides on this if you are not familiar with it. For example this one looks decent:
https://jarv.is/notes/how-to-pull-request-fork-github/
