### ISSUE TITLE
Add money/currency to UnitsNet

### ISSUE THREAD

**Issue by eilidht** [angularsen/UnitsNet#830]
**Is your feature request related to a problem? Please describe.**

I would like to use UnitsNet to represent money. For example, Euros and EUR/Mwh.

**Describe the solution you'd like**

I would like to be able to use UnitsNet to do a calculation like EUR/MWh * MWh = EUR with the correct units. I would not expect to use UnitsNet to do currency conversions like Euros to Dollars because the exchange rates fluctuate all the time. 

**Describe alternatives you've considered**

I am trying to implement this myself on a fork of this project and would like any input from anyone who has considered adding money to UnitsNet previously. As far as I can tell, for the units to be correct in calculations, I would have to add money as a BaseUnit (alongside the seven standard scientific units). This doesn't quite feel right. I would also list the different currencies as units of money but without a conversion between them defined.

**Additional context**

**Comment by eriove** [comment]
What I've done before when needing this is to assume that money is dimensionless. Hence EUR/MWh becomes 1/(MWh). This makes all the calculations work. I was lucky with the units and all I needed already had their inverse implemented.

In other words that would require implementing a couple of new quantities and/or units in existing units, but the total work would be smaller. @angularsen what do you think?

**Comment by eilidht** [comment]
Would that mean that the result of a calculation like  EUR/MWh * MWh = EUR was still in Euros, or would it just be a number?

**Comment by eriove** [comment]
> 
> 
> Would that mean that the result of a calculation like EUR/MWh * MWh = EUR was still in Euros, or would it just be a number?

It would just be a number. The advantage in the software I created was that we didn't have to care about the currency the end user used. As long as they used the same everywhere the calculations worked out with the correct dimension at the end.

**Comment by angularsen** [comment]
I suspect that UnitsNet's architecture is maybe not a good fit for money.
Perhaps a dedicated library would be better suited.

1. We use double, while decimal or integers are typically used for financial computations.
2. EUR/MWh (unitA/unitB) is difficult to represent in a strongly typed system without an explosion of combinations.


@eriove you said
> In other words that would require implementing a couple of new quantities and/or units in existing units, but the total work would be smaller. @angularsen what do you think?

Not sure I follow what you propose here, could you provide some example?
