### ISSUE TITLE
Get Unit Info form IQuantity

### ISSUE THREAD

**Issue by expertalex** [angularsen/UnitsNet#835]
Hi, thanks for your contribution. I was wondering if is it possible to get the complete information about the Unit form IQuantity Interface? 

For example:

IQuantity quantity = Quantity.From(3, LengthUnit.Centimeter); // Length

Currently:  

quantity.ToString() => 3 cm 

It will be great to have all the Unit Information (Not only the enum value and String, but also the ToString separate form the IQuantity. 

Like: 
quantity.UnitObject.Name => Centimeter 
quantity.UnitObject.ToString() => cm

I saw that we have  UnitParser.cs that parse a unit abbreviation, such as "kg" or "m", to the unit enum value of the enum type
Do we have the reverse? 
**Parse unit enum value of the enum type to the unit abbreviation, such as "kg" or "m"**

Is it possible?
Is it any IUnit Interface?

**Comment by angularsen** [comment]
I believe you can achieve this via `UnitParser` and `UnitAbbreviationsCache`.
Something like this maybe?

```c#
// LINQPad sample
PressureUnit psiUnit = UnitParser.Default.Parse<PressureUnit>("psi").Dump("psiUnit");
PressureUnit psiUnit2 = (PressureUnit)UnitParser.Default.Parse("lb/in²", typeof(PressureUnit)).Dump("psiUnit2");

UnitAbbreviationsCache.Default.GetDefaultAbbreviation(psiUnit).Dump("GetDefaultAbbreviation(psiUnit)");
UnitAbbreviationsCache.Default.GetUnitAbbreviations(psiUnit).Dump("GetUnitAbbreviations(psiUnit)");
```

Output:
![image](https://user-images.githubusercontent.com/787816/92782165-0b1fac80-f3a5-11ea-910e-b90f058b173e.png)


I see what you mean though and how your proposal would be easier to discover, maybe something like this to basically expose the above code example:

- Add new class `UnitInfo` with members
	- `Type UnitEnumType`, example value `typeof(PressureUnit)`
	- `int UnitEnumValue`, example value `1` for `PressureUnit.PoundForcePerSquareInch`
	- `string DefaultAbbreviation`, example value `"psi"`
	- `string[] Abbreviations`, example value `["psi", "lb/in²"]`
- Add new derived class `UnitInfo<TUnitType> : UnitInfo { }` with strongly typed members
	- `TUnit UnitEnumValue`, example value `LengthUnit.Meter`
- Add `public UnitInfo GetUnitInfo()` method to `IQuantity` and implement in concrete types
- Add `public UnitInfo<TUnitType> GetUnitInfo()` method to `IQuantity<TUnitType>` hiding the non-generic one
