### ISSUE TITLE
Add air–fuel equivalence ratio (lambda) unit

### ISSUE THREAD

**Issue by falcoz** [angularsen/UnitsNet#845]
Is it possible to add air-fuel equivalence ratio (lambda) unit?
[https://en.wikipedia.org/wiki/Oxygen_sensor](url)
It's the standard unit used to express the exhaust-gas concentration of oxygen for internal combustion engines, we use it extensively in ECU development.

**Comment by angularsen** [comment]
Hi, this seems like a ratio and not a quantity. We already have `Ratio`
quantity, can you make use of that?

I added a section in the wiki to describe what kind of quantities we may
not accept into the library, let me know if that helps explain things.

https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit#before-you-start

**Comment by falcoz** [comment]
Hi, yes, it's derived from a ratio (quantity of air over quantity of fuel, AFR, [https://en.wikipedia.org/wiki/Air%E2%80%93fuel_ratio](url)) and I can make use of the Ratio quantity; the "problem" is I don't know how to "associate" the correct unit of measure to it so that when calling UnitAbbreviationsCache(unitType, unitValue) I get greek letter lambda...

Maybe there's a way to achieve this with the standard UnitsNet library and I'm just missing something. Do you have any suggestions?

**Comment by angularsen** [comment]
If you are looking to get unit abbreviations for your own custom units, then take a look at 
https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units. The page was outdated, so I spent some effort rewriting it today. Let me know if it helps.

**Comment by falcoz** [comment]
Ok, that helps, thanks!
