### ISSUE TITLE
Add unit prefix to IQuantityInfo

### ISSUE THREAD

**Issue by selmaohneh** [angularsen/UnitsNet#851]
**Is your feature request related to a problem? Please describe.**
I want to use UnitsNet for my project. I have to guarantee compability to a legacy project using a different approach of defining units. The old approach generated a unit like `mbar` / `Millibar` by setting a base unit enum value (i.e. BaseUnit.bar) and a unit prefix enum (i.e. milli). In order to map the units of UnitsNet to the old units, I have to extract both of these information (base unit and prefix) from `IQuantityInfo`. But this information does currently not exist.

**Describe the solution you'd like**
Somewhere inside an `IQuantityInfo` is a readonly property for the unit prefix and the corresponding base unit.

**Comment by angularsen** [comment]
Would you be interested in attempting a pull request for this?

I believe we have all the information we need in the JSON files already, so it would be a matter of updating the code generator to add the information you require.

I'll be happy to assist.

**Comment by selmaohneh** [comment]
Just had a quick peek inside the code.
I assume I have to add the new property `Prefix` to the class `Unit` and the interface `IQuantity`. 
I guess my entry point would be somewhere around `AddPrefixUnits(Quantity quantity)`. Since `Unit` and `IQuantity` are not generated by the code generator (correct me if I'm wrong), I guess the change is kind of straight-forward.

Same here: I'll answer you, when I talked to my colleague!

**Comment by tmilnthorp** [comment]
I think it would be nice to add a generic way to create units. For example
```csharp
var length = 5.0 * Prefixes.Kilo * LenghtUnit.Meter
```

We could also add methods to do things like get prefix unit, as well as methods to convert to lowest possible value/prefix/unit (10 kg = 1g).

**Comment by angularsen** [comment]
You could probably even do something like

```c#
Length length = 5.0.Kilo().Meters;
double lengthMeters = 5.0.Kilo().Meters;

// or to avoid big hit on binary size, similar to the issue we had with number extensions for every unit
Length length = 5.0.Kilo(LengthUnit.Meter);
double lengthMeters = 5.0.Kilo(LengthUnit.Meter);

``` 

with some clever builder patterns and implicit casting,

**Comment by selmaohneh** [comment]
We decided that switching to UnitsNet is out of scope for our sprint. So right now I won't find the time to start implementing it. Freetime is daughter time currently. 😐😊
