### ISSUE TITLE
Culture is the biggest barrier to my use of this library, how do I Chinese?

### ISSUE THREAD

**Issue by chinasqzl** [angularsen/UnitsNet#854]
Culture is the biggest barrier to my use of this library, how do I Chinese?

**Comment by tmilnthorp** [comment]
All that should be necessary is to fill in the abbreviations for the desired culture

**Comment by chinasqzl** [comment]
Need to add, redo the interpretation instead of adding a po file in a similar form?

**Comment by tmilnthorp** [comment]
If you speak it would you be able to add it to the json files and create a pull request?
