### ISSUE TITLE
UnitParser.Default.Parse("m3", typeof(VolumeUnit)) not working

### ISSUE THREAD

**Issue by jstevense-vbe** [angularsen/UnitsNet#855]
**Is your feature request related to a problem? Please describe.**
UnitParser.Default.Parse("m3", typeof(VolumeUnit)) is throwing an exception because only the superscript version is checked.

**Describe the solution you'd like**
Make the UnitParser more flexible by not only checking for m³ but also m3

**Describe alternatives you've considered**
Parsing the unit string myself.

**Comment by angularsen** [comment]
Hi, this would be a great addition. We already support similar schemes for `m^3`:
https://github.com/angularsen/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L103-L132

One pitfall I'm a bit worried about is whether it could conflict with some other unit's abbreviation, but I can't really think of any such cases.

Would you be interested in attempting a pull request? I'm happy to assist.
