### ISSUE TITLE
Setting different unit Description for Unit

### ISSUE THREAD

**Issue by givemysun** [angularsen/UnitsNet#856]
**Is your feature request related to a problem? Please describe.**
We have the quantity Info like this: 
QuantityInfo lengthInfo = Quantity.GetInfo(QuantityType.Length);
And we can get the name of the unit like this:
lengthInfo.UnitNames; 

We also can get the default abbreviation like this:
UnitAbbreviationsCache.Default.GetDefaultAbbreviation(VolumeUnit.Liter); // "l"

**Can we change the UnitNames and the UnitAbbreviations at runtime?**

Will this work for UnitAbbreviations:
UnitAbbreviationsCache.Default.MapUnitToDefaultAbbreviation(VolumeUnit.Liter, "L");

Can we access to the unit DefaultAbbreviations and UnitName from QuantityInfo's UnitInfo? 

**Describe the solution you'd like**
UnitUnitNames Cache.Default.MapUnitToDefaultUnitNames (VolumeUnit.Liter, "Litres "); // Insted of Liter

**Comment by angularsen** [comment]
Hi, this is not currently supported. If you want to attempt a pull request, I'm happy to assist.
