### ISSUE TITLE
Add unit Gauss for MagneticField

### ISSUE THREAD

**Issue by krwq** [angularsen/UnitsNet#860]
Please consider adding Gauss unit. 1 Tesla is 10000 Gauss.

This is used by i.e. [LSM9DS1](https://www.st.com/en/mems-and-sensors/lsm9ds1.html)

**Comment by angularsen** [comment]
If you would like to attempt a pull request, I'm happy to assist.

https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit
https://github.com/angularsen/UnitsNet/blob/master/Common/UnitDefinitions/MagneticField.json

Best,
Andreas
