### ISSUE TITLE
Unit Request: ElectricCurrentChangeRate

### ISSUE THREAD

**Issue by Anthonywolfe** [angularsen/UnitsNet#873]
**Is your feature request related to a problem? Please describe.**
While working on my application I've recently come to need a ElectricCurrentChangeRate unit, Specifically AmpsPerMicrosecond, but AmpsPerMillisecond and AmpsPerSecond will probably be needed down the line.

I was wondering if a PR would be accepted as the wiki suggests opening a issue beforehand.

**Describe the solution you'd like**
The addition of ElectricCurrentChangeRate

**Comment by Anthonywolfe** [comment]
Just found ElectricCurrentGradient covers my needs, guess finding ElectricPotentialChangeRate first tripped me up name wise.

**Comment by angularsen** [comment]
Glad you figured it out!
