### ISSUE TITLE
Specific Entropy * Temperature => Specific Energy

### ISSUE THREAD

**Issue by wiwalsh** [angularsen/UnitsNet#891]
When working with fluids I represent the Enthalpy with SpecificEnergy (Energy/Mass)
The Enthalpy can be calculated a number of ways, but for simplified incompressible fluids it is calculated by
Enthalpy = SpecificHeat * Temperature
or, in UnitsNet units
Specific Energy = SpecificEntropy * Temperature

I can implement this if someone can point me in the right direction.

Thanks,
Scott

Also:
This might also be an opportunity to talk about aliases and if they have been proposed before.  Specific Heat and Specific Entropy are good examples.  They share all the same characteristics, but have different common names.  It makes code readability less simple, and unit conversion similarly difficult.  Is there a way to implement this?

**Comment by angularsen** [comment]
Hi, sorry for late answer. I believe you can implement this by adding operator overloads to `CustomCode/SpecificEntroy.cs` (create the file if it does not already exist).

See
https://github.com/angularsen/UnitsNet/wiki/Adding-operator-overloads

and see how it's done for other quantities.

Let me know if that helps!

As for aliases, this is a much bigger discussion worth its own issue. I believe we have discussed it loosely several times before, but not sure if we have a specific issue for that topic. Please give it a search first.
