### ISSUE TITLE
Units Aware Trig Functions

### ISSUE THREAD

**Issue by wiwalsh** [angularsen/UnitsNet#893]
I am going to write some extension functions that are UnitsNet aware in my personal project and thought it could be universal enough that it could be included here.

Basically I am getting tired of writing
Angle a = Angle.FromDegrees(40);
Angle b = Angle.FromDegrees(40);

to then have to unpack it and repack it later
Angle c = Angle.FromRadians(Math.Atan(0.5*(Math.Tan(a.Radians)+Math.Tan(b.Radians))));

I'd rather do this
Angle c = Atan(0.5*(Tan(a)+Tan(b)));

This will work as the output from an inverse trig function is always an angle, and the output from a direct trig function is a double (or ratio).

Thoughts?

**Comment by angularsen** [comment]
Hi, sure, this sounds useful enough. Please get a pull request started and we can continue the discussion there.
