### ISSUE TITLE
Any (planned) relationship to QUDT? http://www.qudt.org/2.1/vocab/unit

### ISSUE THREAD

**Issue by hubert-associates** [angularsen/UnitsNet#894]
Relationship to W3Cs http://www.qudt.org/2.1/vocab/unit ? 
Thanks!

**Comment by angularsen** [comment]
Hi, never hear of this before.
Could you please help me understand what exactly you would envision adding/changing in Units.NET to establish a relationship?

**Comment by ebfortin** [comment]
I looked quickly and it seems to be trying to solve the same problem as UnitNet. But it's a specification not an implementation. Maybe some interesting concept could be grabbed from it. But I don't see UnitNet as an implementation of QUDT. Would be from what I see a major undertaking.

**Comment by lipchev** [comment]
I have, a while ago, looked into some of the major ontologies ([here's](http://www.semantic-web-journal.net/system/files/swj1825.pdf) the review paper I have bookmarked). 

In terms of "_stealing-from_" - I remember the term _measurement scale_ which I quite liked - [here's](https://github.com/angularsen/UnitsNet/issues/563) the related discussion.

Also- as part of some future v5, I've suggested [extending the JSON definitions](https://github.com/angularsen/UnitsNet/pull/709#issuecomment-538681588) with (optional) links to existing ontological references.

I don't know exactly how this works but I'm guessing there is a use case somewhere for (de)serializing rdf, provided that the reference exists in the UnitInfo.

However I'm yet to discover a single hello world example that communicates with something like a sparql endpoint (such as wiki-data, or even a local store), using anything remotely resembling a POCO (assuming to contain our quantities). If anyone has one available- please, I'd love to check it out.

**Comment by angularsen** [comment]
I'm closing this as no one seems to recognize a concrete feature or change to implement from this. Reopen if someone wants to pursue this further.
