### ISSUE TITLE
Scalar in arithmetic operations

### ISSUE THREAD

**Issue by CallumECameron** [angularsen/UnitsNet#897]
I like the Scalar type introduced in #889 but it doesn't currently play nicely with the existing quantities. All quantities with arithmetic operations should support Scalar in place of double e.g. Scalar * Acceleration or Angle / Scalar.

**Comment by angularsen** [comment]
It makes sense I suppose. 
I just checked, operator overloads supports implicit cast, so if `Scalar` implements implicit cast to `double` then I believe we should be able to reuse all existing operator overloads accepting a `double`. 

![image](https://user-images.githubusercontent.com/787816/111052398-b267c400-845a-11eb-9f98-30e5c3a2c2ab.png)

Would you be interested in attempting a pull request? I'm happy to assist.
A good place to start is adding `Scalar.extra.cs` in [UnitsNet/CustomCode/Quantities/](https://github.com/angularsen/UnitsNet/tree/master/UnitsNet/CustomCode/Quantities).

**Comment by CallumECameron** [comment]
Sounds good, that would work. I have raised a PR, there are a couple of issues but can continue discussion there.
