### ISSUE TITLE
Plural mole in Molarity quantity is inconsistent

### ISSUE THREAD

**Issue by generateui** [angularsen/UnitsNet#898]
All combined units are singular in name part, but mole in Molarity is plural. 

Consistent examples:
- MeterPerSecond (Speed)
- GramPerSecondPerSquareMeter (MassFlux)
- GramPerMole (MolarMass)

Inconsistent units from Molarity quantity:
- CentimolesPerLiter
- DecimolesPerLiter
- MicromolesPerLiter
- MillimolesPerLiter
- MolesPerCubicMeter
- MolesPerLiter
- NanomolesPerLiter
- PicomolesPerLiter

Suggestions to fix:
1. add new units resembling old one but singular and keep api backward compatible
2. change unit names and break api
  - CentimolePerLiter
  - DecimolePerLiter
  - MicromolePerLiter
  - MillimolePerLiter
  - MolePerCubicMeter
  - MolePerLiter
  - NanomolePerLiter
  - PicomolePerLiter

**Comment by angularsen** [comment]
Thanks for pointing out, we would have to deprecate the old ones and add new ones - then remove in v5.
We can mark units obsolete in JSON with `ObsoleteText` I believe it was.

Would you like to attempt a pull request?

**Comment by angularsen** [comment]
Nuget on the way with fix.

[Release UnitsNet/4.118.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.118.0)
