### ISSUE TITLE
InformationUnit do not convert properly

### ISSUE THREAD

**Issue by clemexjeap** [angularsen/UnitsNet#899]
**Describe the bug**
One kilobyte represents 1024 bytes. This is what I've learned at school 35 years ago. But using UnitsNet it gives me 1000.

**To Reproduce**
```
var res1 = Quantity.From(1.0, InformationUnit.Kilobyte);
var res2 = new Information(1.0m, InformationUnit.Kilobyte);
```
Looking at res1 & res2, the value of the property "Bytes" is 1000. All the other conversions are also wrong. Is there a work around?

**Additional context**
Tested using Nuget version 4.83.0

**Comment by angularsen** [comment]
Hi, you are probably looking for Kibibyte, Mibibyte etc . Those are 1024
base.

The industry has been very inconsistent on this over the years causing a
lot of confusion.

Let me know if it helps!

>

**Comment by clemexjeap** [comment]
I'm impressed by your quick reply. Yes Kibibyte, Mibibyte, ... are working fine. Now it's me that is confused !?!?

**Comment by angularsen** [comment]
Happy to help! Yes I was just as amazed as you are when I realized the
difference - and how inconsistent these terms are being used.
