### ISSUE TITLE
Add serialization support for System.Text.Json

### ISSUE THREAD

**Issue by rgomez90** [angularsen/UnitsNet#901]
**Is your feature request related to a problem? Please describe.**

There is no serialization support via `System.Text.Json` so users using this library instead of  `Newtonsoft Json` will need to write their own converters. It would be nice if the library would have built-in support for this.

**Describe the solution you'd like**

Add Serialization support for System.Text.Json

**Describe alternatives you've considered**

Use the built-in feature with Newtonsoft

**Comment by rgomez90** [comment]
I could tackle it this weekend, just wanted to be sure there is no far reason for this "issue" than just not have been implemented for now.

**Comment by angularsen** [comment]
Sounds good, look forward to it!

>
I guess it won't work on net40, so you would probably have to exclude it
for that target framework.
