### ISSUE TITLE
Using source generators

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#902]
Anyone thought about using source generators, a new feature from the latest C# release. Didn't look into it in depth but could potentially, I think, simplify adding new units to UnitNet.

**Comment by angularsen** [comment]
I haven't yet, but yes source generators are super interesting. I do plan to check them out more at some point.

Open to suggestions if someone can point out concrete advantages for UnitsNet, such as making the codegen simpler or faster.

**Comment by angularsen** [comment]
Well written article related to source generators, with the perspective of replacing reflection.
https://blog.marcgravell.com/2021/05/is-era-of-reflection-heavy-c-libraries.html?m=1

**Comment by dglozano** [comment]
@angularsen is this still an option? I've been wanting to look into source generators for a while, and this sounds like a good opportunity to try them out while learning.

**Comment by angularsen** [comment]
Absolutely, have at it 😄 
I don't know enough about it to say whether it's a better approach than our current codegen, but it sure sounds promising.
