### ISSUE TITLE
GitHub Action for Continuous Benchmarking

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#920]
I was waiting for [the PR](https://github.com/rhysd/github-action-benchmark/pull/34) for [this](https://github.com/marketplace/actions/continuous-benchmark-net) to get merged, but as it is still open after nearly a year- I suggest we try out the forked action. 

Granted, we don't have many performance affecting PRs- so we could maybe simply enabled it manually for some commits?

I'm quite a novice on the whole git-hub workflow actions thing, but if there aren't any gotchas this would seem like a cool thing to have.

**Comment by angularsen** [comment]
Sounds cool to me, if you want to give it a try then run with it :D
