### ISSUE TITLE
Is it possible to handle custom units in json serialization?

### ISSUE THREAD

**Issue by giantmustache** [angularsen/UnitsNet#934]
**Is your feature request related to a problem? Please describe.**
I am trying to work out a new unit. Since it is rather custom for our domain, we thought it would be best to work this out via the wiki page: https://github.com/angularsen/UnitsNet/wiki/Extending-with-Custom-Units.

It seems that the json converters cannot handle this new quantity type, since there is a direct check on the assembly to see if it can find the correct unit: https://github.com/angularsen/UnitsNet/blob/207363d8ce3333850be6ff43a6eb3f2249ad7018/UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs#L106-L115

**Describe the solution you'd like**
It would be nice if there would be a fallback mechanism that can also handle custom types. Just like the conversion functions and abbreviations, some kind of mapping mechanism could help to find more types than just the ones in the UnitsNet assembly.

**Describe alternatives you've considered**
As an alternative, I can write my own custom JsonConverter and use a decorator pattern to wrap the UnitsNetIQuantityJsonConverter into my own JsonConverter and ensure that `GetUnit` comes with correct values. These functions are not virtual in UnitsNetBaseJsonConverter, so I will need to make my own implementation and cannot make use of the base class functions.

**Additional context**
It would be much appreciated if the custom units could also be used inside the json serialization context, since this is essential in our software package. I think it will be a good addition to the extensibility of this package.

Greetings,
Marnix

**Comment by angularsen** [comment]
Hi and thanks for describing the issue clearly.
I agree this would be a useful feature. Would you be interested in attempting a pull request?

**Comment by lipchev** [comment]
The enums can be problematic when dealing with extended quantities and while it seems to me like there is gradual pivot towards using the Quantity/UnitInfo's instead (which you can custom-register), I don't think they would be going away completely..
