### ISSUE TITLE
A more Engineering friendly version of UnitsNet

### ISSUE THREAD

**Issue by MadsKirkFoged** [angularsen/UnitsNet#953]
I have been working with creating Engineering tools for years and have been putting UnitsNet into every single one!
My users have been requesting a lot of new features and functionality from UnitsNet but since UnitsNet is more an all around laymans tool I was tasked with creating a more Engineering friendly version of UnitsNet.

I hope it is okay that I ask the users of UnitsNet what they think of [EngineeringUnits](https://github.com/MadsKirkFoged/EngineeringUnits) ?

It is an (almost) interchangeable version of UnitsNet which mean you just have to change the *using* if you already use UnitsNet
```
//using UnitsNet;
//using UnitsNet.Units;

using EngineeringUnits;
using EngineeringUnits.Units;
```
We hope people will try it out.
Nuget Package: EngineeringUnits

Our main focus has been to be able to handle mathematical operations (+-*/) between any unit and to have an easy way of creating alias for units.

We would love your feedback on this project!
And we hope to have a lot of cooperation between the two unitsystems in the future!

**Comment by angularsen** [comment]
Absolutely! And if there are improvements in EngineeringUnits that make sense to port back into UnitsNet, then that is win-win.

These look interesting at first glance:
- Arithmetic between any quantity (defer errors to runtime)
- More precise conversions, I'm curious how you achieved this?
- Aliases, this has been requested a number of times.

**Comment by MadsKirkFoged** [comment]
Yeah port everything you find useful back into UnitsNet!

For the more precise conversions we are using a [Fraction](https://github.com/danm-de/Fractions) class instead of doubles. This way we dont lose pricicsion everytime we divide numbers. However there is no free lunch so we pay in slightly more execution time but it is a tradeoff that is fine for us.
