### ISSUE TITLE
Addition to Nanoframework: Making the angle unit and quantities available.

### ISSUE THREAD

**Issue by PascalChristiaanse** [angularsen/UnitsNet#973]
**Is your feature request related to a problem? Please describe.**
Working with devices like esp32 often involves using motors with position encoders. Storing this and related information in an easy fashion such as an angle class makes kinematics more readable and manageable.

**Describe the solution you'd like**
Perhaps a new Nanoframework package for angle, angular velocity, angular acceleration, moment, and moment of inertia

**Describe alternatives you've considered**
Storing in a double and manually keeping track of units

**Additional context**
Currently developing a kinematics program involving steppermotors on an esp32

**Comment by angularsen** [comment]
Hi, I believe it is a matter of adding more quantities to this file:
https://github.com/angularsen/UnitsNet/blob/master/Build/build-pack-nano-nugets.psm1

We intentionally wanted to start small and only add packages that will be used.

These quantities already exist in the library and simply must be added to the above script to produce nanoframework nugets:
- Angle
- RotationalSpeed
- RotationalAcceleration
- Torque (moment?)

[Angular inertia](https://en.wikipedia.org/wiki/Moment_of_inertia) is currently missing in the library, but can be added: https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit

I think the quantities you propose make sense to add, would you agree @josesimoes ?


@PascalChristiaanse Would you be interested in attempting a PR to add the nanoframework nugets and the new quantity?

**Comment by josesimoes** [comment]
@angularsen absolutely! As long as there is no blocker from the api or features go for it. 

The model and build system are pretty stable and tested by now, so let's have more packages added.

Ping me if I can help with anything.

**Comment by PascalChristiaanse** [comment]
Hi @angularsen, I think id be able to make that happen! I am a student so i don' t have a lot of free time, but i think i can get this done in a few weeks. If there is a forum or other place i can target my questions at id love to know!

**Comment by josesimoes** [comment]
@PascalChristiaanse did you had any time to look further into this? 😉 
Ping me if you need help.
