### ISSUE TITLE
Support for Julian year

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#975]
In Astronomy a year is exactly 365.25 days and is called a Julian year. It is used everywhere years are needed. I propose to add this to the Duration unit. Ref https://en.m.wikipedia.org/wiki/Julian_year_(astronomy)#:~:text=In%20astronomy%2C%20a%20Julian%20year,86400%20SI%20seconds%20each.

If agreed I'll add it to the code and create a PR. 

EDIT: The 86400 seconds statement was not true.

**Comment by angularsen** [comment]
Sounds good to me 👍

**Comment by ebfortin** [comment]
Has been merged through PR #978
