### ISSUE TITLE
Using units in dynamic data in MSTest doesn't seem to work

### ISSUE THREAD

**Issue by dschuermans** [angularsen/UnitsNet#976]
**Describe the bug**
When using UnitsNet units as values in a dynamic data set for a MSTest unit test, the value is lost when the test method is executed

**To Reproduce**
```
private static IEnumerable<object> TestArgs => new[] {
    new object[]{ Length.FromMillimeters(2)}

};

[DataTestMethod]
[DynamicData(nameof(TestArgs))]
public void MyTestMethod(Length value)
{
    Assert.AreEqual(Length.FromMillimeters(2), value);

}
```
Assert.AreEqual will fail, reporting that expected is 2mm and actual is 0m

**Expected behavior**
Assert.AreEqual should pass

**Additional context**
Not entirely sure if this is an issue with UnitsNet objects or an issue with the MSTest framework

**Comment by avocadosalsa** [comment]
I believe MSTest is dependent on ISerializable.

**Comment by Wojmik** [comment]
I have the same issue using my own readonly struct. If I change to class it works fine. Problem has started on version 2.2.5 of MSTest.TestAdapter and MSTest.TestFramework. Up to version 2.2.3 worked fine.

**Comment by dschuermans** [comment]
I'm just going to close this as it is indeed an issue with MSTest and not UnitsNet.

The solution where you opt-out of this new behavior, pointed out by @avocadosalsa does work
