### ISSUE TITLE
ForceChangeRate calculation operators

### ISSUE THREAD

**Issue by Chippychap** [angularsen/UnitsNet#989]
Many units have additional calculation operators which do not require you to work with unitless values.
However, there are no additional operators for the ForceChangeRate unit.

I propose adding the following operators:
```cs
public static Force operator *(Duration left, ForceChangeRate right); //Duration.extra.cs
public static Force operator *(ForceChangeRate left, Duration right); //ForceChangeRate.extra.cs
public static Duration operator /(Force left, ForceChangeRate right); //Force.extra.cs
```

**Comment by angularsen** [comment]
@Chippychap Sounds good to me, would you be willing to attempt a PR? I'm happy to assist.

**Comment by Chippychap** [comment]
I am certainly willing to do this. Will look into it this weekend.

**Comment by angularsen** [comment]
Great!
